INSERT INTO delegacias values (1, '002 DP - Bom Retiro'); 
INSERT INTO delegacias values (2, '012 DP - Pari'); 
INSERT INTO delegacias values (3, '035 DP - Jabaquara'); 
INSERT INTO delegacias values (4, '097 DP - American�polis'); 
INSERT INTO delegacias values (5, '034 DP - Vila Sonia'); 
INSERT INTO delegacias values (6, '046 DP - Perus'); 
INSERT INTO delegacias values (7, '089 DP - Portal do Morumbi'); 
INSERT INTO delegacias values (8, '091 DP - Ceagesp'); 
INSERT INTO delegacias values (9, '009 DP - Carandiru'); 
INSERT INTO delegacias values (10, '040 DP - Vila Santa Maria'); 
INSERT INTO delegacias values (11, '045 DP - Vila Brasil�ndia'); 
INSERT INTO delegacias values (12, '072 DP - Vila Penteado'); 
INSERT INTO delegacias values (13, '073 DP - Ja�an�'); 
INSERT INTO delegacias values (14, '074 DP - Jaragu�'); 
INSERT INTO delegacias values (15, '090 DP - Parque Novo Mundo'); 
INSERT INTO delegacias values (16, '010 DP - Penha de Fran�a'); 
INSERT INTO delegacias values (17, '057 DP - Parque da Mo�ca'); 
INSERT INTO delegacias values (18, '011 DP - Santo Amaro'); 
INSERT INTO delegacias values (19, '025 DP - Parelheiros'); 
INSERT INTO delegacias values (20, '047 DP - Cap�o Redondo'); 
INSERT INTO delegacias values (21, '085 DP - Jardim Mirna'); 
INSERT INTO delegacias values (22, '092 DP - Parque Santo Ant�nio'); 
INSERT INTO delegacias values (23, '098 DP - Jardim M�riam'); 
INSERT INTO delegacias values (24, '100 DP - Jardim Herculano'); 
INSERT INTO delegacias values (25, '032 DP - Itaquera'); 
INSERT INTO delegacias values (26, '059 DP - Jardim Noemia'); 
INSERT INTO delegacias values (27, '062 DP - Ermelino Matarazzo'); 
INSERT INTO delegacias values (28, '063 DP - Vila Jacu�'); 
INSERT INTO delegacias values (29, '064 DP - Cidade A E Carvalho'); 
INSERT INTO delegacias values (30, '054 DP - Cidade Tiradentes'); 
INSERT INTO delegacias values (31, '066 DP - Vale do Aricanduva'); 
INSERT INTO delegacias values (32, '069 DP - Teot�nio Vilela'); 
INSERT INTO delegacias values (33, '070 DP - Vila Ema'); 
INSERT INTO delegacias values (34, '003 DP - Cruzeiro'); 
INSERT INTO delegacias values (35, 'DM - Cunha'); 
INSERT INTO delegacias values (36, '001 DP - Lorena'); 
INSERT INTO delegacias values (37, '002 DP - Lorena'); 
INSERT INTO delegacias values (38, 'DM - Piquete'); 
INSERT INTO delegacias values (39, '002 DP - Jacare�'); 
INSERT INTO delegacias values (40, 'DM - Ca�apava'); 
INSERT INTO delegacias values (41, '001 DP - S�o Jose dos Campos'); 
INSERT INTO delegacias values (42, '006 DP - S�o Jose dos Campos'); 
INSERT INTO delegacias values (43, '001 DP - Caraguatatuba'); 
INSERT INTO delegacias values (44, '002 DP - Caraguatatuba'); 
INSERT INTO delegacias values (45, 'DM - Ubatuba'); 
INSERT INTO delegacias values (46, '001 DP - Campos do Jord�o'); 
INSERT INTO delegacias values (47, 'DM - Natividade da Serrra'); 
INSERT INTO delegacias values (48, '001 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (49, '002 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (50, '002 DP - Taubat�'); 
INSERT INTO delegacias values (51, '004 DP - Taubat�'); 
INSERT INTO delegacias values (52, 'DM - Trememb�'); 
INSERT INTO delegacias values (53, '003 DP - Ara�atuba'); 
INSERT INTO delegacias values (54, 'DM - Guararapes'); 
INSERT INTO delegacias values (55, 'DM - Luiziania'); 
INSERT INTO delegacias values (56, '003 DP - Campinas'); 
INSERT INTO delegacias values (57, '004 DP - Campinas'); 
INSERT INTO delegacias values (58, '005 DP - Campinas'); 
INSERT INTO delegacias values (59, 'DM - Vinhedo'); 
INSERT INTO delegacias values (60, '009 DP - Campinas'); 
INSERT INTO delegacias values (61, '011 DP - Campinas'); 
INSERT INTO delegacias values (62, 'DM - �guas de Lind�ia'); 
INSERT INTO delegacias values (63, '001 DP - Atibaia'); 
INSERT INTO delegacias values (64, 'DM - Atibaia'); 
INSERT INTO delegacias values (65, '005 DP - Jundiai'); 
INSERT INTO delegacias values (66, 'DM - Itapira'); 
INSERT INTO delegacias values (67, '002 DP - Mogi-Gua�u'); 
INSERT INTO delegacias values (68, '003 DP - Mogi-Gua�u'); 
INSERT INTO delegacias values (69, 'DM - Sto. Ant�nio de Posse'); 
INSERT INTO delegacias values (70, '001 DP - Araraquara'); 
INSERT INTO delegacias values (71, '003 DP - Araraquara'); 
INSERT INTO delegacias values (72, '001 DP - Matao'); 
INSERT INTO delegacias values (73, '003 DP - Barretos'); 
INSERT INTO delegacias values (74, 'DM - Col�mbia'); 
INSERT INTO delegacias values (75, '003 DP - Bebedouro'); 
INSERT INTO delegacias values (76, 'DM - Monte Azul Paulista'); 
INSERT INTO delegacias values (77, '004 DP - Franca'); 
INSERT INTO delegacias values (78, 'DM - Guar�'); 
INSERT INTO delegacias values (79, 'DM - Altin�polis'); 
INSERT INTO delegacias values (80, 'DM - Cravinhos'); 
INSERT INTO delegacias values (81, '002 DP - Ribeir�o Preto'); 
INSERT INTO delegacias values (82, '003 DP - Ribeir�o Preto'); 
INSERT INTO delegacias values (83, 'DM - Descalvado'); 
INSERT INTO delegacias values (84, 'DM - Ibat�'); 
INSERT INTO delegacias values (85, 'DM - Porto Ferreira'); 
INSERT INTO delegacias values (86, '001 DP - S�o Carlos'); 
INSERT INTO delegacias values (87, '002 DP - S�o Carlos'); 
INSERT INTO delegacias values (88, '005 DP - S�o Carlos'); 
INSERT INTO delegacias values (89, 'DM - Pontal'); 
INSERT INTO delegacias values (90, 'DM - Prad�polis'); 
INSERT INTO delegacias values (91, 'DM - Sert�ozinho'); 
INSERT INTO delegacias values (92, '001 DP - Bauru'); 
INSERT INTO delegacias values (93, '002 DP - Bauru'); 
INSERT INTO delegacias values (94, 'DM - Len��is Paulista'); 
INSERT INTO delegacias values (95, '003 DP - Mar�lia'); 
INSERT INTO delegacias values (96, '003 DP - Catanduva'); 
INSERT INTO delegacias values (97, '004 DP - Catanduva'); 
INSERT INTO delegacias values (98, 'DM - Adolfo'); 
INSERT INTO delegacias values (99, 'DM - Balsamo'); 
INSERT INTO delegacias values (100, '001 DP - Mirassol'); 
INSERT INTO delegacias values (101, '002 DP - S�o Jos� do Rio Preto'); 
INSERT INTO delegacias values (102, '004 DP - S�o Jos� do Rio Preto'); 
INSERT INTO delegacias values (103, '005 DP - S�o Jos� do Rio Preto'); 
INSERT INTO delegacias values (104, '006 DP - S�o Jos� do Rio Preto'); 
INSERT INTO delegacias values (105, '007 DP - S�o Jos� do Rio Preto'); 
INSERT INTO delegacias values (106, 'DM - Tanabi'); 
INSERT INTO delegacias values (107, '002 DP - Votuporanga'); 
INSERT INTO delegacias values (108, 'DM - Itariri'); 
INSERT INTO delegacias values (109, 'DM - Cajati'); 
INSERT INTO delegacias values (110, '001 DP - Iguape'); 
INSERT INTO delegacias values (111, 'DM - Miracat�'); 
INSERT INTO delegacias values (112, '001 DP - Guaruj�'); 
INSERT INTO delegacias values (113, '002 DP - Guaruj�'); 
INSERT INTO delegacias values (114, 'DM - Guaruj�'); 
INSERT INTO delegacias values (115, '002 DP - Praia Grande'); 
INSERT INTO delegacias values (116, 'DM - Praia Grande'); 
INSERT INTO delegacias values (117, '004 DP - Santos'); 
INSERT INTO delegacias values (118, '005 DP - Santos'); 
INSERT INTO delegacias values (119, '002 DP - S�o Vicente'); 
INSERT INTO delegacias values (120, 'DM - Ita�'); 
INSERT INTO delegacias values (121, 'DM - Piraj�'); 
INSERT INTO delegacias values (122, 'DM - Boituva'); 
INSERT INTO delegacias values (123, 'DM - Apia�'); 
INSERT INTO delegacias values (124, 'DM - Ara�ariguama'); 
INSERT INTO delegacias values (125, 'DM - Ara�oiba da Serra'); 
INSERT INTO delegacias values (126, 'DM - Iper�'); 
INSERT INTO delegacias values (127, '002 DP - It�'); 
INSERT INTO delegacias values (128, 'DM - Salto de Pirapora'); 
INSERT INTO delegacias values (129, '001 DP - Sorocaba'); 
INSERT INTO delegacias values (130, '008 DP - Sorocaba'); 
INSERT INTO delegacias values (131, '002 DP - Assis'); 
INSERT INTO delegacias values (132, '003 DP - Assis'); 
INSERT INTO delegacias values (133, 'DM - Tupi Pta.'); 
INSERT INTO delegacias values (134, '001 DP - Presidente Prudente'); 
INSERT INTO delegacias values (135, 'DM - Caiu�'); 
INSERT INTO delegacias values (136, 'DM - Piquerobi'); 
INSERT INTO delegacias values (137, '001 DP - Americana'); 
INSERT INTO delegacias values (138, '004 DP - Americana'); 
INSERT INTO delegacias values (139, 'DM - Cosm�polis'); 
INSERT INTO delegacias values (140, '001 DP - Hortol�ndia'); 
INSERT INTO delegacias values (141, '002 DP - Hortol�ndia'); 
INSERT INTO delegacias values (142, 'DM - Hortol�ndia'); 
INSERT INTO delegacias values (143, '003 DP - Sumar�'); 
INSERT INTO delegacias values (144, '002 DP - Araras'); 
INSERT INTO delegacias values (145, '004 DP - Limeira'); 
INSERT INTO delegacias values (146, '003 DP - Rio Claro'); 
INSERT INTO delegacias values (147, 'DM - Sta. Gertrudes'); 
INSERT INTO delegacias values (148, '001 DP - Barueri'); 
INSERT INTO delegacias values (149, '001 DP - Carapicuiba'); 
INSERT INTO delegacias values (150, '002 DP - Carapicuiba'); 
INSERT INTO delegacias values (151, '003 DP - Carapicuiba'); 
INSERT INTO delegacias values (152, '001 DP - Cotia'); 
INSERT INTO delegacias values (153, '002 DP - Cotia'); 
INSERT INTO delegacias values (154, 'DM - Itapevi'); 
INSERT INTO delegacias values (155, '001 DP - Diadema'); 
INSERT INTO delegacias values (156, '002 DP - Diadema'); 
INSERT INTO delegacias values (157, 'DM - Francisco Morato'); 
INSERT INTO delegacias values (158, 'DM - Franco da Rocha'); 
INSERT INTO delegacias values (159, '002 DP - Guarulhos'); 
INSERT INTO delegacias values (160, '004 DP - Guarulhos'); 
INSERT INTO delegacias values (161, '005 DP - Guarulhos'); 
INSERT INTO delegacias values (162, '006 DP - Guarulhos'); 
INSERT INTO delegacias values (163, '007 DP - Guarulhos'); 
INSERT INTO delegacias values (164, '008 DP - Guarulhos'); 
INSERT INTO delegacias values (165, '009 DP - Guarulhos'); 
INSERT INTO delegacias values (166, 'DM - Santa Isabel'); 
INSERT INTO delegacias values (167, '001 DP - Itaquaquecetuba'); 
INSERT INTO delegacias values (168, 'DM - Itaquaquecetuba'); 
INSERT INTO delegacias values (169, '001 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (170, '002 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (171, '003 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (172, '001 DP - Suzano'); 
INSERT INTO delegacias values (173, '002 DP - Suzano'); 
INSERT INTO delegacias values (174, 'DM - Suzano'); 
INSERT INTO delegacias values (175, '002 DP - Osasco'); 
INSERT INTO delegacias values (176, '004 DP - Osasco'); 
INSERT INTO delegacias values (177, '008 DP - Osasco'); 
INSERT INTO delegacias values (178, '010 DP - Osasco'); 
INSERT INTO delegacias values (179, '003 DP - Mau�'); 
INSERT INTO delegacias values (180, '004 DP - Mau�'); 
INSERT INTO delegacias values (181, 'DM - Ribeir�o Pires'); 
INSERT INTO delegacias values (182, '004 DP - Santo Andr�'); 
INSERT INTO delegacias values (183, '006 DP - Santo Andr�'); 
INSERT INTO delegacias values (184, '004 DP - S�o Bernardo do Campo'); 
INSERT INTO delegacias values (185, '008 DP - S�o Bernardo do Campo'); 
INSERT INTO delegacias values (186, '003 DP - S. Caetano do Sul'); 
INSERT INTO delegacias values (187, 'DM - Emb�'); 
INSERT INTO delegacias values (188, 'DM - Emb� Gua��'); 
INSERT INTO delegacias values (189, 'DM - Itapecerica da Serra'); 
INSERT INTO delegacias values (190, '001 DP - Tabo�o da Serra'); 
INSERT INTO delegacias values (191, '001 DP - S�'); 
INSERT INTO delegacias values (192, '003 DP - Campos El�sios'); 
INSERT INTO delegacias values (193, '004 DP - Consola��o'); 
INSERT INTO delegacias values (194, '077 DP - Santa Cec�lia'); 
INSERT INTO delegacias values (195, '027 DP - Campo Belo'); 
INSERT INTO delegacias values (196, '015 DP - Itaim Bibi'); 
INSERT INTO delegacias values (197, '023 DP - Perdizes'); 
INSERT INTO delegacias values (198, '033 DP - Pirituba'); 
INSERT INTO delegacias values (199, '037 DP - Campo Limpo'); 
INSERT INTO delegacias values (200, '087 DP - Vila Pereira Barreto'); 
INSERT INTO delegacias values (201, '020 DP - �gua Fria'); 
INSERT INTO delegacias values (202, '021 DP - Vila Matilde'); 
INSERT INTO delegacias values (203, '030 DP - Tatuap�'); 
INSERT INTO delegacias values (204, '099 DP - Campo Grande'); 
INSERT INTO delegacias values (205, '101 DP - Jardim das Imbuias'); 
INSERT INTO delegacias values (206, '022 DP - S�o Miguel Paulista'); 
INSERT INTO delegacias values (207, '050 DP - Itaim Paulista'); 
INSERT INTO delegacias values (208, '067 DP - Jardim Robru'); 
INSERT INTO delegacias values (209, '068 DP - Lajeado'); 
INSERT INTO delegacias values (210, '049 DP - S�o Mateus'); 
INSERT INTO delegacias values (211, '053 DP - Parque do Carmo'); 
INSERT INTO delegacias values (212, '002 DP - Cruzeiro'); 
INSERT INTO delegacias values (213, '002 DP - Guaratinguet�'); 
INSERT INTO delegacias values (214, '003 DP - Guaratinguet�'); 
INSERT INTO delegacias values (215, 'DM - Igarat�'); 
INSERT INTO delegacias values (216, '004 DP - Jacare�'); 
INSERT INTO delegacias values (217, '002 DP - S�o Jose dos Campos'); 
INSERT INTO delegacias values (218, '003 DP - S�o Jose dos Campos'); 
INSERT INTO delegacias values (219, 'DM - Campos do Jord�o'); 
INSERT INTO delegacias values (220, '003 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (221, '003 DP - Taubat�'); 
INSERT INTO delegacias values (222, 'DM - Pereira Barreto'); 
INSERT INTO delegacias values (223, '001 DP - Birigui'); 
INSERT INTO delegacias values (224, 'DM - Brejo Alegre'); 
INSERT INTO delegacias values (225, 'DM - Piacatu'); 
INSERT INTO delegacias values (226, '007 DP - Campinas'); 
INSERT INTO delegacias values (227, '010 DP - Campinas'); 
INSERT INTO delegacias values (228, 'DM - Paul�nea'); 
INSERT INTO delegacias values (229, '002 DP - Campinas'); 
INSERT INTO delegacias values (230, '006 DP - Campinas'); 
INSERT INTO delegacias values (231, '008 DP - Campinas'); 
INSERT INTO delegacias values (232, '002 DP - Bragan�a Pta.'); 
INSERT INTO delegacias values (233, 'DM - Campo Limpo Pta.'); 
INSERT INTO delegacias values (234, 'DM - Itupeva'); 
INSERT INTO delegacias values (235, 'DM - Jarin�'); 
INSERT INTO delegacias values (236, '007 DP - Jundiai'); 
INSERT INTO delegacias values (237, 'DM - Tabatinga'); 
INSERT INTO delegacias values (238, 'DM - Pirangi'); 
INSERT INTO delegacias values (239, 'DM - Taia�u'); 
INSERT INTO delegacias values (240, '002 DP - Franca'); 
INSERT INTO delegacias values (241, 'DM - Jeriguara'); 
INSERT INTO delegacias values (242, '007 DP - Ribeir�o Preto'); 
INSERT INTO delegacias values (243, '004 DP - S�o Carlos'); 
INSERT INTO delegacias values (244, 'DM - Monte Alto'); 
INSERT INTO delegacias values (245, '004 DP - Bauru'); 
INSERT INTO delegacias values (246, 'DM - Pederneiras'); 
INSERT INTO delegacias values (247, 'DM - Igara�u do Tiet�'); 
INSERT INTO delegacias values (248, '003 DP - Ja�'); 
INSERT INTO delegacias values (249, '001 DP - Lins'); 
INSERT INTO delegacias values (250, '002 DP - Lins'); 
INSERT INTO delegacias values (251, 'DM - Sabino'); 
INSERT INTO delegacias values (252, '001 DP - Mar�lia'); 
INSERT INTO delegacias values (253, '004 DP - Mar�lia'); 
INSERT INTO delegacias values (254, 'DM - Esp. Sto. Do Turvo'); 
INSERT INTO delegacias values (255, 'DM - Bastos'); 
INSERT INTO delegacias values (256, '002 DP - Catanduva'); 
INSERT INTO delegacias values (257, 'DM - Urupes'); 
INSERT INTO delegacias values (258, 'DM - Mirassol'); 
INSERT INTO delegacias values (259, '003 DP - S�o Jos� do Rio Preto'); 
INSERT INTO delegacias values (260, 'DM - Zacarias'); 
INSERT INTO delegacias values (261, '002 DP - Itanhaem'); 
INSERT INTO delegacias values (262, 'DM - Iporanga'); 
INSERT INTO delegacias values (263, '001 DP - Jacupiranga'); 
INSERT INTO delegacias values (264, 'DM - Bertioga'); 
INSERT INTO delegacias values (265, '001 DP - Cubat�o'); 
INSERT INTO delegacias values (266, '003 DP - Cubat�o'); 
INSERT INTO delegacias values (267, '003 DP - S�o Vicente'); 
INSERT INTO delegacias values (268, '001 DP - Avar�'); 
INSERT INTO delegacias values (269, 'DM - Iaras'); 
INSERT INTO delegacias values (270, '002 DP - Botucatu'); 
INSERT INTO delegacias values (271, 'DM - Itatinga'); 
INSERT INTO delegacias values (272, '001 DP - Itapetininga'); 
INSERT INTO delegacias values (273, '002 DP - Tatu�'); 
INSERT INTO delegacias values (274, 'DM - Tatu�'); 
INSERT INTO delegacias values (275, 'DM - Ibi�na'); 
INSERT INTO delegacias values (276, 'DM - Pilar do Sul'); 
INSERT INTO delegacias values (277, 'DM - Porto Feliz'); 
INSERT INTO delegacias values (278, '001 DP - Salto'); 
INSERT INTO delegacias values (279, '002 DP - Salto'); 
INSERT INTO delegacias values (280, '002 DP - Sorocaba'); 
INSERT INTO delegacias values (281, '003 DP - Sorocaba'); 
INSERT INTO delegacias values (282, '009 DP - Sorocaba'); 
INSERT INTO delegacias values (283, '002 DP - Votorantim'); 
INSERT INTO delegacias values (284, '003 DP - Votorantim'); 
INSERT INTO delegacias values (285, '001 DP - Osvaldo Cruz'); 
INSERT INTO delegacias values (286, '003 DP - Presidente Prudente'); 
INSERT INTO delegacias values (287, 'DM - Regente Feij�'); 
INSERT INTO delegacias values (288, 'DM - Mir. Paranapanema'); 
INSERT INTO delegacias values (289, 'DM - Monte Mor'); 
INSERT INTO delegacias values (290, '002 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (291, '001 DP - Sumar�'); 
INSERT INTO delegacias values (292, 'DM - Torrinha'); 
INSERT INTO delegacias values (293, 'DM - Agua�'); 
INSERT INTO delegacias values (294, '002 DP - S�o Jo�o da Boa Vista'); 
INSERT INTO delegacias values (295, '002 DP - de Barueri'); 
INSERT INTO delegacias values (296, 'DM - Jandira'); 
INSERT INTO delegacias values (297, 'DM - Pirapora do Bom Jesus'); 
INSERT INTO delegacias values (298, '003 DP - Diadema'); 
INSERT INTO delegacias values (299, '004 DP - Diadema'); 
INSERT INTO delegacias values (300, 'DM - Mairipor�'); 
INSERT INTO delegacias values (301, 'DM - Aruja'); 
INSERT INTO delegacias values (302, 'DM - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (303, 'DM - Po�'); 
INSERT INTO delegacias values (304, '001 DP - Osasco'); 
INSERT INTO delegacias values (305, '006 DP - Osasco'); 
INSERT INTO delegacias values (306, '001 DP - Mau�'); 
INSERT INTO delegacias values (307, '002 DP - Santo Andr�'); 
INSERT INTO delegacias values (308, '003 DP - S�o Bernardo do Campo'); 
INSERT INTO delegacias values (309, '006 DP - S�o Bernardo do Campo'); 
INSERT INTO delegacias values (310, 'DM - S. Caetano do Sul'); 
INSERT INTO delegacias values (311, '001 DP - Emb�'); 
INSERT INTO delegacias values (312, '005 DP - Aclima��o'); 
INSERT INTO delegacias values (313, '006 DP - Cambuci'); 
INSERT INTO delegacias values (314, '008 DP - Br�s'); 
INSERT INTO delegacias values (315, '017 DP - Ipiranga'); 
INSERT INTO delegacias values (316, '026 DP - Sacom�'); 
INSERT INTO delegacias values (317, '083 DP - Parque Bristol'); 
INSERT INTO delegacias values (318, '075 DP - Jardim Arpoador'); 
INSERT INTO delegacias values (319, '029 DP - Vila Diva'); 
INSERT INTO delegacias values (320, '065 DP - Artur Alvim'); 
INSERT INTO delegacias values (321, 'DM - Canas'); 
INSERT INTO delegacias values (322, 'DM - Potim'); 
INSERT INTO delegacias values (323, 'DM - Roseira'); 
INSERT INTO delegacias values (324, '001 DP - Jacare�'); 
INSERT INTO delegacias values (325, 'DM - Caraguatatuba'); 
INSERT INTO delegacias values (326, '002 DP - S�o Sebasti�o'); 
INSERT INTO delegacias values (327, '004 DP - S�o Sebasti�o'); 
INSERT INTO delegacias values (328, 'DM - Castilho'); 
INSERT INTO delegacias values (329, 'DM - Sud Menucci'); 
INSERT INTO delegacias values (330, '002 DP - Ara�atuba'); 
INSERT INTO delegacias values (331, 'DM - Penapolis'); 
INSERT INTO delegacias values (332, '001 DP - Campinas'); 
INSERT INTO delegacias values (333, '001 DP - Indaiatuba'); 
INSERT INTO delegacias values (334, 'DM - Bom Jesus dos Perd�es'); 
INSERT INTO delegacias values (335, '001 DP - Itatiba'); 
INSERT INTO delegacias values (336, '002 DP - Jundiai'); 
INSERT INTO delegacias values (337, '004 DP - Jundiai'); 
INSERT INTO delegacias values (338, '006 DP - Jundiai'); 
INSERT INTO delegacias values (339, 'DM - Am�rico Brasiliense'); 
INSERT INTO delegacias values (340, 'DM - Colina'); 
INSERT INTO delegacias values (341, '002 DP - Bebedouro'); 
INSERT INTO delegacias values (342, 'DM - Viradouro'); 
INSERT INTO delegacias values (343, 'DM - Pedregulho'); 
INSERT INTO delegacias values (344, 'DM - Rifaina'); 
INSERT INTO delegacias values (345, '003 DP - S�o Carlos'); 
INSERT INTO delegacias values (346, 'DM - Barrinha'); 
INSERT INTO delegacias values (347, '001 DP - Jaboticabal'); 
INSERT INTO delegacias values (348, '002 DP - Jaboticabal'); 
INSERT INTO delegacias values (349, '003 DP - Lins'); 
INSERT INTO delegacias values (350, 'DM - Bern. De Campos'); 
INSERT INTO delegacias values (351, 'DM - Salto Grande'); 
INSERT INTO delegacias values (352, '001 DP - Sta. F� do Sul'); 
INSERT INTO delegacias values (353, 'DM - Sta. F� do Sul'); 
INSERT INTO delegacias values (354, 'DM - Bady Bassit'); 
INSERT INTO delegacias values (355, 'DM - Nipo�'); 
INSERT INTO delegacias values (356, 'DM - Riol�ndia'); 
INSERT INTO delegacias values (357, '001 DP - Votuporanga'); 
INSERT INTO delegacias values (358, '003 DP - Votuporanga'); 
INSERT INTO delegacias values (359, '001 DP - Peru�be'); 
INSERT INTO delegacias values (360, '003 DP - Praia Grande'); 
INSERT INTO delegacias values (361, '001 DP - S�o Vicente'); 
INSERT INTO delegacias values (362, 'DM - Capela do Alto'); 
INSERT INTO delegacias values (363, 'DM - Sarapu�'); 
INSERT INTO delegacias values (364, '003 DP - It�'); 
INSERT INTO delegacias values (365, '011 DP - Sorocaba'); 
INSERT INTO delegacias values (366, '001 DP - Votorantim'); 
INSERT INTO delegacias values (367, 'DM - Votorantim'); 
INSERT INTO delegacias values (368, '003 DP - Adamantina'); 
INSERT INTO delegacias values (369, 'DM - Paragua�� Pta.'); 
INSERT INTO delegacias values (370, '006 DP - Presidente Prudente'); 
INSERT INTO delegacias values (371, 'DM - Teodoro Sampaio'); 
INSERT INTO delegacias values (372, '003 DP - Americana'); 
INSERT INTO delegacias values (373, '003 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (374, '002 DP - Sumar�'); 
INSERT INTO delegacias values (375, 'DM - Casa Branca'); 
INSERT INTO delegacias values (376, 'DM - Sta. Cruz das Palmeiras'); 
INSERT INTO delegacias values (377, '001 DP - Araras'); 
INSERT INTO delegacias values (378, '001 DP - Leme'); 
INSERT INTO delegacias values (379, '001 DP - Limeira'); 
INSERT INTO delegacias values (380, '002 DP - Limeira'); 
INSERT INTO delegacias values (381, '003 DP - Limeira'); 
INSERT INTO delegacias values (382, '003 DP - Piracicaba'); 
INSERT INTO delegacias values (383, '007 DP - Piracicaba'); 
INSERT INTO delegacias values (384, 'DM - S�o Pedro'); 
INSERT INTO delegacias values (385, 'DM - Barueri'); 
INSERT INTO delegacias values (386, 'DM - Cotia'); 
INSERT INTO delegacias values (387, 'DM - Santana do Parnaiba'); 
INSERT INTO delegacias values (388, 'DM - Vargem Grande Paulista'); 
INSERT INTO delegacias values (389, '003 DP - Guarulhos'); 
INSERT INTO delegacias values (390, '009 DP - Osasco'); 
INSERT INTO delegacias values (391, '001 DP - S�o Bernardo do Campo'); 
INSERT INTO delegacias values (392, '007 DP - S�o Bernardo do Campo'); 
INSERT INTO delegacias values (393, '001 DP - Itapecerica da Serra'); 
INSERT INTO delegacias values (394, 'DM - Juquitiba'); 
INSERT INTO delegacias values (395, '002 DP - Tabo�o da Serra'); 
INSERT INTO delegacias values (396, '078 DP - Jardins'); 
INSERT INTO delegacias values (397, '051 DP - Butant�'); 
INSERT INTO delegacias values (398, '013 DP - Casa Verde'); 
INSERT INTO delegacias values (399, '019 DP - Vila Maria'); 
INSERT INTO delegacias values (400, '028 DP - Freguesia do �'); 
INSERT INTO delegacias values (401, '039 DP - Vila Gustavo'); 
INSERT INTO delegacias values (402, '031 DP - Vila Carr�o'); 
INSERT INTO delegacias values (403, '052 DP - Parque S�o Jorge'); 
INSERT INTO delegacias values (404, '043 DP - Cidade Ademar'); 
INSERT INTO delegacias values (405, '048 DP - Cidade Dutra'); 
INSERT INTO delegacias values (406, '080 DP - Vila Joaniza'); 
INSERT INTO delegacias values (407, '103 DP - Cohab Itaquera'); 
INSERT INTO delegacias values (408, '041 DP - Vila Rica'); 
INSERT INTO delegacias values (409, '044 DP - Guaianazes'); 
INSERT INTO delegacias values (410, '055 DP - Parque S�o Rafael'); 
INSERT INTO delegacias values (411, '004 DP - S�o Jose dos Campos'); 
INSERT INTO delegacias values (412, '005 DP - S�o Jose dos Campos'); 
INSERT INTO delegacias values (413, '007 DP - S�o Jose dos Campos'); 
INSERT INTO delegacias values (414, '001 DP - Andradina'); 
INSERT INTO delegacias values (415, 'DM - Birigui'); 
INSERT INTO delegacias values (416, 'DM - Valparaiso'); 
INSERT INTO delegacias values (417, '001 DP - Bragan�a Pta.'); 
INSERT INTO delegacias values (418, '003 DP - Bragan�a Pta.'); 
INSERT INTO delegacias values (419, 'DM - Louveira'); 
INSERT INTO delegacias values (420, 'DM - It�polis'); 
INSERT INTO delegacias values (421, 'DM - Batatais'); 
INSERT INTO delegacias values (422, '005 DP - Franca'); 
INSERT INTO delegacias values (423, 'DM - Ituverava'); 
INSERT INTO delegacias values (424, '006 DP - Ribeir�o Preto'); 
INSERT INTO delegacias values (425, '008 DP - Ribeir�o Preto'); 
INSERT INTO delegacias values (426, 'DM - Guariba'); 
INSERT INTO delegacias values (427, 'DM - Agudos'); 
INSERT INTO delegacias values (428, '003 DP - Bauru'); 
INSERT INTO delegacias values (429, 'DM - Dois C�rregos'); 
INSERT INTO delegacias values (430, 'DM - Promiss�o'); 
INSERT INTO delegacias values (431, '002 DP - Mar�lia'); 
INSERT INTO delegacias values (432, '001 DP - Tup�'); 
INSERT INTO delegacias values (433, 'DM - Pindorama'); 
INSERT INTO delegacias values (434, 'DM - Ouroeste'); 
INSERT INTO delegacias values (435, 'DM - Jos� Bonif�cio'); 
INSERT INTO delegacias values (436, '002 DP - Registro'); 
INSERT INTO delegacias values (437, '003 DP - Santos'); 
INSERT INTO delegacias values (438, 'DM - Prat�nia'); 
INSERT INTO delegacias values (439, 'DM - Angatuba'); 
INSERT INTO delegacias values (440, 'DM - Guarei'); 
INSERT INTO delegacias values (441, 'DM - Rib. Branco'); 
INSERT INTO delegacias values (442, 'DM - Mairinque'); 
INSERT INTO delegacias values (443, 'DM - Piedade'); 
INSERT INTO delegacias values (444, '006 DP - Sorocaba'); 
INSERT INTO delegacias values (445, 'DM - Tiete'); 
INSERT INTO delegacias values (446, 'DM - Irapuru'); 
INSERT INTO delegacias values (447, '001 DP - Assis'); 
INSERT INTO delegacias values (448, 'DM - Campos Novos Pta.'); 
INSERT INTO delegacias values (449, '001 DP - Dracena'); 
INSERT INTO delegacias values (450, '002 DP - Americana'); 
INSERT INTO delegacias values (451, 'DM - Engenheiro Coelho'); 
INSERT INTO delegacias values (452, 'DM - Nova Odessa'); 
INSERT INTO delegacias values (453, '004 DP - Sumar�'); 
INSERT INTO delegacias values (454, '005 DP - Sumar�'); 
INSERT INTO delegacias values (455, 'DM - Mococa'); 
INSERT INTO delegacias values (456, '002 DP - Leme'); 
INSERT INTO delegacias values (457, '002 DP - Pirassununga'); 
INSERT INTO delegacias values (458, 'DM - Elias Fausto'); 
INSERT INTO delegacias values (459, '006 DP - Piracicaba'); 
INSERT INTO delegacias values (460, 'DM - Rio das Pedras'); 
INSERT INTO delegacias values (461, 'DM - Vargem Grande do Sul'); 
INSERT INTO delegacias values (462, '001 DP - Caieiras'); 
INSERT INTO delegacias values (463, 'DM - Cajamar'); 
INSERT INTO delegacias values (464, '004 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (465, 'DM - Rio Grande da Serra'); 
INSERT INTO delegacias values (466, '001 DP - Santo Andr�'); 
INSERT INTO delegacias values (467, '003 DP - Santo Andr�'); 
INSERT INTO delegacias values (468, 'DM - S�o Louren�o da Serra'); 
INSERT INTO delegacias values (469, '095 DP - Heli�polis'); 
INSERT INTO delegacias values (470, '093 DP - Jaguar�'); 
INSERT INTO delegacias values (471, '038 DP - Vila Am�lia'); 
INSERT INTO delegacias values (472, '102 DP - Socorro'); 
INSERT INTO delegacias values (473, 'DM - S�o Jos� do Barreiro'); 
INSERT INTO delegacias values (474, '001 DP - S�o Sebasti�o'); 
INSERT INTO delegacias values (475, '002 DP - Andradina'); 
INSERT INTO delegacias values (476, 'DM - Coroados'); 
INSERT INTO delegacias values (477, '002 DP - Amparo'); 
INSERT INTO delegacias values (478, 'DM - V�rzea Pta.'); 
INSERT INTO delegacias values (479, '001 DP - Itapira'); 
INSERT INTO delegacias values (480, 'DM - Taquaritinga'); 
INSERT INTO delegacias values (481, '001 DP - Gua�ra'); 
INSERT INTO delegacias values (482, '001 DP - Batatais'); 
INSERT INTO delegacias values (483, 'DM - Miguel�polis'); 
INSERT INTO delegacias values (484, 'DM - Ribeir�o Corrente'); 
INSERT INTO delegacias values (485, 'DM - Morro Agudo'); 
INSERT INTO delegacias values (486, 'DM - Arealva'); 
INSERT INTO delegacias values (487, 'DM - Borac�ia'); 
INSERT INTO delegacias values (488, 'DM - Oleo'); 
INSERT INTO delegacias values (489, '002 DP - Ourinhos'); 
INSERT INTO delegacias values (490, 'DM - Tabapu�'); 
INSERT INTO delegacias values (491, 'DM - Nova Granada'); 
INSERT INTO delegacias values (492, 'DM - Mongagu�'); 
INSERT INTO delegacias values (493, 'DM - Pariquera-A��'); 
INSERT INTO delegacias values (494, 'DM - Fartura'); 
INSERT INTO delegacias values (495, 'DM - Anhembi'); 
INSERT INTO delegacias values (496, 'DM - Arei�polis'); 
INSERT INTO delegacias values (497, '001 DP - Cap�o Bonito'); 
INSERT INTO delegacias values (498, 'DM - Alum�nio'); 
INSERT INTO delegacias values (499, '001 DP - It�'); 
INSERT INTO delegacias values (500, '004 DP - It�'); 
INSERT INTO delegacias values (501, '004 DP - Assis'); 
INSERT INTO delegacias values (502, 'DM - C�ndido Mota'); 
INSERT INTO delegacias values (503, 'DM - Palmital'); 
INSERT INTO delegacias values (504, 'DM - Jo�o Ramalho'); 
INSERT INTO delegacias values (505, 'DM - Presidente Epit�cio'); 
INSERT INTO delegacias values (506, '001 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (507, '001 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (508, 'DM - Caconde'); 
INSERT INTO delegacias values (509, 'DM - Capivari'); 
INSERT INTO delegacias values (510, 'DM - Ipe�na'); 
INSERT INTO delegacias values (511, '001 DP - Rio Claro'); 
INSERT INTO delegacias values (512, '002 DP - Rio Claro'); 
INSERT INTO delegacias values (513, '001 DP - Cajamar'); 
INSERT INTO delegacias values (514, '003 DP - Osasco'); 
INSERT INTO delegacias values (515, '007 DP - Osasco'); 
INSERT INTO delegacias values (516, '081 DP - Bel�m'); 
INSERT INTO delegacias values (517, 'DM - Aparecida'); 
INSERT INTO delegacias values (518, '003 DP - Jacare�'); 
INSERT INTO delegacias values (519, 'DM - Avanhandava'); 
INSERT INTO delegacias values (520, 'DM - General Salgado'); 
INSERT INTO delegacias values (521, '003 DP - Mogi Mirim'); 
INSERT INTO delegacias values (522, 'DM - Altair'); 
INSERT INTO delegacias values (523, '002 DP - Barretos'); 
INSERT INTO delegacias values (524, 'DM - Ol�mpia'); 
INSERT INTO delegacias values (525, 'DM - Taiuva'); 
INSERT INTO delegacias values (526, 'DM - Cajuru'); 
INSERT INTO delegacias values (527, 'DM - Jardin�polis'); 
INSERT INTO delegacias values (528, '005 DP - Ribeir�o Preto'); 
INSERT INTO delegacias values (529, '001 DP - S�o Joaquim da Barra'); 
INSERT INTO delegacias values (530, '002 DP - Tup�'); 
INSERT INTO delegacias values (531, 'DM - Ariranha'); 
INSERT INTO delegacias values (532, '002 DP - Mongagu�'); 
INSERT INTO delegacias values (533, 'DM - Iguape'); 
INSERT INTO delegacias values (534, 'DM - Taquarituba'); 
INSERT INTO delegacias values (535, '003 DP - Itapetininga'); 
INSERT INTO delegacias values (536, 'DM - Buri'); 
INSERT INTO delegacias values (537, 'DM - Itaoca'); 
INSERT INTO delegacias values (538, 'DM - S�o Roque'); 
INSERT INTO delegacias values (539, 'DM - Alfredo Marcondes'); 
INSERT INTO delegacias values (540, 'DM - �lvares Machado'); 
INSERT INTO delegacias values (541, 'DM - Euclides da Cunha Pta.'); 
INSERT INTO delegacias values (542, 'DM - Cordeir�polis'); 
INSERT INTO delegacias values (543, '002 DP - Piracicaba'); 
INSERT INTO delegacias values (544, 'DM - Anal�ndia'); 
INSERT INTO delegacias values (545, '001 DP - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (546, '002 DP - Mau�'); 
INSERT INTO delegacias values (547, '096 DP - Mon��es'); 
INSERT INTO delegacias values (548, '058 DP - Vila Formosa'); 
INSERT INTO delegacias values (549, 'DM - Cachoeira Pta.'); 
INSERT INTO delegacias values (550, '001 DP - Guaratinguet�'); 
INSERT INTO delegacias values (551, '001 DP - Ara�atuba'); 
INSERT INTO delegacias values (552, '001 DP - Mogi-Gua�u'); 
INSERT INTO delegacias values (553, '002 DP - Araraquara'); 
INSERT INTO delegacias values (554, 'DM - Ibitinga'); 
INSERT INTO delegacias values (555, 'DM - Cajobi'); 
INSERT INTO delegacias values (556, 'DM - C. Coqueiros'); 
INSERT INTO delegacias values (557, '004 DP - Ribeir�o Preto'); 
INSERT INTO delegacias values (558, 'DM - Serrana'); 
INSERT INTO delegacias values (559, 'DM - Sta R. do Passa 4'); 
INSERT INTO delegacias values (560, 'DM - Balbinos'); 
INSERT INTO delegacias values (561, '001 DP - Ja�'); 
INSERT INTO delegacias values (562, 'DM - Vera Cruz'); 
INSERT INTO delegacias values (563, 'DM - Jaci'); 
INSERT INTO delegacias values (564, 'DM - Cardoso'); 
INSERT INTO delegacias values (565, '001 DP - Praia Grande'); 
INSERT INTO delegacias values (566, '002 DP - Santos'); 
INSERT INTO delegacias values (567, '002 DP - Avar�'); 
INSERT INTO delegacias values (568, 'DM - Cerqueira C�sar'); 
INSERT INTO delegacias values (569, '001 DP - Botucatu'); 
INSERT INTO delegacias values (570, '001 DP - S�o Manuel'); 
INSERT INTO delegacias values (571, '004 DP - Sorocaba'); 
INSERT INTO delegacias values (572, 'DM - Nova Guataporanga'); 
INSERT INTO delegacias values (573, '002 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (574, 'DM - Artur Nogueira'); 
INSERT INTO delegacias values (575, 'DM - Tamba�'); 
INSERT INTO delegacias values (576, '001 DP - Pirassununga'); 
INSERT INTO delegacias values (577, '004 DP - Piracicaba'); 
INSERT INTO delegacias values (578, '005 DP - Piracicaba'); 
INSERT INTO delegacias values (579, 'DM - S�o Sebasti�o da Gama'); 
INSERT INTO delegacias values (580, '005 DP - Osasco'); 
INSERT INTO delegacias values (581, '005 DP - Santo Andr�'); 
INSERT INTO delegacias values (582, '005 DP - S�o Bernardo do Campo'); 
INSERT INTO delegacias values (583, '016 DP - Vila Clementino'); 
INSERT INTO delegacias values (584, '042 DP - Parque S�o Lucas'); 
INSERT INTO delegacias values (585, 'DM - Mirand�polis'); 
INSERT INTO delegacias values (586, 'DM - Auriflama'); 
INSERT INTO delegacias values (587, '002 DP - Birigui'); 
INSERT INTO delegacias values (588, '002 DP - Mogi Mirim'); 
INSERT INTO delegacias values (589, 'DM - Guaraci'); 
INSERT INTO delegacias values (590, '001 DP - Ituverava'); 
INSERT INTO delegacias values (591, 'DM - Brodowski'); 
INSERT INTO delegacias values (592, 'DM - Ribeir�o Bonito'); 
INSERT INTO delegacias values (593, '001 DP - Ourinhos'); 
INSERT INTO delegacias values (594, '003 DP - Ourinhos'); 
INSERT INTO delegacias values (595, 'DM - Monte Apraz�vel'); 
INSERT INTO delegacias values (596, 'DM - Valentim Gentil'); 
INSERT INTO delegacias values (597, '003 DP - Botucatu'); 
INSERT INTO delegacias values (598, '001 DP - Tatu�'); 
INSERT INTO delegacias values (599, '010 DP - Sorocaba'); 
INSERT INTO delegacias values (600, 'DM - Taciba'); 
INSERT INTO delegacias values (601, 'DM - Itobi'); 
INSERT INTO delegacias values (602, '001 DP - S�o Jo�o da Boa Vista'); 
INSERT INTO delegacias values (603, '003 DP - S�o Jo�o da Boa Vista'); 
INSERT INTO delegacias values (604, 'DM - Caieiras'); 
INSERT INTO delegacias values (605, '001 DP - Mairipor�'); 
INSERT INTO delegacias values (606, '036 DP - Vila Mariana'); 
INSERT INTO delegacias values (607, '056 DP - Vila Alpina'); 
INSERT INTO delegacias values (608, 'DM - Buritama'); 
INSERT INTO delegacias values (609, 'DM - Santo Ant. Aracangua'); 
INSERT INTO delegacias values (610, '002 DP - Atibaia'); 
INSERT INTO delegacias values (611, '003 DP - Atibaia'); 
INSERT INTO delegacias values (612, 'DM - Piracaia'); 
INSERT INTO delegacias values (613, 'DM - Vargem'); 
INSERT INTO delegacias values (614, '001 DP - Cabreuva'); 
INSERT INTO delegacias values (615, '001 DP - V�rzea Pta.'); 
INSERT INTO delegacias values (616, 'DM - Jaguari�na'); 
INSERT INTO delegacias values (617, '001 DP - Barretos'); 
INSERT INTO delegacias values (618, 'DM - Jaborandi'); 
INSERT INTO delegacias values (619, 'DM - Sta. Rosa Viterbo'); 
INSERT INTO delegacias values (620, 'DM - Serra Azul'); 
INSERT INTO delegacias values (621, '001 DP - Porto Ferreira'); 
INSERT INTO delegacias values (622, 'DM - Pitangueiras'); 
INSERT INTO delegacias values (623, 'DM - Queiroz'); 
INSERT INTO delegacias values (624, 'DM - Novo Horizonte'); 
INSERT INTO delegacias values (625, 'DM - Mon��es'); 
INSERT INTO delegacias values (626, 'DM - Juqui�'); 
INSERT INTO delegacias values (627, '001 DP - Santos'); 
INSERT INTO delegacias values (628, 'DM - Conchas'); 
INSERT INTO delegacias values (629, 'DM - S�o Miguel Arcanjo'); 
INSERT INTO delegacias values (630, '001 DP - Itapeva'); 
INSERT INTO delegacias values (631, '007 DP - Sorocaba'); 
INSERT INTO delegacias values (632, 'DM - Paulic�ia'); 
INSERT INTO delegacias values (633, 'DM - Esp�rito Sto. do Pinhal'); 
INSERT INTO delegacias values (634, '007 DP - Lapa'); 
INSERT INTO delegacias values (635, '024 DP - Ponte Rasa'); 
INSERT INTO delegacias values (636, '001 DP - Cruzeiro'); 
INSERT INTO delegacias values (637, 'DM - Barbosa'); 
INSERT INTO delegacias values (638, 'DM - Clementina'); 
INSERT INTO delegacias values (639, '012 DP - Campinas'); 
INSERT INTO delegacias values (640, '013 DP - Campinas'); 
INSERT INTO delegacias values (641, 'DM - Nazar� Pta.'); 
INSERT INTO delegacias values (642, 'DM - Socorro'); 
INSERT INTO delegacias values (643, '003 DP - Franca'); 
INSERT INTO delegacias values (644, 'DM - Presidente Alves'); 
INSERT INTO delegacias values (645, 'DM - Bocaina'); 
INSERT INTO delegacias values (646, 'DM - Elisi�rio'); 
INSERT INTO delegacias values (647, 'DM - Palmeira do Oeste'); 
INSERT INTO delegacias values (648, '001 DP - Itanhaem'); 
INSERT INTO delegacias values (649, '003 DP - Itanhaem'); 
INSERT INTO delegacias values (650, '001 DP - Mongagu�'); 
INSERT INTO delegacias values (651, 'DM - Sete Barras'); 
INSERT INTO delegacias values (652, '002 DP - Cubat�o'); 
INSERT INTO delegacias values (653, '003 DP - Pirassununga'); 
INSERT INTO delegacias values (654, '001 DP - Guarulhos'); 
INSERT INTO delegacias values (655, 'DM - Paraibuna'); 
INSERT INTO delegacias values (656, '004 DP - Araraquara'); 
INSERT INTO delegacias values (657, 'DM - Itirapu�'); 
INSERT INTO delegacias values (658, 'DM - S�o Sim�o'); 
INSERT INTO delegacias values (659, 'DM - Pirajui'); 
INSERT INTO delegacias values (660, '001 DP - Gar�a'); 
INSERT INTO delegacias values (661, 'DM - Gar�a'); 
INSERT INTO delegacias values (662, 'DM - S. Pedro do Turvo'); 
INSERT INTO delegacias values (663, 'DM - Paranapu�'); 
INSERT INTO delegacias values (664, 'DM - Guapia��'); 
INSERT INTO delegacias values (665, 'DM - Potirendaba'); 
INSERT INTO delegacias values (666, 'DM - Peru�be'); 
INSERT INTO delegacias values (667, 'DM - Paranapanema'); 
INSERT INTO delegacias values (668, 'DM - Tapira�'); 
INSERT INTO delegacias values (669, 'DM - Luc�lia'); 
INSERT INTO delegacias values (670, 'DM - Ouro Verde'); 
INSERT INTO delegacias values (671, 'DM - Panorama'); 
INSERT INTO delegacias values (672, 'DM - Ilhabela'); 
INSERT INTO delegacias values (673, '001 DP - Valinhos'); 
INSERT INTO delegacias values (674, 'DM - Itatiba'); 
INSERT INTO delegacias values (675, '001 DP - Jundiai'); 
INSERT INTO delegacias values (676, 'DM - Boa Esperan�a Sul'); 
INSERT INTO delegacias values (677, 'DM - Terra Roxa'); 
INSERT INTO delegacias values (678, 'DM - Igarapava'); 
INSERT INTO delegacias values (679, 'DM - Patroc�nio Pta.'); 
INSERT INTO delegacias values (680, 'DM - Restinga'); 
INSERT INTO delegacias values (681, 'DM - Ipu�'); 
INSERT INTO delegacias values (682, 'DM - Piratininga'); 
INSERT INTO delegacias values (683, '002 DP - Ja�'); 
INSERT INTO delegacias values (684, '004 DP - Ja�'); 
INSERT INTO delegacias values (685, 'DM - Chavantes'); 
INSERT INTO delegacias values (686, 'DM - Quat�'); 
INSERT INTO delegacias values (687, 'DM - Ur�nia'); 
INSERT INTO delegacias values (688, 'DM - Eldorado'); 
INSERT INTO delegacias values (689, 'DM - Itaporanga'); 
INSERT INTO delegacias values (690, '001 DP - Piraj�'); 
INSERT INTO delegacias values (691, 'DM - Laranjal Pta.'); 
INSERT INTO delegacias values (692, 'DM - Cerquilho'); 
INSERT INTO delegacias values (693, 'DM - B. Sucesso / Itarar�'); 
INSERT INTO delegacias values (694, 'DM - Itapirapu� Pta.'); 
INSERT INTO delegacias values (695, '001 DP - Rosana'); 
INSERT INTO delegacias values (696, 'DM - Sto. Anast�cio'); 
INSERT INTO delegacias values (697, 'DM - Sta. Maria da Serra'); 
