INSERT INTO municipios values (1, 'S.PAULO'); 
INSERT INTO municipios values (2, 'CRUZEIRO'); 
INSERT INTO municipios values (3, 'CUNHA'); 
INSERT INTO municipios values (4, 'LORENA'); 
INSERT INTO municipios values (5, 'PIQUETE'); 
INSERT INTO municipios values (6, 'JACAREI'); 
INSERT INTO municipios values (7, 'CACAPAVA'); 
INSERT INTO municipios values (8, 'S.JOSE DOS CAMPOS'); 
INSERT INTO municipios values (9, 'CARAGUATATUBA'); 
INSERT INTO municipios values (10, 'UBATUBA'); 
INSERT INTO municipios values (11, 'CAMPOS DO JORDAO'); 
INSERT INTO municipios values (12, 'NATIVIDADE DA SERRA'); 
INSERT INTO municipios values (13, 'PINDAMONHANGABA'); 
INSERT INTO municipios values (14, 'TAUBATE'); 
INSERT INTO municipios values (15, 'TREMEMBE'); 
INSERT INTO municipios values (16, 'ARACATUBA'); 
INSERT INTO municipios values (17, 'GUARARAPES'); 
INSERT INTO municipios values (18, 'LUIZIANIA'); 
INSERT INTO municipios values (19, 'CAMPINAS'); 
INSERT INTO municipios values (20, 'VINHEDO'); 
INSERT INTO municipios values (21, 'AGUAS DE LINDOIA'); 
INSERT INTO municipios values (22, 'ATIBAIA'); 
INSERT INTO municipios values (23, 'JUNDIAI'); 
INSERT INTO municipios values (24, 'ITAPIRA'); 
INSERT INTO municipios values (25, 'MOGI-GUACU'); 
INSERT INTO municipios values (26, 'S.ANTONIO DE POSSE'); 
INSERT INTO municipios values (27, 'ARARAQUARA'); 
INSERT INTO municipios values (28, 'MATAO'); 
INSERT INTO municipios values (29, 'BARRETOS'); 
INSERT INTO municipios values (30, 'COLOMBIA'); 
INSERT INTO municipios values (31, 'BEBEDOURO'); 
INSERT INTO municipios values (32, 'MONTE AZUL PAULISTA'); 
INSERT INTO municipios values (33, 'FRANCA'); 
INSERT INTO municipios values (34, 'GUARA'); 
INSERT INTO municipios values (35, 'ALTINOPOLIS'); 
INSERT INTO municipios values (36, 'CRAVINHOS'); 
INSERT INTO municipios values (37, 'RIBEIRAO PRETO'); 
INSERT INTO municipios values (38, 'S.CARLOS'); 
INSERT INTO municipios values (39, 'IBATE'); 
INSERT INTO municipios values (40, 'PORTO FERREIRA'); 
INSERT INTO municipios values (41, 'PONTAL'); 
INSERT INTO municipios values (42, 'PRADOPOLIS'); 
INSERT INTO municipios values (43, 'SERTAOZINHO'); 
INSERT INTO municipios values (44, 'BAURU'); 
INSERT INTO municipios values (45, 'LENCOIS PAULISTA'); 
INSERT INTO municipios values (46, 'MARILIA'); 
INSERT INTO municipios values (47, 'CATANDUVA'); 
INSERT INTO municipios values (48, 'ADOLFO'); 
INSERT INTO municipios values (49, 'BALSAMO'); 
INSERT INTO municipios values (50, 'MIRASSOL'); 
INSERT INTO municipios values (51, 'S.JOSE DO RIO PRETO'); 
INSERT INTO municipios values (52, 'TANABI'); 
INSERT INTO municipios values (53, 'VOTUPORANGA'); 
INSERT INTO municipios values (54, 'ITARIRI'); 
INSERT INTO municipios values (55, 'CAJATI'); 
INSERT INTO municipios values (56, 'IGUAPE'); 
INSERT INTO municipios values (57, 'MIRACATU'); 
INSERT INTO municipios values (58, 'GUARUJA'); 
INSERT INTO municipios values (59, 'PRAIA GRANDE'); 
INSERT INTO municipios values (60, 'SANTOS'); 
INSERT INTO municipios values (61, 'S.VICENTE'); 
INSERT INTO municipios values (62, 'ITAI'); 
INSERT INTO municipios values (63, 'PIRAJU'); 
INSERT INTO municipios values (64, 'BOITUVA'); 
INSERT INTO municipios values (65, 'APIAI'); 
INSERT INTO municipios values (66, 'ARACARIGUAMA'); 
INSERT INTO municipios values (67, 'ARACOIABA DA SERRA'); 
INSERT INTO municipios values (68, 'IPERO'); 
INSERT INTO municipios values (69, 'ITU'); 
INSERT INTO municipios values (70, 'SALTO DE PIRAPORA'); 
INSERT INTO municipios values (71, 'SOROCABA'); 
INSERT INTO municipios values (72, 'ASSIS'); 
INSERT INTO municipios values (73, 'TUPI PAULISTA'); 
INSERT INTO municipios values (74, 'PRESIDENTE PRUDENTE'); 
INSERT INTO municipios values (75, 'CAIUA'); 
INSERT INTO municipios values (76, 'PIQUEROBI'); 
INSERT INTO municipios values (77, 'AMERICANA'); 
INSERT INTO municipios values (78, 'COSMOPOLIS'); 
INSERT INTO municipios values (79, 'HORTOLANDIA'); 
INSERT INTO municipios values (80, 'SUMARE'); 
INSERT INTO municipios values (81, 'ARARAS'); 
INSERT INTO municipios values (82, 'LIMEIRA'); 
INSERT INTO municipios values (83, 'RIO CLARO'); 
INSERT INTO municipios values (84, 'S.GERTRUDES'); 
INSERT INTO municipios values (85, 'BARUERI'); 
INSERT INTO municipios values (86, 'CARAPICUIBA'); 
INSERT INTO municipios values (87, 'COTIA'); 
INSERT INTO municipios values (88, 'ITAPEVI'); 
INSERT INTO municipios values (89, 'DIADEMA'); 
INSERT INTO municipios values (90, 'FRANCISCO MORATO'); 
INSERT INTO municipios values (91, 'FRANCO DA ROCHA'); 
INSERT INTO municipios values (92, 'GUARULHOS'); 
INSERT INTO municipios values (93, 'S.ISABEL'); 
INSERT INTO municipios values (94, 'ITAQUAQUECETUBA'); 
INSERT INTO municipios values (95, 'MOGI DAS CRUZES'); 
INSERT INTO municipios values (96, 'SUZANO'); 
INSERT INTO municipios values (97, 'OSASCO'); 
INSERT INTO municipios values (98, 'MAUA'); 
INSERT INTO municipios values (99, 'RIBEIRAO PIRES'); 
INSERT INTO municipios values (100, 'S.ANDRE'); 
INSERT INTO municipios values (101, 'S.BERNARDO DO CAMPO'); 
INSERT INTO municipios values (102, 'S.CAETANO DO SUL'); 
INSERT INTO municipios values (103, 'EMBU DAS ARTES'); 
INSERT INTO municipios values (104, 'EMBU-GUACU'); 
INSERT INTO municipios values (105, 'ITAPECERICA DA SERRA'); 
INSERT INTO municipios values (106, 'TABOAO DA SERRA'); 
INSERT INTO municipios values (107, 'GUARATINGUETA'); 
INSERT INTO municipios values (108, 'IGARATA'); 
INSERT INTO municipios values (109, 'SUD MENNUCCI'); 
INSERT INTO municipios values (110, 'BIRIGUI'); 
INSERT INTO municipios values (111, 'BREJO ALEGRE'); 
INSERT INTO municipios values (112, 'PIACATU'); 
INSERT INTO municipios values (113, 'PAULINIA'); 
INSERT INTO municipios values (114, 'BRAGANCA PAULISTA'); 
INSERT INTO municipios values (115, 'CAMPO LIMPO PAULISTA'); 
INSERT INTO municipios values (116, 'ITUPEVA'); 
INSERT INTO municipios values (117, 'JARINU'); 
INSERT INTO municipios values (118, 'TABATINGA'); 
INSERT INTO municipios values (119, 'PIRANGI'); 
INSERT INTO municipios values (120, 'TAIACU'); 
INSERT INTO municipios values (121, 'JERIQUARA'); 
INSERT INTO municipios values (122, 'DESCALVADO'); 
INSERT INTO municipios values (123, 'MONTE ALTO'); 
INSERT INTO municipios values (124, 'PEDERNEIRAS'); 
INSERT INTO municipios values (125, 'IGARACU DO TIETE'); 
INSERT INTO municipios values (126, 'JAU'); 
INSERT INTO municipios values (127, 'LINS'); 
INSERT INTO municipios values (128, 'SABINO'); 
INSERT INTO municipios values (129, 'ESPIRITO S. DO TURVO'); 
INSERT INTO municipios values (130, 'BASTOS'); 
INSERT INTO municipios values (131, 'URUPES'); 
INSERT INTO municipios values (132, 'ZACARIAS'); 
INSERT INTO municipios values (133, 'ITANHAEM'); 
INSERT INTO municipios values (134, 'IPORANGA'); 
INSERT INTO municipios values (135, 'JACUPIRANGA'); 
INSERT INTO municipios values (136, 'BERTIOGA'); 
INSERT INTO municipios values (137, 'CUBATAO'); 
INSERT INTO municipios values (138, 'AVARE'); 
INSERT INTO municipios values (139, 'IARAS'); 
INSERT INTO municipios values (140, 'BOTUCATU'); 
INSERT INTO municipios values (141, 'ITATINGA'); 
INSERT INTO municipios values (142, 'ITAPETININGA'); 
INSERT INTO municipios values (143, 'TATUI'); 
INSERT INTO municipios values (144, 'IBIUNA'); 
INSERT INTO municipios values (145, 'PILAR DO SUL'); 
INSERT INTO municipios values (146, 'PORTO FELIZ'); 
INSERT INTO municipios values (147, 'SALTO'); 
INSERT INTO municipios values (148, 'VOTORANTIM'); 
INSERT INTO municipios values (149, 'OSVALDO CRUZ'); 
INSERT INTO municipios values (150, 'REGENTE FEIJO'); 
INSERT INTO municipios values (151, 'MIRANTE PARANAPANEMA'); 
INSERT INTO municipios values (152, 'MONTE MOR'); 
INSERT INTO municipios values (153, 'S.BARBARA D OESTE'); 
INSERT INTO municipios values (154, 'TORRINHA'); 
INSERT INTO municipios values (155, 'AGUAI'); 
INSERT INTO municipios values (156, 'S.JOAO DA BOA VISTA'); 
INSERT INTO municipios values (157, 'JANDIRA'); 
INSERT INTO municipios values (158, 'PIRAPORA DO BOM JESUS'); 
INSERT INTO municipios values (159, 'MAIRIPORA'); 
INSERT INTO municipios values (160, 'ARUJA'); 
INSERT INTO municipios values (161, 'FERRAZ DE VASCONCELOS'); 
INSERT INTO municipios values (162, 'POA'); 
INSERT INTO municipios values (163, 'CANAS'); 
INSERT INTO municipios values (164, 'POTIM'); 
INSERT INTO municipios values (165, 'ROSEIRA'); 
INSERT INTO municipios values (166, 'S.SEBASTIAO'); 
INSERT INTO municipios values (167, 'CASTILHO'); 
INSERT INTO municipios values (168, 'PENAPOLIS'); 
INSERT INTO municipios values (169, 'INDAIATUBA'); 
INSERT INTO municipios values (170, 'BOM JESUS DOS PERDOES'); 
INSERT INTO municipios values (171, 'ITATIBA'); 
INSERT INTO municipios values (172, 'AMERICO BRASILIENSE'); 
INSERT INTO municipios values (173, 'COLINA'); 
INSERT INTO municipios values (174, 'VIRADOURO'); 
INSERT INTO municipios values (175, 'PEDREGULHO'); 
INSERT INTO municipios values (176, 'BARRINHA'); 
INSERT INTO municipios values (177, 'JABOTICABAL'); 
INSERT INTO municipios values (178, 'BERNARDINO DE CAMPOS'); 
INSERT INTO municipios values (179, 'S.FE DO SUL'); 
INSERT INTO municipios values (180, 'BADY BASSITT'); 
INSERT INTO municipios values (181, 'NIPOA'); 
INSERT INTO municipios values (182, 'RIOLANDIA'); 
INSERT INTO municipios values (183, 'PERUIBE'); 
INSERT INTO municipios values (184, 'CAPELA DO ALTO'); 
INSERT INTO municipios values (185, 'SARAPUI'); 
INSERT INTO municipios values (186, 'ADAMANTINA'); 
INSERT INTO municipios values (187, 'PARAGUACU PAULISTA'); 
INSERT INTO municipios values (188, 'TEODORO SAMPAIO'); 
INSERT INTO municipios values (189, 'CASA BRANCA'); 
INSERT INTO municipios values (190, 'S.CRUZ DAS PALMEIRAS'); 
INSERT INTO municipios values (191, 'LEME'); 
INSERT INTO municipios values (192, 'PIRACICABA'); 
INSERT INTO municipios values (193, 'S.PEDRO'); 
INSERT INTO municipios values (194, 'SANTANA DE PARNAIBA'); 
INSERT INTO municipios values (195, 'VARGEM GRANDE PAULISTA'); 
INSERT INTO municipios values (196, 'JUQUITIBA'); 
INSERT INTO municipios values (197, 'ANDRADINA'); 
INSERT INTO municipios values (198, 'VALPARAISO'); 
INSERT INTO municipios values (199, 'LOUVEIRA'); 
INSERT INTO municipios values (200, 'ITAPOLIS'); 
INSERT INTO municipios values (201, 'BATATAIS'); 
INSERT INTO municipios values (202, 'ITUVERAVA'); 
INSERT INTO municipios values (203, 'GUARIBA'); 
INSERT INTO municipios values (204, 'AGUDOS'); 
INSERT INTO municipios values (205, 'DOIS CORREGOS'); 
INSERT INTO municipios values (206, 'PROMISSAO'); 
INSERT INTO municipios values (207, 'TUPA'); 
INSERT INTO municipios values (208, 'PINDORAMA'); 
INSERT INTO municipios values (209, 'OUROESTE'); 
INSERT INTO municipios values (210, 'JOSE BONIFACIO'); 
INSERT INTO municipios values (211, 'REGISTRO'); 
INSERT INTO municipios values (212, 'PRATANIA'); 
INSERT INTO municipios values (213, 'ANGATUBA'); 
INSERT INTO municipios values (214, 'GUAREI'); 
INSERT INTO municipios values (215, 'RIBEIRAO BRANCO'); 
INSERT INTO municipios values (216, 'MAIRINQUE'); 
INSERT INTO municipios values (217, 'PIEDADE'); 
INSERT INTO municipios values (218, 'TIETE'); 
INSERT INTO municipios values (219, 'IRAPURU'); 
INSERT INTO municipios values (220, 'CAMPOS NOVOS PAULISTA'); 
INSERT INTO municipios values (221, 'DRACENA'); 
INSERT INTO municipios values (222, 'ENGENHEIRO COELHO'); 
INSERT INTO municipios values (223, 'NOVA ODESSA'); 
INSERT INTO municipios values (224, 'MOCOCA'); 
INSERT INTO municipios values (225, 'PIRASSUNUNGA'); 
INSERT INTO municipios values (226, 'ELIAS FAUSTO'); 
INSERT INTO municipios values (227, 'RIO DAS PEDRAS'); 
INSERT INTO municipios values (228, 'VARGEM GRANDE DO SUL'); 
INSERT INTO municipios values (229, 'CAIEIRAS'); 
INSERT INTO municipios values (230, 'CAJAMAR'); 
INSERT INTO municipios values (231, 'RIO GRANDE DA SERRA'); 
INSERT INTO municipios values (232, 'S.LOURENCO DA SERRA'); 
INSERT INTO municipios values (233, 'S.JOSE DO BARREIRO'); 
INSERT INTO municipios values (234, 'COROADOS'); 
INSERT INTO municipios values (235, 'AMPARO'); 
INSERT INTO municipios values (236, 'VARZEA PAULISTA'); 
INSERT INTO municipios values (237, 'TAQUARITINGA'); 
INSERT INTO municipios values (238, 'GUAIRA'); 
INSERT INTO municipios values (239, 'MIGUELOPOLIS'); 
INSERT INTO municipios values (240, 'RIBEIRAO CORRENTE'); 
INSERT INTO municipios values (241, 'MORRO AGUDO'); 
INSERT INTO municipios values (242, 'AREALVA'); 
INSERT INTO municipios values (243, 'BORACEIA'); 
INSERT INTO municipios values (244, 'OLEO'); 
INSERT INTO municipios values (245, 'OURINHOS'); 
INSERT INTO municipios values (246, 'TABAPUA'); 
INSERT INTO municipios values (247, 'NOVA GRANADA'); 
INSERT INTO municipios values (248, 'MONGAGUA'); 
INSERT INTO municipios values (249, 'PARIQUERA ACU'); 
INSERT INTO municipios values (250, 'FARTURA'); 
INSERT INTO municipios values (251, 'ANHEMBI'); 
INSERT INTO municipios values (252, 'AREIÓPOLIS'); 
INSERT INTO municipios values (253, 'CAPAO BONITO'); 
INSERT INTO municipios values (254, 'ALUMINIO'); 
INSERT INTO municipios values (255, 'CANDIDO MOTA'); 
INSERT INTO municipios values (256, 'PALMITAL'); 
INSERT INTO municipios values (257, 'JOAO RAMALHO'); 
INSERT INTO municipios values (258, 'PRESIDENTE EPITACIO'); 
INSERT INTO municipios values (259, 'PRESIDENTE VENCESLAU'); 
INSERT INTO municipios values (260, 'CACONDE'); 
INSERT INTO municipios values (261, 'CAPIVARI'); 
INSERT INTO municipios values (262, 'IPEUNA'); 
INSERT INTO municipios values (263, 'APARECIDA'); 
INSERT INTO municipios values (264, 'AVANHANDAVA'); 
INSERT INTO municipios values (265, 'GENERAL SALGADO'); 
INSERT INTO municipios values (266, 'MOGI MIRIM'); 
INSERT INTO municipios values (267, 'ALTAIR'); 
INSERT INTO municipios values (268, 'OLIMPIA'); 
INSERT INTO municipios values (269, 'TAIUVA'); 
INSERT INTO municipios values (270, 'RIFAINA'); 
INSERT INTO municipios values (271, 'CAJURU'); 
INSERT INTO municipios values (272, 'JARDINOPOLIS'); 
INSERT INTO municipios values (273, 'S.JOAQUIM DA BARRA'); 
INSERT INTO municipios values (274, 'ARIRANHA'); 
INSERT INTO municipios values (275, 'TAQUARITUBA'); 
INSERT INTO municipios values (276, 'BURI'); 
INSERT INTO municipios values (277, 'ITAOCA'); 
INSERT INTO municipios values (278, 'S.ROQUE'); 
INSERT INTO municipios values (279, 'ALFREDO MARCONDES'); 
INSERT INTO municipios values (280, 'ALVARES MACHADO'); 
INSERT INTO municipios values (281, 'EUCLIDES DA CUNHA PTA'); 
INSERT INTO municipios values (282, 'CORDEIROPOLIS'); 
INSERT INTO municipios values (283, 'ANALANDIA'); 
INSERT INTO municipios values (284, 'CACHOEIRA PAULISTA'); 
INSERT INTO municipios values (285, 'IBITINGA'); 
INSERT INTO municipios values (286, 'CAJOBI'); 
INSERT INTO municipios values (287, 'CASSIA DOS COQUEIROS'); 
INSERT INTO municipios values (288, 'SERRANA'); 
INSERT INTO municipios values (289, 'S.RITA PASSA QUATRO'); 
INSERT INTO municipios values (290, 'BALBINOS'); 
INSERT INTO municipios values (291, 'VERA CRUZ'); 
INSERT INTO municipios values (292, 'JACI'); 
INSERT INTO municipios values (293, 'CARDOSO'); 
INSERT INTO municipios values (294, 'CERQUEIRA CESAR'); 
INSERT INTO municipios values (295, 'S.MANUEL'); 
INSERT INTO municipios values (296, 'NOVA GUATAPORANGA'); 
INSERT INTO municipios values (297, 'ARTUR NOGUEIRA'); 
INSERT INTO municipios values (298, 'TAMBAU'); 
INSERT INTO municipios values (299, 'S.SEBASTIAO DA GRAMA'); 
INSERT INTO municipios values (300, 'MIRANDOPOLIS'); 
INSERT INTO municipios values (301, 'AURIFLAMA'); 
INSERT INTO municipios values (302, 'GUARACI'); 
INSERT INTO municipios values (303, 'BRODOWSKI'); 
INSERT INTO municipios values (304, 'RIBEIRAO BONITO'); 
INSERT INTO municipios values (305, 'MONTE APRAZIVEL'); 
INSERT INTO municipios values (306, 'VALENTIM GENTIL'); 
INSERT INTO municipios values (307, 'TACIBA'); 
INSERT INTO municipios values (308, 'ITOBI'); 
INSERT INTO municipios values (309, 'PEREIRA BARRETO'); 
INSERT INTO municipios values (310, 'BURITAMA'); 
INSERT INTO municipios values (311, 'S.ANTONIO DE ARACANGUA'); 
INSERT INTO municipios values (312, 'PIRACAIA'); 
INSERT INTO municipios values (313, 'VARGEM'); 
INSERT INTO municipios values (314, 'CABREUVA'); 
INSERT INTO municipios values (315, 'JAGUARIUNA'); 
INSERT INTO municipios values (316, 'JABORANDI'); 
INSERT INTO municipios values (317, 'S.ROSA DE VITERBO'); 
INSERT INTO municipios values (318, 'SERRA AZUL'); 
INSERT INTO municipios values (319, 'PITANGUEIRAS'); 
INSERT INTO municipios values (320, 'QUEIROZ'); 
INSERT INTO municipios values (321, 'NOVO HORIZONTE'); 
INSERT INTO municipios values (322, 'JUQUIA'); 
INSERT INTO municipios values (323, 'CONCHAS'); 
INSERT INTO municipios values (324, 'S.MIGUEL ARCANJO'); 
INSERT INTO municipios values (325, 'ITAPEVA'); 
INSERT INTO municipios values (326, 'PAULICEIA'); 
INSERT INTO municipios values (327, 'ESPIRITO STO. PINHAL'); 
INSERT INTO municipios values (328, 'BARBOSA'); 
INSERT INTO municipios values (329, 'CLEMENTINA'); 
INSERT INTO municipios values (330, 'NAZARE PAULISTA'); 
INSERT INTO municipios values (331, 'SOCORRO'); 
INSERT INTO municipios values (332, 'PRESIDENTE ALVES'); 
INSERT INTO municipios values (333, 'BOCAINA'); 
INSERT INTO municipios values (334, 'ELISIARIO'); 
INSERT INTO municipios values (335, 'PALMEIRA D OESTE'); 
INSERT INTO municipios values (336, 'SETE BARRAS'); 
INSERT INTO municipios values (337, 'PARAIBUNA'); 
INSERT INTO municipios values (338, 'ITIRAPUA'); 
INSERT INTO municipios values (339, 'S.SIMAO'); 
INSERT INTO municipios values (340, 'PIRAJUI'); 
INSERT INTO municipios values (341, 'GARCA'); 
INSERT INTO municipios values (342, 'S.PEDRO DO TURVO'); 
INSERT INTO municipios values (343, 'PARANAPUA'); 
INSERT INTO municipios values (344, 'GUAPIACU'); 
INSERT INTO municipios values (345, 'POTIRENDABA'); 
INSERT INTO municipios values (346, 'PARANAPANEMA'); 
INSERT INTO municipios values (347, 'TAPIRAI'); 
INSERT INTO municipios values (348, 'LUCELIA'); 
INSERT INTO municipios values (349, 'OURO VERDE'); 
INSERT INTO municipios values (350, 'PANORAMA'); 
INSERT INTO municipios values (351, 'ILHABELA'); 
INSERT INTO municipios values (352, 'VALINHOS'); 
INSERT INTO municipios values (353, 'BOA ESPERANCA DO SUL'); 
INSERT INTO municipios values (354, 'TERRA ROXA'); 
INSERT INTO municipios values (355, 'IGARAPAVA'); 
INSERT INTO municipios values (356, 'PATROCINIO PAULISTA'); 
INSERT INTO municipios values (357, 'RESTINGA'); 
INSERT INTO municipios values (358, 'IPUA'); 
INSERT INTO municipios values (359, 'PIRATININGA'); 
INSERT INTO municipios values (360, 'CHAVANTES'); 
INSERT INTO municipios values (361, 'QUATA'); 
INSERT INTO municipios values (362, 'URANIA'); 
INSERT INTO municipios values (363, 'ELDORADO'); 
INSERT INTO municipios values (364, 'ITAPORANGA'); 
INSERT INTO municipios values (365, 'LARANJAL PAULISTA'); 
INSERT INTO municipios values (366, 'CERQUILHO'); 
INSERT INTO municipios values (367, 'BOM SUCESSO DE ITARARE'); 
INSERT INTO municipios values (368, 'ITAPIRAPUA PAULISTA'); 
INSERT INTO municipios values (369, 'ROSANA'); 
INSERT INTO municipios values (370, 'S.ANASTACIO'); 
INSERT INTO municipios values (371, 'SANTA MARIA DA SERRA'); 
