INSERT INTO tipo_local values (26, 'Via pública'); 
INSERT INTO tipo_local values (27, 'Residência'); 
INSERT INTO tipo_local values (28, 'Comércio e serviços'); 
INSERT INTO tipo_local values (29, 'Saúde'); 
INSERT INTO tipo_local values (30, 'Area não ocupada'); 
INSERT INTO tipo_local values (31, 'Condominio Comercial'); 
INSERT INTO tipo_local values (32, 'Restaurante e afins'); 
INSERT INTO tipo_local values (33, 'Lazer e recreação'); 
INSERT INTO tipo_local values (34, 'Unidade rural'); 
INSERT INTO tipo_local values (35, 'Local clandestino/ilegal'); 
INSERT INTO tipo_local values (36, 'Terminal/Estação'); 
INSERT INTO tipo_local values (37, 'Rodovia/Estrada'); 
INSERT INTO tipo_local values (38, 'Condominio Residencial'); 
INSERT INTO tipo_local values (39, 'Favela'); 
INSERT INTO tipo_local values (40, 'Hospedagem'); 
INSERT INTO tipo_local values (41, 'Repartição Pública'); 
INSERT INTO tipo_local values (42, 'Serviços e bens públicos'); 
INSERT INTO tipo_local values (43, 'Centro Comerc./Empresarial'); 
INSERT INTO tipo_local values (44, 'Estabelecimento prisional'); 
INSERT INTO tipo_local values (45, 'Estrada de ferro'); 
INSERT INTO tipo_local values (46, 'Estabelecimento de ensino'); 
INSERT INTO tipo_local values (47, 'Escritório'); 
INSERT INTO tipo_local values (48, 'Estabelecimento industrial'); 
INSERT INTO tipo_local values (49, 'Entidade assistencial'); 
INSERT INTO tipo_local values (50, 'Templo e afins'); 
