INSERT INTO municipios values (1, 'S.PAULO'); 
INSERT INTO municipios values (2, 'CRUZEIRO'); 
INSERT INTO municipios values (3, 'APARECIDA'); 
INSERT INTO municipios values (4, 'CANAS'); 
INSERT INTO municipios values (5, 'GUARATINGUETA'); 
INSERT INTO municipios values (6, 'LORENA'); 
INSERT INTO municipios values (7, 'POTIM'); 
INSERT INTO municipios values (8, 'JACAREI'); 
INSERT INTO municipios values (9, 'S.JOSE DOS CAMPOS'); 
INSERT INTO municipios values (10, 'CARAGUATATUBA'); 
INSERT INTO municipios values (11, 'S.SEBASTIAO'); 
INSERT INTO municipios values (12, 'UBATUBA'); 
INSERT INTO municipios values (13, 'CAMPOS DO JORDAO'); 
INSERT INTO municipios values (14, 'PINDAMONHANGABA'); 
INSERT INTO municipios values (15, 'TAUBATE'); 
INSERT INTO municipios values (16, 'PEREIRA BARRETO'); 
INSERT INTO municipios values (17, 'SUZANAPOLIS'); 
INSERT INTO municipios values (18, 'ARACATUBA'); 
INSERT INTO municipios values (19, 'LOURDES'); 
INSERT INTO municipios values (20, 'CAMPINAS'); 
INSERT INTO municipios values (21, 'INDAIATUBA'); 
INSERT INTO municipios values (22, 'ATIBAIA'); 
INSERT INTO municipios values (23, 'BRAGANCA PAULISTA'); 
INSERT INTO municipios values (24, 'JOANOPOLIS'); 
INSERT INTO municipios values (25, 'CAMPO LIMPO PAULISTA'); 
INSERT INTO municipios values (26, 'JUNDIAI'); 
INSERT INTO municipios values (27, 'VARZEA PAULISTA'); 
INSERT INTO municipios values (28, 'ITAPIRA'); 
INSERT INTO municipios values (29, 'MOGI-GUACU'); 
INSERT INTO municipios values (30, 'ARARAQUARA'); 
INSERT INTO municipios values (31, 'IBITINGA'); 
INSERT INTO municipios values (32, 'ITAPOLIS'); 
INSERT INTO municipios values (33, 'OLIMPIA'); 
INSERT INTO municipios values (34, 'TAIACU'); 
INSERT INTO municipios values (35, 'CRISTAIS PAULISTA'); 
INSERT INTO municipios values (36, 'RIBEIRAO PRETO'); 
INSERT INTO municipios values (37, 'PORTO FERREIRA'); 
INSERT INTO municipios values (38, 'S.CARLOS'); 
INSERT INTO municipios values (39, 'GUARIBA'); 
INSERT INTO municipios values (40, 'SERTAOZINHO'); 
INSERT INTO municipios values (41, 'AGUDOS'); 
INSERT INTO municipios values (42, 'LINS'); 
INSERT INTO municipios values (43, 'LUPERCIO'); 
INSERT INTO municipios values (44, 'MARILIA'); 
INSERT INTO municipios values (45, 'MIRA ESTRELA'); 
INSERT INTO municipios values (46, 'SANTA ALBERTINA'); 
INSERT INTO municipios values (47, 'URANIA'); 
INSERT INTO municipios values (48, 'ICEM'); 
INSERT INTO municipios values (49, 'S.JOSE DO RIO PRETO'); 
INSERT INTO municipios values (50, 'TANABI'); 
INSERT INTO municipios values (51, 'ITANHAEM'); 
INSERT INTO municipios values (52, 'MONGAGUA'); 
INSERT INTO municipios values (53, 'BARRA DO TURVO'); 
INSERT INTO municipios values (54, 'IGUAPE'); 
INSERT INTO municipios values (55, 'CUBATAO'); 
INSERT INTO municipios values (56, 'GUARUJA'); 
INSERT INTO municipios values (57, 'PRAIA GRANDE'); 
INSERT INTO municipios values (58, 'SANTOS'); 
INSERT INTO municipios values (59, 'S.VICENTE'); 
INSERT INTO municipios values (60, 'IARAS'); 
INSERT INTO municipios values (61, 'PORANGABA'); 
INSERT INTO municipios values (62, 'ITAPETININGA'); 
INSERT INTO municipios values (63, 'TATUI'); 
INSERT INTO municipios values (64, 'CAPAO BONITO'); 
INSERT INTO municipios values (65, 'ITU'); 
INSERT INTO municipios values (66, 'S.ROQUE'); 
INSERT INTO municipios values (67, 'SOROCABA'); 
INSERT INTO municipios values (68, 'VOTORANTIM'); 
INSERT INTO municipios values (69, 'PARAGUACU PAULISTA'); 
INSERT INTO municipios values (70, 'PRESIDENTE PRUDENTE'); 
INSERT INTO municipios values (71, 'COSMOPOLIS'); 
INSERT INTO municipios values (72, 'ENGENHEIRO COELHO'); 
INSERT INTO municipios values (73, 'HORTOLANDIA'); 
INSERT INTO municipios values (74, 'MONTE MOR'); 
INSERT INTO municipios values (75, 'S.BARBARA D OESTE'); 
INSERT INTO municipios values (76, 'SUMARE'); 
INSERT INTO municipios values (77, 'LEME'); 
INSERT INTO municipios values (78, 'PIRASSUNUNGA'); 
INSERT INTO municipios values (79, 'PIRACICABA'); 
INSERT INTO municipios values (80, 'RIO CLARO'); 
INSERT INTO municipios values (81, 'ESPIRITO STO. PINHAL'); 
INSERT INTO municipios values (82, 'CARAPICUIBA'); 
INSERT INTO municipios values (83, 'COTIA'); 
INSERT INTO municipios values (84, 'ITAPEVI'); 
INSERT INTO municipios values (85, 'JANDIRA'); 
INSERT INTO municipios values (86, 'PIRAPORA DO BOM JESUS'); 
INSERT INTO municipios values (87, 'SANTANA DE PARNAIBA'); 
INSERT INTO municipios values (88, 'DIADEMA'); 
INSERT INTO municipios values (89, 'CAIEIRAS'); 
INSERT INTO municipios values (90, 'CAJAMAR'); 
INSERT INTO municipios values (91, 'FRANCISCO MORATO'); 
INSERT INTO municipios values (92, 'MAIRIPORA'); 
INSERT INTO municipios values (93, 'ARUJA'); 
INSERT INTO municipios values (94, 'GUARULHOS'); 
INSERT INTO municipios values (95, 'S.ISABEL'); 
INSERT INTO municipios values (96, 'FERRAZ DE VASCONCELOS'); 
INSERT INTO municipios values (97, 'ITAQUAQUECETUBA'); 
INSERT INTO municipios values (98, 'MOGI DAS CRUZES'); 
INSERT INTO municipios values (99, 'POA'); 
INSERT INTO municipios values (100, 'SUZANO'); 
INSERT INTO municipios values (101, 'OSASCO'); 
INSERT INTO municipios values (102, 'MAUA'); 
INSERT INTO municipios values (103, 'RIBEIRAO PIRES'); 
INSERT INTO municipios values (104, 'S.ANDRE'); 
INSERT INTO municipios values (105, 'S.BERNARDO DO CAMPO'); 
INSERT INTO municipios values (106, 'EMBU DAS ARTES'); 
INSERT INTO municipios values (107, 'EMBU-GUACU'); 
INSERT INTO municipios values (108, 'ITAPECERICA DA SERRA'); 
INSERT INTO municipios values (109, 'TABOAO DA SERRA'); 
INSERT INTO municipios values (110, 'CACAPAVA'); 
INSERT INTO municipios values (111, 'S.BENTO DO SAPUCAI'); 
INSERT INTO municipios values (112, 'TREMEMBE'); 
INSERT INTO municipios values (113, 'GUARARAPES'); 
INSERT INTO municipios values (114, 'PIRACAIA'); 
INSERT INTO municipios values (115, 'ITATIBA'); 
INSERT INTO municipios values (116, 'MOGI MIRIM'); 
INSERT INTO municipios values (117, 'MATAO'); 
INSERT INTO municipios values (118, 'RINCAO'); 
INSERT INTO municipios values (119, 'CAJOBI'); 
INSERT INTO municipios values (120, 'GUAIRA'); 
INSERT INTO municipios values (121, 'BATATAIS'); 
INSERT INTO municipios values (122, 'FRANCA'); 
INSERT INTO municipios values (123, 'RESTINGA'); 
INSERT INTO municipios values (124, 'CRAVINHOS'); 
INSERT INTO municipios values (125, 'MORRO AGUDO'); 
INSERT INTO municipios values (126, 'PITANGUEIRAS'); 
INSERT INTO municipios values (127, 'BAURU'); 
INSERT INTO municipios values (128, 'LENCOIS PAULISTA'); 
INSERT INTO municipios values (129, 'PEDERNEIRAS'); 
INSERT INTO municipios values (130, 'JAU'); 
INSERT INTO municipios values (131, 'GETULINA'); 
INSERT INTO municipios values (132, 'IPAUSSU'); 
INSERT INTO municipios values (133, 'OURINHOS'); 
INSERT INTO municipios values (134, 'S.CRUZ DO RIO PARDO'); 
INSERT INTO municipios values (135, 'CATANDUVA'); 
INSERT INTO municipios values (136, 'VALENTIM GENTIL'); 
INSERT INTO municipios values (137, 'VOTUPORANGA'); 
INSERT INTO municipios values (138, 'ITAPORANGA'); 
INSERT INTO municipios values (139, 'SARUTAIA'); 
INSERT INTO municipios values (140, 'BOTUCATU'); 
INSERT INTO municipios values (141, 'PARDINHO'); 
INSERT INTO municipios values (142, 'RIBEIRA'); 
INSERT INTO municipios values (143, 'IBIUNA'); 
INSERT INTO municipios values (144, 'MAIRINQUE'); 
INSERT INTO municipios values (145, 'SALTO'); 
INSERT INTO municipios values (146, 'JUNQUEIROPOLIS'); 
INSERT INTO municipios values (147, 'TUPI PAULISTA'); 
INSERT INTO municipios values (148, 'ROSANA'); 
INSERT INTO municipios values (149, 'S.ANASTACIO'); 
INSERT INTO municipios values (150, 'AMERICANA'); 
INSERT INTO municipios values (151, 'NOVA ODESSA'); 
INSERT INTO municipios values (152, 'CASA BRANCA'); 
INSERT INTO municipios values (153, 'TAPIRATIBA'); 
INSERT INTO municipios values (154, 'CORDEIROPOLIS'); 
INSERT INTO municipios values (155, 'LIMEIRA'); 
INSERT INTO municipios values (156, 'S.GERTRUDES'); 
INSERT INTO municipios values (157, 'VARGEM GRANDE PAULISTA'); 
INSERT INTO municipios values (158, 'QUELUZ'); 
INSERT INTO municipios values (159, 'LAVINIA'); 
INSERT INTO municipios values (160, 'BIRIGUI'); 
INSERT INTO municipios values (161, 'BEBEDOURO'); 
INSERT INTO municipios values (162, 'MIGUELOPOLIS'); 
INSERT INTO municipios values (163, 'PATROCINIO PAULISTA'); 
INSERT INTO municipios values (164, 'JARDINOPOLIS'); 
INSERT INTO municipios values (165, 'IBATE'); 
INSERT INTO municipios values (166, 'JABOTICABAL'); 
INSERT INTO municipios values (167, 'CABRALIA PAULISTA'); 
INSERT INTO municipios values (168, 'MACATUBA'); 
INSERT INTO municipios values (169, 'IGARACU DO TIETE'); 
INSERT INTO municipios values (170, 'GUAICARA'); 
INSERT INTO municipios values (171, 'GUAIMBE'); 
INSERT INTO municipios values (172, 'PARAPUA'); 
INSERT INTO municipios values (173, 'JOSE BONIFACIO'); 
INSERT INTO municipios values (174, 'SEBASTIANOPOLIS SUL'); 
INSERT INTO municipios values (175, 'PERUIBE'); 
INSERT INTO municipios values (176, 'SETE BARRAS'); 
INSERT INTO municipios values (177, 'BERTIOGA'); 
INSERT INTO municipios values (178, 'ITAI'); 
INSERT INTO municipios values (179, 'BOFETE'); 
INSERT INTO municipios values (180, 'ITATINGA'); 
INSERT INTO municipios values (181, 'BOITUVA'); 
INSERT INTO municipios values (182, 'BURI'); 
INSERT INTO municipios values (183, 'SALTO DE PIRAPORA'); 
INSERT INTO municipios values (184, 'ASSIS'); 
INSERT INTO municipios values (185, 'PIRAPOZINHO'); 
INSERT INTO municipios values (186, 'REGENTE FEIJO'); 
INSERT INTO municipios values (187, 'PRESIDENTE EPITACIO'); 
INSERT INTO municipios values (188, 'PRESIDENTE VENCESLAU'); 
INSERT INTO municipios values (189, 'ARTUR NOGUEIRA'); 
INSERT INTO municipios values (190, 'ITOBI'); 
INSERT INTO municipios values (191, 'CHARQUEADA'); 
INSERT INTO municipios values (192, 'S.SEBASTIAO DA GRAMA'); 
INSERT INTO municipios values (193, 'BARUERI'); 
INSERT INTO municipios values (194, 'FRANCO DA ROCHA'); 
INSERT INTO municipios values (195, 'S.LOURENCO DA SERRA'); 
INSERT INTO municipios values (196, 'MONTEIRO LOBATO'); 
INSERT INTO municipios values (197, 'ANDRADINA'); 
INSERT INTO municipios values (198, 'ILHA SOLTEIRA'); 
INSERT INTO municipios values (199, 'BURITAMA'); 
INSERT INTO municipios values (200, 'PENAPOLIS'); 
INSERT INTO municipios values (201, 'JAGUARIUNA'); 
INSERT INTO municipios values (202, 'TABATINGA'); 
INSERT INTO municipios values (203, 'VISTA ALEGRE DO ALTO'); 
INSERT INTO municipios values (204, 'GUARA'); 
INSERT INTO municipios values (205, 'MONTE ALTO'); 
INSERT INTO municipios values (206, 'IACANGA'); 
INSERT INTO municipios values (207, 'ITAJU'); 
INSERT INTO municipios values (208, 'PROMISSAO'); 
INSERT INTO municipios values (209, 'ALVINLANDIA'); 
INSERT INTO municipios values (210, 'PALMARES PAULISTA'); 
INSERT INTO municipios values (211, 'TABAPUA'); 
INSERT INTO municipios values (212, 'URUPES'); 
INSERT INTO municipios values (213, 'AMERICO DE CAMPOS'); 
INSERT INTO municipios values (214, 'MIRACATU'); 
INSERT INTO municipios values (215, 'AVARE'); 
INSERT INTO municipios values (216, 'PIRAJU'); 
INSERT INTO municipios values (217, 'ARACOIABA DA SERRA'); 
INSERT INTO municipios values (218, 'PORTO FELIZ'); 
INSERT INTO municipios values (219, 'TIETE'); 
INSERT INTO municipios values (220, 'ADAMANTINA'); 
INSERT INTO municipios values (221, 'FLÓRIDA PAULISTA'); 
INSERT INTO municipios values (222, 'TEODORO SAMPAIO'); 
INSERT INTO municipios values (223, 'S.CRUZ DAS PALMEIRAS'); 
INSERT INTO municipios values (224, 'S.PEDRO'); 
INSERT INTO municipios values (225, 'BIRITIBA-MIRIM'); 
INSERT INTO municipios values (226, 'ILHABELA'); 
INSERT INTO municipios values (227, 'PAULINIA'); 
INSERT INTO municipios values (228, 'VALINHOS'); 
INSERT INTO municipios values (229, 'AGUAS DE LINDOIA'); 
INSERT INTO municipios values (230, 'AMERICO BRASILIENSE'); 
INSERT INTO municipios values (231, 'ITUVERAVA'); 
INSERT INTO municipios values (232, 'ORLANDIA'); 
INSERT INTO municipios values (233, 'PONTAL'); 
INSERT INTO municipios values (234, 'BALBINOS'); 
INSERT INTO municipios values (235, 'SABINO'); 
INSERT INTO municipios values (236, 'OCAUCU'); 
INSERT INTO municipios values (237, 'JALES'); 
INSERT INTO municipios values (238, 'MIRASSOL'); 
INSERT INTO municipios values (239, 'CORONEL MACEDO'); 
INSERT INTO municipios values (240, 'FARTURA'); 
INSERT INTO municipios values (241, 'ANHEMBI'); 
INSERT INTO municipios values (242, 'ARACARIGUAMA'); 
INSERT INTO municipios values (243, 'PALMITAL'); 
INSERT INTO municipios values (244, 'ALVARES MACHADO'); 
INSERT INTO municipios values (245, 'ARARAS'); 
INSERT INTO municipios values (246, 'CONCHAL'); 
INSERT INTO municipios values (247, 'RIO GRANDE DA SERRA'); 
INSERT INTO municipios values (248, 'CACHOEIRA PAULISTA'); 
INSERT INTO municipios values (249, 'CASTILHO'); 
INSERT INTO municipios values (250, 'NAZARE PAULISTA'); 
INSERT INTO municipios values (251, 'SOCORRO'); 
INSERT INTO municipios values (252, 'JARINU'); 
INSERT INTO municipios values (253, 'S.ANTONIO DE POSSE'); 
INSERT INTO municipios values (254, 'COLINA'); 
INSERT INTO municipios values (255, 'PIRANGI'); 
INSERT INTO municipios values (256, 'S.SIMAO'); 
INSERT INTO municipios values (257, 'SERRANA'); 
INSERT INTO municipios values (258, 'S.RITA PASSA QUATRO'); 
INSERT INTO municipios values (259, 'PINDORAMA'); 
INSERT INTO municipios values (260, 'MONTE APRAZIVEL'); 
INSERT INTO municipios values (261, 'ITARIRI'); 
INSERT INTO municipios values (262, 'CESARIO LANGE'); 
INSERT INTO municipios values (263, 'S.MIGUEL ARCANJO'); 
INSERT INTO municipios values (264, 'APIAI'); 
INSERT INTO municipios values (265, 'ITARARE'); 
INSERT INTO municipios values (266, 'TARUMA'); 
INSERT INTO municipios values (267, 'PANORAMA'); 
INSERT INTO municipios values (268, 'BROTAS'); 
INSERT INTO municipios values (269, 'CORUMBATAI'); 
INSERT INTO municipios values (270, 'AGUAI'); 
INSERT INTO municipios values (271, 'JUQUITIBA'); 
INSERT INTO municipios values (272, 'PARAIBUNA'); 
INSERT INTO municipios values (273, 'S.BRANCA'); 
INSERT INTO municipios values (274, 'AMPARO'); 
INSERT INTO municipios values (275, 'LOUVEIRA'); 
INSERT INTO municipios values (276, 'MORUNGABA'); 
INSERT INTO municipios values (277, 'DOBRADA'); 
INSERT INTO municipios values (278, 'GAVIAO PEIXOTO'); 
INSERT INTO municipios values (279, 'BARRA BONITA'); 
INSERT INTO municipios values (280, 'DOIS CORREGOS'); 
INSERT INTO municipios values (281, 'CANITAR'); 
INSERT INTO municipios values (282, 'POPULINA'); 
INSERT INTO municipios values (283, 'PAULO DE FARIA'); 
INSERT INTO municipios values (284, 'REGISTRO'); 
INSERT INTO municipios values (285, 'CAMPINA MONTE ALEGRE'); 
INSERT INTO municipios values (286, 'PIEDADE'); 
INSERT INTO municipios values (287, 'S.ANTONIO DE ARACANGUA'); 
INSERT INTO municipios values (288, 'CABREUVA'); 
INSERT INTO municipios values (289, 'BORBOREMA'); 
INSERT INTO municipios values (290, 'S.LUCIA'); 
INSERT INTO municipios values (291, 'BARRETOS'); 
INSERT INTO municipios values (292, 'BURITIZAL'); 
INSERT INTO municipios values (293, 'GARCA'); 
INSERT INTO municipios values (294, 'TUPA'); 
INSERT INTO municipios values (295, 'BADY BASSITT'); 
INSERT INTO municipios values (296, 'UNIAO PAULISTA'); 
INSERT INTO municipios values (297, 'JUQUIA'); 
INSERT INTO municipios values (298, 'IPERO'); 
INSERT INTO municipios values (299, 'IBIRAREMA'); 
INSERT INTO municipios values (300, 'VARGEM GRANDE DO SUL'); 
INSERT INTO municipios values (301, 'ROSEIRA'); 
INSERT INTO municipios values (302, 'IGARATA'); 
INSERT INTO municipios values (303, 'NATIVIDADE DA SERRA'); 
INSERT INTO municipios values (304, 'AVANHANDAVA'); 
INSERT INTO municipios values (305, 'PRADOPOLIS'); 
INSERT INTO municipios values (306, 'AREALVA'); 
INSERT INTO municipios values (307, 'REGINOPOLIS'); 
INSERT INTO municipios values (308, 'ESTRELA D OESTE'); 
INSERT INTO municipios values (309, 'S.JOAO DUAS PONTES'); 
INSERT INTO municipios values (310, 'NOVO HORIZONTE'); 
INSERT INTO municipios values (311, 'ITABERA'); 
INSERT INTO municipios values (312, 'NOVA CAMPINA'); 
INSERT INTO municipios values (313, 'CAPIVARI'); 
INSERT INTO municipios values (314, 'ITIRAPINA'); 
INSERT INTO municipios values (315, 'GUARAREMA'); 
INSERT INTO municipios values (316, 'AURIFLAMA'); 
INSERT INTO municipios values (317, 'LINDOIA'); 
INSERT INTO municipios values (318, 'ITUPEVA'); 
INSERT INTO municipios values (319, 'CAFELANDIA'); 
INSERT INTO municipios values (320, 'ECHAPORA'); 
INSERT INTO municipios values (321, 'S.FE DO SUL'); 
INSERT INTO municipios values (322, 'ONDA VERDE'); 
INSERT INTO municipios values (323, 'POTIRENDABA'); 
INSERT INTO municipios values (324, 'GUAREI'); 
INSERT INTO municipios values (325, 'S.JOAO DA BOA VISTA'); 
INSERT INTO municipios values (326, 'CUNHA'); 
INSERT INTO municipios values (327, 'ITAPURA'); 
INSERT INTO municipios values (328, 'VARGEM'); 
INSERT INTO municipios values (329, 'ALTAIR'); 
INSERT INTO municipios values (330, 'S.ROSA DE VITERBO'); 
INSERT INTO municipios values (331, 'S.JOAQUIM DA BARRA'); 
INSERT INTO municipios values (332, 'BOCAINA'); 
INSERT INTO municipios values (333, 'TAQUARITUBA'); 
INSERT INTO municipios values (334, 'S.MERCEDES'); 
INSERT INTO municipios values (335, 'SALESOPOLIS'); 
INSERT INTO municipios values (336, 'COLOMBIA'); 
INSERT INTO municipios values (337, 'SEVERINIA'); 
INSERT INTO municipios values (338, 'IGARAPAVA'); 
INSERT INTO municipios values (339, 'BARRINHA'); 
INSERT INTO municipios values (340, 'VERA CRUZ'); 
INSERT INTO municipios values (341, 'RIBEIRAO DO SUL'); 
INSERT INTO municipios values (342, 'OUROESTE'); 
INSERT INTO municipios values (343, 'SALES'); 
INSERT INTO municipios values (344, 'PONTES GESTAL'); 
INSERT INTO municipios values (345, 'CANANEIA'); 
INSERT INTO municipios values (346, 'AREIÓPOLIS'); 
INSERT INTO municipios values (347, 'ITAPEVA'); 
INSERT INTO municipios values (348, 'RIBEIRAO GRANDE'); 
INSERT INTO municipios values (349, 'MIRANTE PARANAPANEMA'); 
INSERT INTO municipios values (350, 'IRACEMAPOLIS'); 
