INSERT INTO circunscricoes values (334, 'Santa Mercedes'); 
INSERT INTO circunscricoes values (174, 'Sebastianópolis do Sul'); 
INSERT INTO circunscricoes values (139, 'Sarutaiá'); 
INSERT INTO circunscricoes values (296, 'União Paulista'); 
INSERT INTO circunscricoes values (35, 'Cristais Paulista'); 
INSERT INTO circunscricoes values (283, 'Paulo de Faria'); 
INSERT INTO circunscricoes values (196, 'Monteiro Lobato'); 
INSERT INTO circunscricoes values (46, 'Santa Albertina'); 
INSERT INTO circunscricoes values (268, 'Brotas'); 
INSERT INTO circunscricoes values (206, 'Iacanga'); 
INSERT INTO circunscricoes values (311, 'Itaberá'); 
INSERT INTO circunscricoes values (282, 'Populina'); 
INSERT INTO circunscricoes values (132, 'Ipaussu'); 
INSERT INTO circunscricoes values (246, 'Conchal'); 
INSERT INTO circunscricoes values (171, 'Guaimbê'); 
INSERT INTO circunscricoes values (17, 'Suzanápolis'); 
INSERT INTO circunscricoes values (344, 'Pontes Gestal'); 
INSERT INTO circunscricoes values (134, 'Santa Cruz do Rio Pardo'); 
INSERT INTO circunscricoes values (276, 'Morungaba'); 
INSERT INTO circunscricoes values (309, 'São João das Duas Pontes'); 
INSERT INTO circunscricoes values (172, 'Parapuã'); 
INSERT INTO circunscricoes values (285, 'Campina do Monte Alegre'); 
INSERT INTO circunscricoes values (153, 'Tapiratiba'); 
INSERT INTO circunscricoes values (53, 'Barra do Turvo'); 
INSERT INTO circunscricoes values (327, 'Itapura'); 
INSERT INTO circunscricoes values (210, 'Palmares Paulista'); 
INSERT INTO circunscricoes values (209, 'Alvinlândia'); 
INSERT INTO circunscricoes values (278, 'Gavião Peixoto'); 
INSERT INTO circunscricoes values (159, 'Lavínia'); 
INSERT INTO circunscricoes values (341, 'Ribeirão do Sul'); 
INSERT INTO circunscricoes values (299, 'Ibirarema'); 
INSERT INTO circunscricoes values (290, 'Santa Lucia'); 
INSERT INTO circunscricoes values (198, 'Ilha Solteira'); 
INSERT INTO circunscricoes values (312, 'Nova Campina'); 
INSERT INTO circunscricoes values (24, 'Joanópolis'); 
INSERT INTO circunscricoes values (317, 'Lindóia'); 
INSERT INTO circunscricoes values (225, 'Biritiba Mirim'); 
INSERT INTO circunscricoes values (348, 'Ribeirão Grande'); 
INSERT INTO circunscricoes values (61, 'Porangaba'); 
INSERT INTO circunscricoes values (314, 'Itirapina'); 
INSERT INTO circunscricoes values (315, 'Guararema'); 
INSERT INTO circunscricoes values (350, 'Iracemápolis'); 
INSERT INTO circunscricoes values (343, 'Sales'); 
INSERT INTO circunscricoes values (191, 'Charqueada'); 
INSERT INTO circunscricoes values (269, 'Corumbataí'); 
INSERT INTO circunscricoes values (239, 'Coronel Macedo'); 
INSERT INTO circunscricoes values (111, 'São Bento do Sapucaí'); 
INSERT INTO circunscricoes values (118, 'Rincão'); 
INSERT INTO circunscricoes values (320, 'Echaporã'); 
INSERT INTO circunscricoes values (45, 'Mira Estrela'); 
INSERT INTO circunscricoes values (146, 'Junqueirópolis'); 
INSERT INTO circunscricoes values (277, 'Dobrada'); 
INSERT INTO circunscricoes values (232, 'Orlândia'); 
INSERT INTO circunscricoes values (185, 'Pirapozinho'); 
INSERT INTO circunscricoes values (170, 'Guaiçara'); 
INSERT INTO circunscricoes values (337, 'Severínia'); 
INSERT INTO circunscricoes values (266, 'Tarumã'); 
INSERT INTO circunscricoes values (203, 'Vista Alegre do Alto'); 
INSERT INTO circunscricoes values (168, 'Macatuba'); 
INSERT INTO circunscricoes values (48, 'Icém'); 
INSERT INTO circunscricoes values (221, 'Flórida Paulista'); 
INSERT INTO circunscricoes values (131, 'Getulina'); 
INSERT INTO circunscricoes values (292, 'Buritizal'); 
INSERT INTO circunscricoes values (207, 'Itaju'); 
INSERT INTO circunscricoes values (281, 'Canitar'); 
INSERT INTO circunscricoes values (319, 'Cafelândia'); 
INSERT INTO circunscricoes values (158, 'Queluz'); 
INSERT INTO circunscricoes values (289, 'Borborema'); 
INSERT INTO circunscricoes values (142, 'Ribeira'); 
INSERT INTO circunscricoes values (141, 'Pardinho'); 
INSERT INTO circunscricoes values (19, 'Lourdes'); 
INSERT INTO circunscricoes values (262, 'Cesário Lange'); 
INSERT INTO circunscricoes values (43, 'Lupércio'); 
INSERT INTO circunscricoes values (307, 'Reginópolis'); 
INSERT INTO circunscricoes values (345, 'Cananéia'); 
INSERT INTO circunscricoes values (236, 'Ocauçu'); 
INSERT INTO circunscricoes values (167, 'Cabrália Paulista'); 
INSERT INTO circunscricoes values (308, 'Estrela DOeste'); 
INSERT INTO circunscricoes values (273, 'Santa Branca'); 
INSERT INTO circunscricoes values (237, 'Jales'); 
INSERT INTO circunscricoes values (335, 'Salesópolis'); 
INSERT INTO circunscricoes values (213, 'Américo de Campos'); 
INSERT INTO circunscricoes values (265, 'Itararé'); 
INSERT INTO circunscricoes values (179, 'Bofete'); 
INSERT INTO circunscricoes values (322, 'Onda Verde'); 
INSERT INTO circunscricoes values (279, 'Barra Bonita'); 
