INSERT INTO circunscricoes values (374, 'Américo de Campos'); 
INSERT INTO circunscricoes values (375, 'Canitar'); 
INSERT INTO circunscricoes values (376, 'Santa Albertina'); 
INSERT INTO circunscricoes values (377, 'Itapura'); 
INSERT INTO circunscricoes values (378, 'Barra Bonita'); 
INSERT INTO circunscricoes values (379, 'Guaimbê'); 
INSERT INTO circunscricoes values (380, 'Iracemápolis'); 
INSERT INTO circunscricoes values (381, 'Santa Branca'); 
INSERT INTO circunscricoes values (382, 'Onda Verde'); 
INSERT INTO circunscricoes values (383, 'Pardinho'); 
INSERT INTO circunscricoes values (384, 'Dobrada'); 
INSERT INTO circunscricoes values (385, 'Cafelândia'); 
INSERT INTO circunscricoes values (386, 'Sarutaiá'); 
INSERT INTO circunscricoes values (387, 'Nova Campina'); 
INSERT INTO circunscricoes values (388, 'Palmares Paulista'); 
INSERT INTO circunscricoes values (389, 'Ocauçu'); 
INSERT INTO circunscricoes values (390, 'Queluz'); 
INSERT INTO circunscricoes values (391, 'Tarumã'); 
INSERT INTO circunscricoes values (392, 'Ribeirão do Sul'); 
INSERT INTO circunscricoes values (393, 'Junqueirópolis'); 
INSERT INTO circunscricoes values (394, 'Paulo de Faria'); 
INSERT INTO circunscricoes values (395, 'Brotas'); 
INSERT INTO circunscricoes values (396, 'Cristais Paulista'); 
INSERT INTO circunscricoes values (397, 'Lupércio'); 
INSERT INTO circunscricoes values (398, 'Santa Lucia'); 
INSERT INTO circunscricoes values (399, 'Orlândia'); 
INSERT INTO circunscricoes values (400, 'Guaiçara'); 
INSERT INTO circunscricoes values (401, 'Biritiba Mirim'); 
INSERT INTO circunscricoes values (402, 'Mira Estrela'); 
INSERT INTO circunscricoes values (403, 'Jales'); 
INSERT INTO circunscricoes values (404, 'Itaju'); 
INSERT INTO circunscricoes values (405, 'Porangaba'); 
INSERT INTO circunscricoes values (406, 'Bofete'); 
INSERT INTO circunscricoes values (407, 'Iacanga'); 
INSERT INTO circunscricoes values (408, 'Ribeirão Grande'); 
INSERT INTO circunscricoes values (409, 'Itaberá'); 
INSERT INTO circunscricoes values (410, 'Getulina'); 
INSERT INTO circunscricoes values (411, 'Pirapozinho'); 
INSERT INTO circunscricoes values (412, 'Echaporã'); 
INSERT INTO circunscricoes values (413, 'Cesário Lange'); 
INSERT INTO circunscricoes values (414, 'Coronel Macedo'); 
INSERT INTO circunscricoes values (415, 'Pontes Gestal'); 
INSERT INTO circunscricoes values (416, 'Vista Alegre do Alto'); 
INSERT INTO circunscricoes values (417, 'Buritizal'); 
INSERT INTO circunscricoes values (418, 'Santa Mercedes'); 
INSERT INTO circunscricoes values (419, 'Barra do Turvo'); 
INSERT INTO circunscricoes values (420, 'Itirapina'); 
INSERT INTO circunscricoes values (421, 'Ibirarema'); 
INSERT INTO circunscricoes values (422, 'Reginópolis'); 
INSERT INTO circunscricoes values (423, 'Ipaussu'); 
INSERT INTO circunscricoes values (424, 'Tapiratiba'); 
INSERT INTO circunscricoes values (425, 'Charqueada'); 
INSERT INTO circunscricoes values (426, 'Borborema'); 
INSERT INTO circunscricoes values (427, 'Suzanápolis'); 
INSERT INTO circunscricoes values (428, 'Cananéia'); 
INSERT INTO circunscricoes values (429, 'Severínia'); 
INSERT INTO circunscricoes values (430, 'Corumbataí'); 
INSERT INTO circunscricoes values (431, 'Monteiro Lobato'); 
INSERT INTO circunscricoes values (432, 'União Paulista'); 
INSERT INTO circunscricoes values (433, 'Guararema'); 
INSERT INTO circunscricoes values (434, 'Conchal'); 
INSERT INTO circunscricoes values (435, 'Parapuã'); 
INSERT INTO circunscricoes values (436, 'Sebastianópolis do Sul'); 
INSERT INTO circunscricoes values (437, 'São João das Duas Pontes'); 
INSERT INTO circunscricoes values (438, 'Macatuba'); 
INSERT INTO circunscricoes values (439, 'Salesópolis'); 
INSERT INTO circunscricoes values (440, 'São Bento do Sapucaí'); 
INSERT INTO circunscricoes values (441, 'Cabrália Paulista'); 
INSERT INTO circunscricoes values (442, 'Sales'); 
INSERT INTO circunscricoes values (443, 'Gavião Peixoto'); 
INSERT INTO circunscricoes values (444, 'Lourdes'); 
INSERT INTO circunscricoes values (445, 'Icém'); 
INSERT INTO circunscricoes values (446, 'Lavínia'); 
INSERT INTO circunscricoes values (447, 'Santa Cruz do Rio Pardo'); 
INSERT INTO circunscricoes values (448, 'Flórida Paulista'); 
INSERT INTO circunscricoes values (449, 'Populina'); 
INSERT INTO circunscricoes values (450, 'Campina do Monte Alegre'); 
INSERT INTO circunscricoes values (451, 'Itararé'); 
INSERT INTO circunscricoes values (452, 'Lindóia'); 
INSERT INTO circunscricoes values (453, 'Ilha Solteira'); 
INSERT INTO circunscricoes values (454, 'Rincão'); 
INSERT INTO circunscricoes values (455, 'Alvinlândia'); 
INSERT INTO circunscricoes values (456, 'Joanópolis'); 
INSERT INTO circunscricoes values (457, 'Morungaba'); 
INSERT INTO circunscricoes values (458, 'Estrela D'Oeste'); 
INSERT INTO circunscricoes values (459, 'Ribeira'); 
