INSERT INTO circunscricoes values (1, 'São Paulo'); 
INSERT INTO circunscricoes values (2, 'Cruzeiro'); 
INSERT INTO circunscricoes values (3, 'Aparecida'); 
INSERT INTO circunscricoes values (4, 'Canas'); 
INSERT INTO circunscricoes values (5, 'Guaratinguetá'); 
INSERT INTO circunscricoes values (6, 'Lorena'); 
INSERT INTO circunscricoes values (7, 'Potim'); 
INSERT INTO circunscricoes values (8, 'Jacareí'); 
INSERT INTO circunscricoes values (9, 'São José dos Campos'); 
INSERT INTO circunscricoes values (10, 'Caraguatatuba'); 
INSERT INTO circunscricoes values (11, 'São Sebastião'); 
INSERT INTO circunscricoes values (12, 'Ubatuba'); 
INSERT INTO circunscricoes values (13, 'Campos do Jordão'); 
INSERT INTO circunscricoes values (14, 'Pindamonhangaba'); 
INSERT INTO circunscricoes values (15, 'Taubaté'); 
INSERT INTO circunscricoes values (16, 'Pereira Barreto'); 
INSERT INTO circunscricoes values (17, 'Suzanápolis'); 
INSERT INTO circunscricoes values (18, 'Araçatuba'); 
INSERT INTO circunscricoes values (19, 'Lourdes'); 
INSERT INTO circunscricoes values (20, 'Campinas'); 
INSERT INTO circunscricoes values (21, 'Indaiatuba'); 
INSERT INTO circunscricoes values (22, 'Atibaia'); 
INSERT INTO circunscricoes values (23, 'Bragança Paulista'); 
INSERT INTO circunscricoes values (24, 'Joanópolis'); 
INSERT INTO circunscricoes values (25, 'Campo Limpo Paulista'); 
INSERT INTO circunscricoes values (26, 'Jundiaí'); 
INSERT INTO circunscricoes values (27, 'Várzea Paulista'); 
INSERT INTO circunscricoes values (28, 'Itapira'); 
INSERT INTO circunscricoes values (29, 'Mogi Guaçu'); 
INSERT INTO circunscricoes values (30, 'Araraquara'); 
INSERT INTO circunscricoes values (31, 'Ibitinga'); 
INSERT INTO circunscricoes values (32, 'Itápolis'); 
INSERT INTO circunscricoes values (33, 'Olímpia'); 
INSERT INTO circunscricoes values (34, 'Taiaçu'); 
INSERT INTO circunscricoes values (35, 'Cristais Paulista'); 
INSERT INTO circunscricoes values (36, 'Ribeirão Preto'); 
INSERT INTO circunscricoes values (37, 'Porto Ferreira'); 
INSERT INTO circunscricoes values (38, 'São Carlos'); 
INSERT INTO circunscricoes values (39, 'Guariba'); 
INSERT INTO circunscricoes values (40, 'Sertãozinho'); 
INSERT INTO circunscricoes values (41, 'Agudos'); 
INSERT INTO circunscricoes values (42, 'Lins'); 
INSERT INTO circunscricoes values (43, 'Lupércio'); 
INSERT INTO circunscricoes values (44, 'Marília'); 
INSERT INTO circunscricoes values (45, 'Mira Estrela'); 
INSERT INTO circunscricoes values (46, 'Santa Albertina'); 
INSERT INTO circunscricoes values (47, 'Urânia'); 
INSERT INTO circunscricoes values (48, 'Icém'); 
INSERT INTO circunscricoes values (49, 'São José do Rio Preto'); 
INSERT INTO circunscricoes values (50, 'Tanabi'); 
INSERT INTO circunscricoes values (51, 'Itanhaém'); 
INSERT INTO circunscricoes values (52, 'Mongaguá'); 
INSERT INTO circunscricoes values (53, 'Barra do Turvo'); 
INSERT INTO circunscricoes values (54, 'Iguape'); 
INSERT INTO circunscricoes values (55, 'Cubatão'); 
INSERT INTO circunscricoes values (56, 'Guarujá'); 
INSERT INTO circunscricoes values (57, 'Praia Grande'); 
INSERT INTO circunscricoes values (58, 'Santos'); 
INSERT INTO circunscricoes values (59, 'São Vicente'); 
INSERT INTO circunscricoes values (60, 'Iaras'); 
INSERT INTO circunscricoes values (61, 'Porangaba'); 
INSERT INTO circunscricoes values (62, 'Itapetininga'); 
INSERT INTO circunscricoes values (63, 'Tatuí'); 
INSERT INTO circunscricoes values (64, 'Capão Bonito'); 
INSERT INTO circunscricoes values (65, 'Itu'); 
INSERT INTO circunscricoes values (66, 'São Roque'); 
INSERT INTO circunscricoes values (67, 'Sorocaba'); 
INSERT INTO circunscricoes values (68, 'Votorantim'); 
INSERT INTO circunscricoes values (69, 'Paraguaçu Paulista'); 
INSERT INTO circunscricoes values (70, 'Presidente Prudente'); 
INSERT INTO circunscricoes values (71, 'Cosmópolis'); 
INSERT INTO circunscricoes values (72, 'Engenheiro Coelho'); 
INSERT INTO circunscricoes values (73, 'Hortolândia'); 
INSERT INTO circunscricoes values (74, 'Monte Mor'); 
INSERT INTO circunscricoes values (75, 'Santa Bárbara D'Oeste'); 
INSERT INTO circunscricoes values (76, 'Sumaré'); 
INSERT INTO circunscricoes values (77, 'Leme'); 
INSERT INTO circunscricoes values (78, 'Pirassununga'); 
INSERT INTO circunscricoes values (79, 'Piracicaba'); 
INSERT INTO circunscricoes values (80, 'Rio Claro'); 
INSERT INTO circunscricoes values (81, 'Espírito Santo do Pinhal'); 
INSERT INTO circunscricoes values (82, 'Carapicuíba'); 
INSERT INTO circunscricoes values (83, 'Cotia'); 
INSERT INTO circunscricoes values (84, 'Itapevi'); 
INSERT INTO circunscricoes values (85, 'Jandira'); 
INSERT INTO circunscricoes values (86, 'Pirapora do Bom Jesus'); 
INSERT INTO circunscricoes values (87, 'Santana de Parnaíba'); 
INSERT INTO circunscricoes values (88, 'Diadema'); 
INSERT INTO circunscricoes values (89, 'Caieiras'); 
INSERT INTO circunscricoes values (90, 'Cajamar'); 
INSERT INTO circunscricoes values (91, 'Francisco Morato'); 
INSERT INTO circunscricoes values (92, 'Mairiporã'); 
INSERT INTO circunscricoes values (93, 'Arujá'); 
INSERT INTO circunscricoes values (94, 'Guarulhos'); 
INSERT INTO circunscricoes values (95, 'Santa Isabel'); 
INSERT INTO circunscricoes values (96, 'Ferraz de Vasconcelos'); 
INSERT INTO circunscricoes values (97, 'Itaquaquecetuba'); 
INSERT INTO circunscricoes values (98, 'Mogi das Cruzes'); 
INSERT INTO circunscricoes values (99, 'Poá'); 
INSERT INTO circunscricoes values (100, 'Suzano'); 
INSERT INTO circunscricoes values (101, 'Osasco'); 
INSERT INTO circunscricoes values (102, 'Mauá'); 
INSERT INTO circunscricoes values (103, 'Ribeirão Pires'); 
INSERT INTO circunscricoes values (104, 'Santo André'); 
INSERT INTO circunscricoes values (105, 'São Bernardo do Campo'); 
INSERT INTO circunscricoes values (106, 'Embu das Artes'); 
INSERT INTO circunscricoes values (107, 'Embu-Guaçu'); 
INSERT INTO circunscricoes values (108, 'Itapecerica da Serra'); 
INSERT INTO circunscricoes values (109, 'Taboão da Serra'); 
INSERT INTO circunscricoes values (110, 'Caçapava'); 
INSERT INTO circunscricoes values (111, 'São Bento do Sapucaí'); 
INSERT INTO circunscricoes values (112, 'Tremembé'); 
INSERT INTO circunscricoes values (113, 'Guararapes'); 
INSERT INTO circunscricoes values (114, 'Piracaia'); 
INSERT INTO circunscricoes values (115, 'Itatiba'); 
INSERT INTO circunscricoes values (116, 'Mogi Mirim'); 
INSERT INTO circunscricoes values (117, 'Matão'); 
INSERT INTO circunscricoes values (118, 'Rincão'); 
INSERT INTO circunscricoes values (119, 'Cajobi'); 
INSERT INTO circunscricoes values (120, 'Guaíra'); 
INSERT INTO circunscricoes values (121, 'Batatais'); 
INSERT INTO circunscricoes values (122, 'Franca'); 
INSERT INTO circunscricoes values (123, 'Restinga'); 
INSERT INTO circunscricoes values (124, 'Cravinhos'); 
INSERT INTO circunscricoes values (125, 'Morro Agudo'); 
INSERT INTO circunscricoes values (126, 'Pitangueiras'); 
INSERT INTO circunscricoes values (127, 'Bauru'); 
INSERT INTO circunscricoes values (128, 'Lençóis Paulista'); 
INSERT INTO circunscricoes values (129, 'Pederneiras'); 
INSERT INTO circunscricoes values (130, 'Jaú'); 
INSERT INTO circunscricoes values (131, 'Getulina'); 
INSERT INTO circunscricoes values (132, 'Ipaussu'); 
INSERT INTO circunscricoes values (133, 'Ourinhos'); 
INSERT INTO circunscricoes values (134, 'Santa Cruz do Rio Pardo'); 
INSERT INTO circunscricoes values (135, 'Catanduva'); 
INSERT INTO circunscricoes values (136, 'Valentim Gentil'); 
INSERT INTO circunscricoes values (137, 'Votuporanga'); 
INSERT INTO circunscricoes values (138, 'Itaporanga'); 
INSERT INTO circunscricoes values (139, 'Sarutaiá'); 
INSERT INTO circunscricoes values (140, 'Botucatu'); 
INSERT INTO circunscricoes values (141, 'Pardinho'); 
INSERT INTO circunscricoes values (142, 'Ribeira'); 
INSERT INTO circunscricoes values (143, 'Ibiúna'); 
INSERT INTO circunscricoes values (144, 'Mairinque'); 
INSERT INTO circunscricoes values (145, 'Salto'); 
INSERT INTO circunscricoes values (146, 'Junqueirópolis'); 
INSERT INTO circunscricoes values (147, 'Tupi Paulista'); 
INSERT INTO circunscricoes values (148, 'Rosana'); 
INSERT INTO circunscricoes values (149, 'Santo Anastácio'); 
INSERT INTO circunscricoes values (150, 'Americana'); 
INSERT INTO circunscricoes values (151, 'Nova Odessa'); 
INSERT INTO circunscricoes values (152, 'Casa Branca'); 
INSERT INTO circunscricoes values (153, 'Tapiratiba'); 
INSERT INTO circunscricoes values (154, 'Cordeirópolis'); 
INSERT INTO circunscricoes values (155, 'Limeira'); 
INSERT INTO circunscricoes values (156, 'Santa Gertrudes'); 
INSERT INTO circunscricoes values (157, 'Vargem Grande Paulista'); 
INSERT INTO circunscricoes values (158, 'Queluz'); 
INSERT INTO circunscricoes values (159, 'Lavínia'); 
INSERT INTO circunscricoes values (160, 'Birigui'); 
INSERT INTO circunscricoes values (161, 'Bebedouro'); 
INSERT INTO circunscricoes values (162, 'Miguelópolis'); 
INSERT INTO circunscricoes values (163, 'Patrocínio Paulista'); 
INSERT INTO circunscricoes values (164, 'Jardinópolis'); 
INSERT INTO circunscricoes values (165, 'Ibaté'); 
INSERT INTO circunscricoes values (166, 'Jaboticabal'); 
INSERT INTO circunscricoes values (167, 'Cabrália Paulista'); 
INSERT INTO circunscricoes values (168, 'Macatuba'); 
INSERT INTO circunscricoes values (169, 'Igaraçu do Tietê'); 
INSERT INTO circunscricoes values (170, 'Guaiçara'); 
INSERT INTO circunscricoes values (171, 'Guaimbê'); 
INSERT INTO circunscricoes values (172, 'Parapuã'); 
INSERT INTO circunscricoes values (173, 'José Bonifácio'); 
INSERT INTO circunscricoes values (174, 'Sebastianópolis do Sul'); 
INSERT INTO circunscricoes values (175, 'Peruíbe'); 
INSERT INTO circunscricoes values (176, 'Sete Barras'); 
INSERT INTO circunscricoes values (177, 'Bertioga'); 
INSERT INTO circunscricoes values (178, 'Itaí'); 
INSERT INTO circunscricoes values (179, 'Bofete'); 
INSERT INTO circunscricoes values (180, 'Itatinga'); 
INSERT INTO circunscricoes values (181, 'Boituva'); 
INSERT INTO circunscricoes values (182, 'Buri'); 
INSERT INTO circunscricoes values (183, 'Salto de Pirapora'); 
INSERT INTO circunscricoes values (184, 'Assis'); 
INSERT INTO circunscricoes values (185, 'Pirapozinho'); 
INSERT INTO circunscricoes values (186, 'Regente Feijó'); 
INSERT INTO circunscricoes values (187, 'Presidente Epitácio'); 
INSERT INTO circunscricoes values (188, 'Presidente Venceslau'); 
INSERT INTO circunscricoes values (189, 'Artur Nogueira'); 
INSERT INTO circunscricoes values (190, 'Itobi'); 
INSERT INTO circunscricoes values (191, 'Charqueada'); 
INSERT INTO circunscricoes values (192, 'São Sebastião da Grama'); 
INSERT INTO circunscricoes values (193, 'Barueri'); 
INSERT INTO circunscricoes values (194, 'Franco da Rocha'); 
INSERT INTO circunscricoes values (195, 'São Lourenço da Serra'); 
INSERT INTO circunscricoes values (196, 'Monteiro Lobato'); 
INSERT INTO circunscricoes values (197, 'Andradina'); 
INSERT INTO circunscricoes values (198, 'Ilha Solteira'); 
INSERT INTO circunscricoes values (199, 'Buritama'); 
INSERT INTO circunscricoes values (200, 'Penápolis'); 
INSERT INTO circunscricoes values (201, 'Jaguariúna'); 
INSERT INTO circunscricoes values (202, 'Tabatinga'); 
INSERT INTO circunscricoes values (203, 'Vista Alegre do Alto'); 
INSERT INTO circunscricoes values (204, 'Guará'); 
INSERT INTO circunscricoes values (205, 'Monte Alto'); 
INSERT INTO circunscricoes values (206, 'Iacanga'); 
INSERT INTO circunscricoes values (207, 'Itaju'); 
INSERT INTO circunscricoes values (208, 'Promissão'); 
INSERT INTO circunscricoes values (209, 'Alvinlândia'); 
INSERT INTO circunscricoes values (210, 'Palmares Paulista'); 
INSERT INTO circunscricoes values (211, 'Tabapuã'); 
INSERT INTO circunscricoes values (212, 'Urupês'); 
INSERT INTO circunscricoes values (213, 'Américo de Campos'); 
INSERT INTO circunscricoes values (214, 'Miracatu'); 
INSERT INTO circunscricoes values (215, 'Avaré'); 
INSERT INTO circunscricoes values (216, 'Piraju'); 
INSERT INTO circunscricoes values (217, 'Araçoiaba da Serra'); 
INSERT INTO circunscricoes values (218, 'Porto Feliz'); 
INSERT INTO circunscricoes values (219, 'Tietê'); 
INSERT INTO circunscricoes values (220, 'Adamantina'); 
INSERT INTO circunscricoes values (221, 'Flórida Paulista'); 
INSERT INTO circunscricoes values (222, 'Teodoro Sampaio'); 
INSERT INTO circunscricoes values (223, 'Santa Cruz das Palmeiras'); 
INSERT INTO circunscricoes values (224, 'São Pedro'); 
INSERT INTO circunscricoes values (225, 'Biritiba Mirim'); 
INSERT INTO circunscricoes values (226, 'Ilhabela'); 
INSERT INTO circunscricoes values (227, 'Paulínia'); 
INSERT INTO circunscricoes values (228, 'Valinhos'); 
INSERT INTO circunscricoes values (229, 'Águas de Lindóia'); 
INSERT INTO circunscricoes values (230, 'Américo Brasiliense'); 
INSERT INTO circunscricoes values (231, 'Ituverava'); 
INSERT INTO circunscricoes values (232, 'Orlândia'); 
INSERT INTO circunscricoes values (233, 'Pontal'); 
INSERT INTO circunscricoes values (234, 'Balbinos'); 
INSERT INTO circunscricoes values (235, 'Sabino'); 
INSERT INTO circunscricoes values (236, 'Ocauçu'); 
INSERT INTO circunscricoes values (237, 'Jales'); 
INSERT INTO circunscricoes values (238, 'Mirassol'); 
INSERT INTO circunscricoes values (239, 'Coronel Macedo'); 
INSERT INTO circunscricoes values (240, 'Fartura'); 
INSERT INTO circunscricoes values (241, 'Anhembi'); 
INSERT INTO circunscricoes values (242, 'Araçariguama'); 
INSERT INTO circunscricoes values (243, 'Palmital'); 
INSERT INTO circunscricoes values (244, 'Álvares Machado'); 
INSERT INTO circunscricoes values (245, 'Araras'); 
INSERT INTO circunscricoes values (246, 'Conchal'); 
INSERT INTO circunscricoes values (247, 'Rio Grande da Serra'); 
INSERT INTO circunscricoes values (248, 'Cachoeira Paulista'); 
INSERT INTO circunscricoes values (249, 'Castilho'); 
INSERT INTO circunscricoes values (250, 'Nazaré Paulista'); 
INSERT INTO circunscricoes values (251, 'Socorro'); 
INSERT INTO circunscricoes values (252, 'Jarinu'); 
INSERT INTO circunscricoes values (253, 'Santo Antônio de Posse'); 
INSERT INTO circunscricoes values (254, 'Colina'); 
INSERT INTO circunscricoes values (255, 'Pirangi'); 
INSERT INTO circunscricoes values (256, 'São Simão'); 
INSERT INTO circunscricoes values (257, 'Serrana'); 
INSERT INTO circunscricoes values (258, 'Santa Rita do Passa Quatro'); 
INSERT INTO circunscricoes values (259, 'Pindorama'); 
INSERT INTO circunscricoes values (260, 'Monte Aprazível'); 
INSERT INTO circunscricoes values (261, 'Itariri'); 
INSERT INTO circunscricoes values (262, 'Cesário Lange'); 
INSERT INTO circunscricoes values (263, 'São Miguel Arcanjo'); 
INSERT INTO circunscricoes values (264, 'Apiaí'); 
INSERT INTO circunscricoes values (265, 'Itararé'); 
INSERT INTO circunscricoes values (266, 'Tarumã'); 
INSERT INTO circunscricoes values (267, 'Panorama'); 
INSERT INTO circunscricoes values (268, 'Brotas'); 
INSERT INTO circunscricoes values (269, 'Corumbataí'); 
INSERT INTO circunscricoes values (270, 'Aguaí'); 
INSERT INTO circunscricoes values (271, 'Juquitiba'); 
INSERT INTO circunscricoes values (272, 'Paraibuna'); 
INSERT INTO circunscricoes values (273, 'Santa Branca'); 
INSERT INTO circunscricoes values (274, 'Amparo'); 
INSERT INTO circunscricoes values (275, 'Louveira'); 
INSERT INTO circunscricoes values (276, 'Morungaba'); 
INSERT INTO circunscricoes values (277, 'Dobrada'); 
INSERT INTO circunscricoes values (278, 'Gavião Peixoto'); 
INSERT INTO circunscricoes values (279, 'Barra Bonita'); 
INSERT INTO circunscricoes values (280, 'Dois Córregos'); 
INSERT INTO circunscricoes values (281, 'Canitar'); 
INSERT INTO circunscricoes values (282, 'Populina'); 
INSERT INTO circunscricoes values (283, 'Paulo de Faria'); 
INSERT INTO circunscricoes values (284, 'Registro'); 
INSERT INTO circunscricoes values (285, 'Campina do Monte Alegre'); 
INSERT INTO circunscricoes values (286, 'Piedade'); 
INSERT INTO circunscricoes values (287, 'Santo Antonio do Aracanguá'); 
INSERT INTO circunscricoes values (288, 'Cabreúva'); 
INSERT INTO circunscricoes values (289, 'Borborema'); 
INSERT INTO circunscricoes values (290, 'Santa Lucia'); 
INSERT INTO circunscricoes values (291, 'Barretos'); 
INSERT INTO circunscricoes values (292, 'Buritizal'); 
INSERT INTO circunscricoes values (293, 'Garça'); 
INSERT INTO circunscricoes values (294, 'Tupã'); 
INSERT INTO circunscricoes values (295, 'Bady Bassitt'); 
INSERT INTO circunscricoes values (296, 'União Paulista'); 
INSERT INTO circunscricoes values (297, 'Juquiá'); 
INSERT INTO circunscricoes values (298, 'Iperó'); 
INSERT INTO circunscricoes values (299, 'Ibirarema'); 
INSERT INTO circunscricoes values (300, 'Vargem Grande do Sul'); 
INSERT INTO circunscricoes values (301, 'Roseira'); 
INSERT INTO circunscricoes values (302, 'Igaratá'); 
INSERT INTO circunscricoes values (303, 'Natividade da Serra'); 
INSERT INTO circunscricoes values (304, 'Avanhandava'); 
INSERT INTO circunscricoes values (305, 'Pradópolis'); 
INSERT INTO circunscricoes values (306, 'Arealva'); 
INSERT INTO circunscricoes values (307, 'Reginópolis'); 
INSERT INTO circunscricoes values (308, 'Estrela D'Oeste'); 
INSERT INTO circunscricoes values (309, 'São João das Duas Pontes'); 
INSERT INTO circunscricoes values (310, 'Novo Horizonte'); 
INSERT INTO circunscricoes values (311, 'Itaberá'); 
INSERT INTO circunscricoes values (312, 'Nova Campina'); 
INSERT INTO circunscricoes values (313, 'Capivari'); 
INSERT INTO circunscricoes values (314, 'Itirapina'); 
INSERT INTO circunscricoes values (315, 'Guararema'); 
INSERT INTO circunscricoes values (316, 'Auriflama'); 
INSERT INTO circunscricoes values (317, 'Lindóia'); 
INSERT INTO circunscricoes values (318, 'Itupeva'); 
INSERT INTO circunscricoes values (319, 'Cafelândia'); 
INSERT INTO circunscricoes values (320, 'Echaporã'); 
INSERT INTO circunscricoes values (321, 'Santa Fé do Sul'); 
INSERT INTO circunscricoes values (322, 'Onda Verde'); 
INSERT INTO circunscricoes values (323, 'Potirendaba'); 
INSERT INTO circunscricoes values (324, 'Guareí'); 
INSERT INTO circunscricoes values (325, 'São João da Boa Vista'); 
INSERT INTO circunscricoes values (326, 'Cunha'); 
INSERT INTO circunscricoes values (327, 'Itapura'); 
INSERT INTO circunscricoes values (328, 'Vargem'); 
INSERT INTO circunscricoes values (329, 'Altair'); 
INSERT INTO circunscricoes values (330, 'Santa Rosa do Viterbo'); 
INSERT INTO circunscricoes values (331, 'São Joaquim da Barra'); 
INSERT INTO circunscricoes values (332, 'Bocaina'); 
INSERT INTO circunscricoes values (333, 'Taquarituba'); 
INSERT INTO circunscricoes values (334, 'Santa Mercedes'); 
INSERT INTO circunscricoes values (335, 'Salesópolis'); 
INSERT INTO circunscricoes values (336, 'Colômbia'); 
INSERT INTO circunscricoes values (337, 'Severínia'); 
INSERT INTO circunscricoes values (338, 'Igarapava'); 
INSERT INTO circunscricoes values (339, 'Barrinha'); 
INSERT INTO circunscricoes values (340, 'Vera Cruz'); 
INSERT INTO circunscricoes values (341, 'Ribeirão do Sul'); 
INSERT INTO circunscricoes values (342, 'Ouroeste'); 
INSERT INTO circunscricoes values (343, 'Sales'); 
INSERT INTO circunscricoes values (344, 'Pontes Gestal'); 
INSERT INTO circunscricoes values (345, 'Cananéia'); 
INSERT INTO circunscricoes values (346, 'Areiópolis'); 
INSERT INTO circunscricoes values (347, 'Itapeva'); 
INSERT INTO circunscricoes values (348, 'Ribeirão Grande'); 
INSERT INTO circunscricoes values (349, 'Mirante do Paranapanema'); 
INSERT INTO circunscricoes values (350, 'Iracemápolis'); 
