UPDATE circunscricoes SET cir_municipio = 'São Paulo' where cir_id = 1; 
UPDATE circunscricoes SET cir_municipio = 'Cruzeiro' where cir_id = 2; 
UPDATE circunscricoes SET cir_municipio = 'Aparecida' where cir_id = 3; 
UPDATE circunscricoes SET cir_municipio = 'Canas' where cir_id = 4; 
UPDATE circunscricoes SET cir_municipio = 'Guaratinguetá' where cir_id = 5; 
UPDATE circunscricoes SET cir_municipio = 'Lorena' where cir_id = 6; 
UPDATE circunscricoes SET cir_municipio = 'Potim' where cir_id = 7; 
UPDATE circunscricoes SET cir_municipio = 'Jacareí' where cir_id = 8; 
UPDATE circunscricoes SET cir_municipio = 'São José dos Campos' where cir_id = 9; 
UPDATE circunscricoes SET cir_municipio = 'Caraguatatuba' where cir_id = 10; 
UPDATE circunscricoes SET cir_municipio = 'São Sebastião' where cir_id = 11; 
UPDATE circunscricoes SET cir_municipio = 'Ubatuba' where cir_id = 12; 
UPDATE circunscricoes SET cir_municipio = 'Campos do Jordão' where cir_id = 13; 
UPDATE circunscricoes SET cir_municipio = 'Pindamonhangaba' where cir_id = 14; 
UPDATE circunscricoes SET cir_municipio = 'Taubaté' where cir_id = 15; 
UPDATE circunscricoes SET cir_municipio = 'Pereira Barreto' where cir_id = 16; 
UPDATE circunscricoes SET cir_municipio = 'Suzanápolis' where cir_id = 17; 
UPDATE circunscricoes SET cir_municipio = 'Araçatuba' where cir_id = 18; 
UPDATE circunscricoes SET cir_municipio = 'Lourdes' where cir_id = 19; 
UPDATE circunscricoes SET cir_municipio = 'Campinas' where cir_id = 20; 
UPDATE circunscricoes SET cir_municipio = 'Indaiatuba' where cir_id = 21; 
UPDATE circunscricoes SET cir_municipio = 'Atibaia' where cir_id = 22; 
UPDATE circunscricoes SET cir_municipio = 'Bragança Paulista' where cir_id = 23; 
UPDATE circunscricoes SET cir_municipio = 'Joanópolis' where cir_id = 24; 
UPDATE circunscricoes SET cir_municipio = 'Campo Limpo Paulista' where cir_id = 25; 
UPDATE circunscricoes SET cir_municipio = 'Jundiaí' where cir_id = 26; 
UPDATE circunscricoes SET cir_municipio = 'Várzea Paulista' where cir_id = 27; 
UPDATE circunscricoes SET cir_municipio = 'Itapira' where cir_id = 28; 
UPDATE circunscricoes SET cir_municipio = 'Mogi Guaçu' where cir_id = 29; 
UPDATE circunscricoes SET cir_municipio = 'Araraquara' where cir_id = 30; 
UPDATE circunscricoes SET cir_municipio = 'Ibitinga' where cir_id = 31; 
UPDATE circunscricoes SET cir_municipio = 'Itápolis' where cir_id = 32; 
UPDATE circunscricoes SET cir_municipio = 'Olímpia' where cir_id = 33; 
UPDATE circunscricoes SET cir_municipio = 'Taiaçu' where cir_id = 34; 
UPDATE circunscricoes SET cir_municipio = 'Cristais Paulista' where cir_id = 35; 
UPDATE circunscricoes SET cir_municipio = 'Ribeirão Preto' where cir_id = 36; 
UPDATE circunscricoes SET cir_municipio = 'Porto Ferreira' where cir_id = 37; 
UPDATE circunscricoes SET cir_municipio = 'São Carlos' where cir_id = 38; 
UPDATE circunscricoes SET cir_municipio = 'Guariba' where cir_id = 39; 
UPDATE circunscricoes SET cir_municipio = 'Sertãozinho' where cir_id = 40; 
UPDATE circunscricoes SET cir_municipio = 'Agudos' where cir_id = 41; 
UPDATE circunscricoes SET cir_municipio = 'Lins' where cir_id = 42; 
UPDATE circunscricoes SET cir_municipio = 'Lupércio' where cir_id = 43; 
UPDATE circunscricoes SET cir_municipio = 'Marília' where cir_id = 44; 
UPDATE circunscricoes SET cir_municipio = 'Mira Estrela' where cir_id = 45; 
UPDATE circunscricoes SET cir_municipio = 'Santa Albertina' where cir_id = 46; 
UPDATE circunscricoes SET cir_municipio = 'Urânia' where cir_id = 47; 
UPDATE circunscricoes SET cir_municipio = 'Icém' where cir_id = 48; 
UPDATE circunscricoes SET cir_municipio = 'São José do Rio Preto' where cir_id = 49; 
UPDATE circunscricoes SET cir_municipio = 'Tanabi' where cir_id = 50; 
UPDATE circunscricoes SET cir_municipio = 'Itanhaém' where cir_id = 51; 
UPDATE circunscricoes SET cir_municipio = 'Mongaguá' where cir_id = 52; 
UPDATE circunscricoes SET cir_municipio = 'Barra do Turvo' where cir_id = 53; 
UPDATE circunscricoes SET cir_municipio = 'Iguape' where cir_id = 54; 
UPDATE circunscricoes SET cir_municipio = 'Cubatão' where cir_id = 55; 
UPDATE circunscricoes SET cir_municipio = 'Guarujá' where cir_id = 56; 
UPDATE circunscricoes SET cir_municipio = 'Praia Grande' where cir_id = 57; 
UPDATE circunscricoes SET cir_municipio = 'Santos' where cir_id = 58; 
UPDATE circunscricoes SET cir_municipio = 'São Vicente' where cir_id = 59; 
UPDATE circunscricoes SET cir_municipio = 'Iaras' where cir_id = 60; 
UPDATE circunscricoes SET cir_municipio = 'Porangaba' where cir_id = 61; 
UPDATE circunscricoes SET cir_municipio = 'Itapetininga' where cir_id = 62; 
UPDATE circunscricoes SET cir_municipio = 'Tatuí' where cir_id = 63; 
UPDATE circunscricoes SET cir_municipio = 'Capão Bonito' where cir_id = 64; 
UPDATE circunscricoes SET cir_municipio = 'Itu' where cir_id = 65; 
UPDATE circunscricoes SET cir_municipio = 'São Roque' where cir_id = 66; 
UPDATE circunscricoes SET cir_municipio = 'Sorocaba' where cir_id = 67; 
UPDATE circunscricoes SET cir_municipio = 'Votorantim' where cir_id = 68; 
UPDATE circunscricoes SET cir_municipio = 'Paraguaçu Paulista' where cir_id = 69; 
UPDATE circunscricoes SET cir_municipio = 'Presidente Prudente' where cir_id = 70; 
UPDATE circunscricoes SET cir_municipio = 'Cosmópolis' where cir_id = 71; 
UPDATE circunscricoes SET cir_municipio = 'Engenheiro Coelho' where cir_id = 72; 
UPDATE circunscricoes SET cir_municipio = 'Hortolândia' where cir_id = 73; 
UPDATE circunscricoes SET cir_municipio = 'Monte Mor' where cir_id = 74; 
UPDATE circunscricoes SET cir_municipio = 'Santa Bárbara DOeste' where cir_id = 75; 
UPDATE circunscricoes SET cir_municipio = 'Sumaré' where cir_id = 76; 
UPDATE circunscricoes SET cir_municipio = 'Leme' where cir_id = 77; 
UPDATE circunscricoes SET cir_municipio = 'Pirassununga' where cir_id = 78; 
UPDATE circunscricoes SET cir_municipio = 'Piracicaba' where cir_id = 79; 
UPDATE circunscricoes SET cir_municipio = 'Rio Claro' where cir_id = 80; 
UPDATE circunscricoes SET cir_municipio = 'Espírito Santo do Pinhal' where cir_id = 81; 
UPDATE circunscricoes SET cir_municipio = 'Carapicuíba' where cir_id = 82; 
UPDATE circunscricoes SET cir_municipio = 'Cotia' where cir_id = 83; 
UPDATE circunscricoes SET cir_municipio = 'Itapevi' where cir_id = 84; 
UPDATE circunscricoes SET cir_municipio = 'Jandira' where cir_id = 85; 
UPDATE circunscricoes SET cir_municipio = 'Pirapora do Bom Jesus' where cir_id = 86; 
UPDATE circunscricoes SET cir_municipio = 'Santana de Parnaíba' where cir_id = 87; 
UPDATE circunscricoes SET cir_municipio = 'Diadema' where cir_id = 88; 
UPDATE circunscricoes SET cir_municipio = 'Caieiras' where cir_id = 89; 
UPDATE circunscricoes SET cir_municipio = 'Cajamar' where cir_id = 90; 
UPDATE circunscricoes SET cir_municipio = 'Francisco Morato' where cir_id = 91; 
UPDATE circunscricoes SET cir_municipio = 'Mairiporã' where cir_id = 92; 
UPDATE circunscricoes SET cir_municipio = 'Arujá' where cir_id = 93; 
UPDATE circunscricoes SET cir_municipio = 'Guarulhos' where cir_id = 94; 
UPDATE circunscricoes SET cir_municipio = 'Santa Isabel' where cir_id = 95; 
UPDATE circunscricoes SET cir_municipio = 'Ferraz de Vasconcelos' where cir_id = 96; 
UPDATE circunscricoes SET cir_municipio = 'Itaquaquecetuba' where cir_id = 97; 
UPDATE circunscricoes SET cir_municipio = 'Mogi das Cruzes' where cir_id = 98; 
UPDATE circunscricoes SET cir_municipio = 'Poá' where cir_id = 99; 
UPDATE circunscricoes SET cir_municipio = 'Suzano' where cir_id = 100; 
UPDATE circunscricoes SET cir_municipio = 'Osasco' where cir_id = 101; 
UPDATE circunscricoes SET cir_municipio = 'Mauá' where cir_id = 102; 
UPDATE circunscricoes SET cir_municipio = 'Ribeirão Pires' where cir_id = 103; 
UPDATE circunscricoes SET cir_municipio = 'Santo André' where cir_id = 104; 
UPDATE circunscricoes SET cir_municipio = 'São Bernardo do Campo' where cir_id = 105; 
UPDATE circunscricoes SET cir_municipio = 'Embu das Artes' where cir_id = 106; 
UPDATE circunscricoes SET cir_municipio = 'Embu-Guaçu' where cir_id = 107; 
UPDATE circunscricoes SET cir_municipio = 'Itapecerica da Serra' where cir_id = 108; 
UPDATE circunscricoes SET cir_municipio = 'Taboão da Serra' where cir_id = 109; 
UPDATE circunscricoes SET cir_municipio = 'Caçapava' where cir_id = 110; 
UPDATE circunscricoes SET cir_municipio = 'São Bento do Sapucaí' where cir_id = 111; 
UPDATE circunscricoes SET cir_municipio = 'Tremembé' where cir_id = 112; 
UPDATE circunscricoes SET cir_municipio = 'Guararapes' where cir_id = 113; 
UPDATE circunscricoes SET cir_municipio = 'Piracaia' where cir_id = 114; 
UPDATE circunscricoes SET cir_municipio = 'Itatiba' where cir_id = 115; 
UPDATE circunscricoes SET cir_municipio = 'Mogi Mirim' where cir_id = 116; 
UPDATE circunscricoes SET cir_municipio = 'Matão' where cir_id = 117; 
UPDATE circunscricoes SET cir_municipio = 'Rincão' where cir_id = 118; 
UPDATE circunscricoes SET cir_municipio = 'Cajobi' where cir_id = 119; 
UPDATE circunscricoes SET cir_municipio = 'Guaíra' where cir_id = 120; 
UPDATE circunscricoes SET cir_municipio = 'Batatais' where cir_id = 121; 
UPDATE circunscricoes SET cir_municipio = 'Franca' where cir_id = 122; 
UPDATE circunscricoes SET cir_municipio = 'Restinga' where cir_id = 123; 
UPDATE circunscricoes SET cir_municipio = 'Cravinhos' where cir_id = 124; 
UPDATE circunscricoes SET cir_municipio = 'Morro Agudo' where cir_id = 125; 
UPDATE circunscricoes SET cir_municipio = 'Pitangueiras' where cir_id = 126; 
UPDATE circunscricoes SET cir_municipio = 'Bauru' where cir_id = 127; 
UPDATE circunscricoes SET cir_municipio = 'Lençóis Paulista' where cir_id = 128; 
UPDATE circunscricoes SET cir_municipio = 'Pederneiras' where cir_id = 129; 
UPDATE circunscricoes SET cir_municipio = 'Jaú' where cir_id = 130; 
UPDATE circunscricoes SET cir_municipio = 'Getulina' where cir_id = 131; 
UPDATE circunscricoes SET cir_municipio = 'Ipaussu' where cir_id = 132; 
UPDATE circunscricoes SET cir_municipio = 'Ourinhos' where cir_id = 133; 
UPDATE circunscricoes SET cir_municipio = 'Santa Cruz do Rio Pardo' where cir_id = 134; 
UPDATE circunscricoes SET cir_municipio = 'Catanduva' where cir_id = 135; 
UPDATE circunscricoes SET cir_municipio = 'Valentim Gentil' where cir_id = 136; 
UPDATE circunscricoes SET cir_municipio = 'Votuporanga' where cir_id = 137; 
UPDATE circunscricoes SET cir_municipio = 'Itaporanga' where cir_id = 138; 
UPDATE circunscricoes SET cir_municipio = 'Sarutaiá' where cir_id = 139; 
UPDATE circunscricoes SET cir_municipio = 'Botucatu' where cir_id = 140; 
UPDATE circunscricoes SET cir_municipio = 'Pardinho' where cir_id = 141; 
UPDATE circunscricoes SET cir_municipio = 'Ribeira' where cir_id = 142; 
UPDATE circunscricoes SET cir_municipio = 'Ibiúna' where cir_id = 143; 
UPDATE circunscricoes SET cir_municipio = 'Mairinque' where cir_id = 144; 
UPDATE circunscricoes SET cir_municipio = 'Salto' where cir_id = 145; 
UPDATE circunscricoes SET cir_municipio = 'Junqueirópolis' where cir_id = 146; 
UPDATE circunscricoes SET cir_municipio = 'Tupi Paulista' where cir_id = 147; 
UPDATE circunscricoes SET cir_municipio = 'Rosana' where cir_id = 148; 
UPDATE circunscricoes SET cir_municipio = 'Santo Anastácio' where cir_id = 149; 
UPDATE circunscricoes SET cir_municipio = 'Americana' where cir_id = 150; 
UPDATE circunscricoes SET cir_municipio = 'Nova Odessa' where cir_id = 151; 
UPDATE circunscricoes SET cir_municipio = 'Casa Branca' where cir_id = 152; 
UPDATE circunscricoes SET cir_municipio = 'Tapiratiba' where cir_id = 153; 
UPDATE circunscricoes SET cir_municipio = 'Cordeirópolis' where cir_id = 154; 
UPDATE circunscricoes SET cir_municipio = 'Limeira' where cir_id = 155; 
UPDATE circunscricoes SET cir_municipio = 'Santa Gertrudes' where cir_id = 156; 
UPDATE circunscricoes SET cir_municipio = 'Vargem Grande Paulista' where cir_id = 157; 
UPDATE circunscricoes SET cir_municipio = 'Queluz' where cir_id = 158; 
UPDATE circunscricoes SET cir_municipio = 'Lavínia' where cir_id = 159; 
UPDATE circunscricoes SET cir_municipio = 'Birigui' where cir_id = 160; 
UPDATE circunscricoes SET cir_municipio = 'Bebedouro' where cir_id = 161; 
UPDATE circunscricoes SET cir_municipio = 'Miguelópolis' where cir_id = 162; 
UPDATE circunscricoes SET cir_municipio = 'Patrocínio Paulista' where cir_id = 163; 
UPDATE circunscricoes SET cir_municipio = 'Jardinópolis' where cir_id = 164; 
UPDATE circunscricoes SET cir_municipio = 'Ibaté' where cir_id = 165; 
UPDATE circunscricoes SET cir_municipio = 'Jaboticabal' where cir_id = 166; 
UPDATE circunscricoes SET cir_municipio = 'Cabrália Paulista' where cir_id = 167; 
UPDATE circunscricoes SET cir_municipio = 'Macatuba' where cir_id = 168; 
UPDATE circunscricoes SET cir_municipio = 'Igaraçu do Tietê' where cir_id = 169; 
UPDATE circunscricoes SET cir_municipio = 'Guaiçara' where cir_id = 170; 
UPDATE circunscricoes SET cir_municipio = 'Guaimbê' where cir_id = 171; 
UPDATE circunscricoes SET cir_municipio = 'Parapuã' where cir_id = 172; 
UPDATE circunscricoes SET cir_municipio = 'José Bonifácio' where cir_id = 173; 
UPDATE circunscricoes SET cir_municipio = 'Sebastianópolis do Sul' where cir_id = 174; 
UPDATE circunscricoes SET cir_municipio = 'Peruíbe' where cir_id = 175; 
UPDATE circunscricoes SET cir_municipio = 'Sete Barras' where cir_id = 176; 
UPDATE circunscricoes SET cir_municipio = 'Bertioga' where cir_id = 177; 
UPDATE circunscricoes SET cir_municipio = 'Itaí' where cir_id = 178; 
UPDATE circunscricoes SET cir_municipio = 'Bofete' where cir_id = 179; 
UPDATE circunscricoes SET cir_municipio = 'Itatinga' where cir_id = 180; 
UPDATE circunscricoes SET cir_municipio = 'Boituva' where cir_id = 181; 
UPDATE circunscricoes SET cir_municipio = 'Buri' where cir_id = 182; 
UPDATE circunscricoes SET cir_municipio = 'Salto de Pirapora' where cir_id = 183; 
UPDATE circunscricoes SET cir_municipio = 'Assis' where cir_id = 184; 
UPDATE circunscricoes SET cir_municipio = 'Pirapozinho' where cir_id = 185; 
UPDATE circunscricoes SET cir_municipio = 'Regente Feijó' where cir_id = 186; 
UPDATE circunscricoes SET cir_municipio = 'Presidente Epitácio' where cir_id = 187; 
UPDATE circunscricoes SET cir_municipio = 'Presidente Venceslau' where cir_id = 188; 
UPDATE circunscricoes SET cir_municipio = 'Artur Nogueira' where cir_id = 189; 
UPDATE circunscricoes SET cir_municipio = 'Itobi' where cir_id = 190; 
UPDATE circunscricoes SET cir_municipio = 'Charqueada' where cir_id = 191; 
UPDATE circunscricoes SET cir_municipio = 'São Sebastião da Grama' where cir_id = 192; 
UPDATE circunscricoes SET cir_municipio = 'Barueri' where cir_id = 193; 
UPDATE circunscricoes SET cir_municipio = 'Franco da Rocha' where cir_id = 194; 
UPDATE circunscricoes SET cir_municipio = 'São Lourenço da Serra' where cir_id = 195; 
UPDATE circunscricoes SET cir_municipio = 'Monteiro Lobato' where cir_id = 196; 
UPDATE circunscricoes SET cir_municipio = 'Andradina' where cir_id = 197; 
UPDATE circunscricoes SET cir_municipio = 'Ilha Solteira' where cir_id = 198; 
UPDATE circunscricoes SET cir_municipio = 'Buritama' where cir_id = 199; 
UPDATE circunscricoes SET cir_municipio = 'Penápolis' where cir_id = 200; 
UPDATE circunscricoes SET cir_municipio = 'Jaguariúna' where cir_id = 201; 
UPDATE circunscricoes SET cir_municipio = 'Tabatinga' where cir_id = 202; 
UPDATE circunscricoes SET cir_municipio = 'Vista Alegre do Alto' where cir_id = 203; 
UPDATE circunscricoes SET cir_municipio = 'Guará' where cir_id = 204; 
UPDATE circunscricoes SET cir_municipio = 'Monte Alto' where cir_id = 205; 
UPDATE circunscricoes SET cir_municipio = 'Iacanga' where cir_id = 206; 
UPDATE circunscricoes SET cir_municipio = 'Itaju' where cir_id = 207; 
UPDATE circunscricoes SET cir_municipio = 'Promissão' where cir_id = 208; 
UPDATE circunscricoes SET cir_municipio = 'Alvinlândia' where cir_id = 209; 
UPDATE circunscricoes SET cir_municipio = 'Palmares Paulista' where cir_id = 210; 
UPDATE circunscricoes SET cir_municipio = 'Tabapuã' where cir_id = 211; 
UPDATE circunscricoes SET cir_municipio = 'Urupês' where cir_id = 212; 
UPDATE circunscricoes SET cir_municipio = 'Américo de Campos' where cir_id = 213; 
UPDATE circunscricoes SET cir_municipio = 'Miracatu' where cir_id = 214; 
UPDATE circunscricoes SET cir_municipio = 'Avaré' where cir_id = 215; 
UPDATE circunscricoes SET cir_municipio = 'Piraju' where cir_id = 216; 
UPDATE circunscricoes SET cir_municipio = 'Araçoiaba da Serra' where cir_id = 217; 
UPDATE circunscricoes SET cir_municipio = 'Porto Feliz' where cir_id = 218; 
UPDATE circunscricoes SET cir_municipio = 'Tietê' where cir_id = 219; 
UPDATE circunscricoes SET cir_municipio = 'Adamantina' where cir_id = 220; 
UPDATE circunscricoes SET cir_municipio = 'Flórida Paulista' where cir_id = 221; 
UPDATE circunscricoes SET cir_municipio = 'Teodoro Sampaio' where cir_id = 222; 
UPDATE circunscricoes SET cir_municipio = 'Santa Cruz das Palmeiras' where cir_id = 223; 
UPDATE circunscricoes SET cir_municipio = 'São Pedro' where cir_id = 224; 
UPDATE circunscricoes SET cir_municipio = 'Biritiba Mirim' where cir_id = 225; 
UPDATE circunscricoes SET cir_municipio = 'Ilhabela' where cir_id = 226; 
UPDATE circunscricoes SET cir_municipio = 'Paulínia' where cir_id = 227; 
UPDATE circunscricoes SET cir_municipio = 'Valinhos' where cir_id = 228; 
UPDATE circunscricoes SET cir_municipio = 'Águas de Lindóia' where cir_id = 229; 
UPDATE circunscricoes SET cir_municipio = 'Américo Brasiliense' where cir_id = 230; 
UPDATE circunscricoes SET cir_municipio = 'Ituverava' where cir_id = 231; 
UPDATE circunscricoes SET cir_municipio = 'Orlândia' where cir_id = 232; 
UPDATE circunscricoes SET cir_municipio = 'Pontal' where cir_id = 233; 
UPDATE circunscricoes SET cir_municipio = 'Balbinos' where cir_id = 234; 
UPDATE circunscricoes SET cir_municipio = 'Sabino' where cir_id = 235; 
UPDATE circunscricoes SET cir_municipio = 'Ocauçu' where cir_id = 236; 
UPDATE circunscricoes SET cir_municipio = 'Jales' where cir_id = 237; 
UPDATE circunscricoes SET cir_municipio = 'Mirassol' where cir_id = 238; 
UPDATE circunscricoes SET cir_municipio = 'Coronel Macedo' where cir_id = 239; 
UPDATE circunscricoes SET cir_municipio = 'Fartura' where cir_id = 240; 
UPDATE circunscricoes SET cir_municipio = 'Anhembi' where cir_id = 241; 
UPDATE circunscricoes SET cir_municipio = 'Araçariguama' where cir_id = 242; 
UPDATE circunscricoes SET cir_municipio = 'Palmital' where cir_id = 243; 
UPDATE circunscricoes SET cir_municipio = 'Álvares Machado' where cir_id = 244; 
UPDATE circunscricoes SET cir_municipio = 'Araras' where cir_id = 245; 
UPDATE circunscricoes SET cir_municipio = 'Conchal' where cir_id = 246; 
UPDATE circunscricoes SET cir_municipio = 'Rio Grande da Serra' where cir_id = 247; 
UPDATE circunscricoes SET cir_municipio = 'Cachoeira Paulista' where cir_id = 248; 
UPDATE circunscricoes SET cir_municipio = 'Castilho' where cir_id = 249; 
UPDATE circunscricoes SET cir_municipio = 'Nazaré Paulista' where cir_id = 250; 
UPDATE circunscricoes SET cir_municipio = 'Socorro' where cir_id = 251; 
UPDATE circunscricoes SET cir_municipio = 'Jarinu' where cir_id = 252; 
UPDATE circunscricoes SET cir_municipio = 'Santo Antônio de Posse' where cir_id = 253; 
UPDATE circunscricoes SET cir_municipio = 'Colina' where cir_id = 254; 
UPDATE circunscricoes SET cir_municipio = 'Pirangi' where cir_id = 255; 
UPDATE circunscricoes SET cir_municipio = 'São Simão' where cir_id = 256; 
UPDATE circunscricoes SET cir_municipio = 'Serrana' where cir_id = 257; 
UPDATE circunscricoes SET cir_municipio = 'Santa Rita do Passa Quatro' where cir_id = 258; 
UPDATE circunscricoes SET cir_municipio = 'Pindorama' where cir_id = 259; 
UPDATE circunscricoes SET cir_municipio = 'Monte Aprazível' where cir_id = 260; 
UPDATE circunscricoes SET cir_municipio = 'Itariri' where cir_id = 261; 
UPDATE circunscricoes SET cir_municipio = 'Cesário Lange' where cir_id = 262; 
UPDATE circunscricoes SET cir_municipio = 'São Miguel Arcanjo' where cir_id = 263; 
UPDATE circunscricoes SET cir_municipio = 'Apiaí' where cir_id = 264; 
UPDATE circunscricoes SET cir_municipio = 'Itararé' where cir_id = 265; 
UPDATE circunscricoes SET cir_municipio = 'Tarumã' where cir_id = 266; 
UPDATE circunscricoes SET cir_municipio = 'Panorama' where cir_id = 267; 
UPDATE circunscricoes SET cir_municipio = 'Brotas' where cir_id = 268; 
UPDATE circunscricoes SET cir_municipio = 'Corumbataí' where cir_id = 269; 
UPDATE circunscricoes SET cir_municipio = 'Aguaí' where cir_id = 270; 
UPDATE circunscricoes SET cir_municipio = 'Juquitiba' where cir_id = 271; 
UPDATE circunscricoes SET cir_municipio = 'Paraibuna' where cir_id = 272; 
UPDATE circunscricoes SET cir_municipio = 'Santa Branca' where cir_id = 273; 
UPDATE circunscricoes SET cir_municipio = 'Amparo' where cir_id = 274; 
UPDATE circunscricoes SET cir_municipio = 'Louveira' where cir_id = 275; 
UPDATE circunscricoes SET cir_municipio = 'Morungaba' where cir_id = 276; 
UPDATE circunscricoes SET cir_municipio = 'Dobrada' where cir_id = 277; 
UPDATE circunscricoes SET cir_municipio = 'Gavião Peixoto' where cir_id = 278; 
UPDATE circunscricoes SET cir_municipio = 'Barra Bonita' where cir_id = 279; 
UPDATE circunscricoes SET cir_municipio = 'Dois Córregos' where cir_id = 280; 
UPDATE circunscricoes SET cir_municipio = 'Canitar' where cir_id = 281; 
UPDATE circunscricoes SET cir_municipio = 'Populina' where cir_id = 282; 
UPDATE circunscricoes SET cir_municipio = 'Paulo de Faria' where cir_id = 283; 
UPDATE circunscricoes SET cir_municipio = 'Registro' where cir_id = 284; 
UPDATE circunscricoes SET cir_municipio = 'Campina do Monte Alegre' where cir_id = 285; 
UPDATE circunscricoes SET cir_municipio = 'Piedade' where cir_id = 286; 
UPDATE circunscricoes SET cir_municipio = 'Santo Antonio do Aracanguá' where cir_id = 287; 
UPDATE circunscricoes SET cir_municipio = 'Cabreúva' where cir_id = 288; 
UPDATE circunscricoes SET cir_municipio = 'Borborema' where cir_id = 289; 
UPDATE circunscricoes SET cir_municipio = 'Santa Lucia' where cir_id = 290; 
UPDATE circunscricoes SET cir_municipio = 'Barretos' where cir_id = 291; 
UPDATE circunscricoes SET cir_municipio = 'Buritizal' where cir_id = 292; 
UPDATE circunscricoes SET cir_municipio = 'Garça' where cir_id = 293; 
UPDATE circunscricoes SET cir_municipio = 'Tupã' where cir_id = 294; 
UPDATE circunscricoes SET cir_municipio = 'Bady Bassitt' where cir_id = 295; 
UPDATE circunscricoes SET cir_municipio = 'União Paulista' where cir_id = 296; 
UPDATE circunscricoes SET cir_municipio = 'Juquiá' where cir_id = 297; 
UPDATE circunscricoes SET cir_municipio = 'Iperó' where cir_id = 298; 
UPDATE circunscricoes SET cir_municipio = 'Ibirarema' where cir_id = 299; 
UPDATE circunscricoes SET cir_municipio = 'Vargem Grande do Sul' where cir_id = 300; 
UPDATE circunscricoes SET cir_municipio = 'Roseira' where cir_id = 301; 
UPDATE circunscricoes SET cir_municipio = 'Igaratá' where cir_id = 302; 
UPDATE circunscricoes SET cir_municipio = 'Natividade da Serra' where cir_id = 303; 
UPDATE circunscricoes SET cir_municipio = 'Avanhandava' where cir_id = 304; 
UPDATE circunscricoes SET cir_municipio = 'Pradópolis' where cir_id = 305; 
UPDATE circunscricoes SET cir_municipio = 'Arealva' where cir_id = 306; 
UPDATE circunscricoes SET cir_municipio = 'Reginópolis' where cir_id = 307; 
UPDATE circunscricoes SET cir_municipio = 'Estrela DOeste' where cir_id = 308; 
UPDATE circunscricoes SET cir_municipio = 'São João das Duas Pontes' where cir_id = 309; 
UPDATE circunscricoes SET cir_municipio = 'Novo Horizonte' where cir_id = 310; 
UPDATE circunscricoes SET cir_municipio = 'Itaberá' where cir_id = 311; 
UPDATE circunscricoes SET cir_municipio = 'Nova Campina' where cir_id = 312; 
UPDATE circunscricoes SET cir_municipio = 'Capivari' where cir_id = 313; 
UPDATE circunscricoes SET cir_municipio = 'Itirapina' where cir_id = 314; 
UPDATE circunscricoes SET cir_municipio = 'Guararema' where cir_id = 315; 
UPDATE circunscricoes SET cir_municipio = 'Auriflama' where cir_id = 316; 
UPDATE circunscricoes SET cir_municipio = 'Lindóia' where cir_id = 317; 
UPDATE circunscricoes SET cir_municipio = 'Itupeva' where cir_id = 318; 
UPDATE circunscricoes SET cir_municipio = 'Cafelândia' where cir_id = 319; 
UPDATE circunscricoes SET cir_municipio = 'Echaporã' where cir_id = 320; 
UPDATE circunscricoes SET cir_municipio = 'Santa Fé do Sul' where cir_id = 321; 
UPDATE circunscricoes SET cir_municipio = 'Onda Verde' where cir_id = 322; 
UPDATE circunscricoes SET cir_municipio = 'Potirendaba' where cir_id = 323; 
UPDATE circunscricoes SET cir_municipio = 'Guareí' where cir_id = 324; 
UPDATE circunscricoes SET cir_municipio = 'São João da Boa Vista' where cir_id = 325; 
UPDATE circunscricoes SET cir_municipio = 'Cunha' where cir_id = 326; 
UPDATE circunscricoes SET cir_municipio = 'Itapura' where cir_id = 327; 
UPDATE circunscricoes SET cir_municipio = 'Vargem' where cir_id = 328; 
UPDATE circunscricoes SET cir_municipio = 'Altair' where cir_id = 329; 
UPDATE circunscricoes SET cir_municipio = 'Santa Rosa do Viterbo' where cir_id = 330; 
UPDATE circunscricoes SET cir_municipio = 'São Joaquim da Barra' where cir_id = 331; 
UPDATE circunscricoes SET cir_municipio = 'Bocaina' where cir_id = 332; 
UPDATE circunscricoes SET cir_municipio = 'Taquarituba' where cir_id = 333; 
UPDATE circunscricoes SET cir_municipio = 'Santa Mercedes' where cir_id = 334; 
UPDATE circunscricoes SET cir_municipio = 'Salesópolis' where cir_id = 335; 
UPDATE circunscricoes SET cir_municipio = 'Colômbia' where cir_id = 336; 
UPDATE circunscricoes SET cir_municipio = 'Severínia' where cir_id = 337; 
UPDATE circunscricoes SET cir_municipio = 'Igarapava' where cir_id = 338; 
UPDATE circunscricoes SET cir_municipio = 'Barrinha' where cir_id = 339; 
UPDATE circunscricoes SET cir_municipio = 'Vera Cruz' where cir_id = 340; 
UPDATE circunscricoes SET cir_municipio = 'Ribeirão do Sul' where cir_id = 341; 
UPDATE circunscricoes SET cir_municipio = 'Ouroeste' where cir_id = 342; 
UPDATE circunscricoes SET cir_municipio = 'Sales' where cir_id = 343; 
UPDATE circunscricoes SET cir_municipio = 'Pontes Gestal' where cir_id = 344; 
UPDATE circunscricoes SET cir_municipio = 'Cananéia' where cir_id = 345; 
UPDATE circunscricoes SET cir_municipio = 'Areiópolis' where cir_id = 346; 
UPDATE circunscricoes SET cir_municipio = 'Itapeva' where cir_id = 347; 
UPDATE circunscricoes SET cir_municipio = 'Ribeirão Grande' where cir_id = 348; 
UPDATE circunscricoes SET cir_municipio = 'Mirante do Paranapanema' where cir_id = 349; 
UPDATE circunscricoes SET cir_municipio = 'Iracemápolis' where cir_id = 350; 
