INSERT INTO circunscricoes values (1, 'São Paulo'); 
INSERT INTO circunscricoes values (2, 'Cruzeiro'); 
INSERT INTO circunscricoes values (3, 'Cunha'); 
INSERT INTO circunscricoes values (4, 'Lorena'); 
INSERT INTO circunscricoes values (5, 'Piquete'); 
INSERT INTO circunscricoes values (6, 'Jacareí'); 
INSERT INTO circunscricoes values (7, 'Caçapava'); 
INSERT INTO circunscricoes values (8, 'São José dos Campos'); 
INSERT INTO circunscricoes values (9, 'Caraguatatuba'); 
INSERT INTO circunscricoes values (10, 'Ubatuba'); 
INSERT INTO circunscricoes values (11, 'Campos do Jordão'); 
INSERT INTO circunscricoes values (12, 'Natividade da Serra'); 
INSERT INTO circunscricoes values (13, 'Pindamonhangaba'); 
INSERT INTO circunscricoes values (14, 'Taubaté'); 
INSERT INTO circunscricoes values (15, 'Tremembé'); 
INSERT INTO circunscricoes values (16, 'Araçatuba'); 
INSERT INTO circunscricoes values (17, 'Guararapes'); 
INSERT INTO circunscricoes values (18, 'Luiziânia'); 
INSERT INTO circunscricoes values (19, 'Campinas'); 
INSERT INTO circunscricoes values (20, 'Vinhedo'); 
INSERT INTO circunscricoes values (21, 'Águas de Lindóia'); 
INSERT INTO circunscricoes values (22, 'Atibaia'); 
INSERT INTO circunscricoes values (23, 'Jundiaí'); 
INSERT INTO circunscricoes values (24, 'Itapira'); 
INSERT INTO circunscricoes values (25, 'Mogi Guaçu'); 
INSERT INTO circunscricoes values (26, 'Santo Antônio de Posse'); 
INSERT INTO circunscricoes values (27, 'Araraquara'); 
INSERT INTO circunscricoes values (28, 'Matão'); 
INSERT INTO circunscricoes values (29, 'Barretos'); 
INSERT INTO circunscricoes values (30, 'Colômbia'); 
INSERT INTO circunscricoes values (31, 'Bebedouro'); 
INSERT INTO circunscricoes values (32, 'Monte Azul Paulista'); 
INSERT INTO circunscricoes values (33, 'Franca'); 
INSERT INTO circunscricoes values (34, 'Guará'); 
INSERT INTO circunscricoes values (35, 'Altinópolis'); 
INSERT INTO circunscricoes values (36, 'Cravinhos'); 
INSERT INTO circunscricoes values (37, 'Ribeirão Preto'); 
INSERT INTO circunscricoes values (38, 'Descalvado'); 
INSERT INTO circunscricoes values (39, 'Ibaté'); 
INSERT INTO circunscricoes values (40, 'Porto Ferreira'); 
INSERT INTO circunscricoes values (41, 'São Carlos'); 
INSERT INTO circunscricoes values (42, 'Pontal'); 
INSERT INTO circunscricoes values (43, 'Pradópolis'); 
INSERT INTO circunscricoes values (44, 'Sertãozinho'); 
INSERT INTO circunscricoes values (45, 'Bauru'); 
INSERT INTO circunscricoes values (46, 'Lençóis Paulista'); 
INSERT INTO circunscricoes values (47, 'Marília'); 
INSERT INTO circunscricoes values (48, 'Catanduva'); 
INSERT INTO circunscricoes values (49, 'Adolfo'); 
INSERT INTO circunscricoes values (50, 'Bálsamo'); 
INSERT INTO circunscricoes values (51, 'Mirassol'); 
INSERT INTO circunscricoes values (52, 'São José do Rio Preto'); 
INSERT INTO circunscricoes values (53, 'Tanabi'); 
INSERT INTO circunscricoes values (54, 'Votuporanga'); 
INSERT INTO circunscricoes values (55, 'Itariri'); 
INSERT INTO circunscricoes values (56, 'Cajati'); 
INSERT INTO circunscricoes values (57, 'Iguape'); 
INSERT INTO circunscricoes values (58, 'Miracatu'); 
INSERT INTO circunscricoes values (59, 'Guarujá'); 
INSERT INTO circunscricoes values (60, 'Praia Grande'); 
INSERT INTO circunscricoes values (61, 'Santos'); 
INSERT INTO circunscricoes values (62, 'São Vicente'); 
INSERT INTO circunscricoes values (63, 'Itaí'); 
INSERT INTO circunscricoes values (64, 'Piraju'); 
INSERT INTO circunscricoes values (65, 'Boituva'); 
INSERT INTO circunscricoes values (66, 'Apiaí'); 
INSERT INTO circunscricoes values (67, 'Araçariguama'); 
INSERT INTO circunscricoes values (68, 'Araçoiaba da Serra'); 
INSERT INTO circunscricoes values (69, 'Iperó'); 
INSERT INTO circunscricoes values (70, 'Itu'); 
INSERT INTO circunscricoes values (71, 'Salto de Pirapora'); 
INSERT INTO circunscricoes values (72, 'Sorocaba'); 
INSERT INTO circunscricoes values (73, 'Assis'); 
INSERT INTO circunscricoes values (74, 'Tupi Paulista'); 
INSERT INTO circunscricoes values (75, 'Presidente Prudente'); 
INSERT INTO circunscricoes values (76, 'Caiuá'); 
INSERT INTO circunscricoes values (77, 'Piquerobi'); 
INSERT INTO circunscricoes values (78, 'Americana'); 
INSERT INTO circunscricoes values (79, 'Cosmópolis'); 
INSERT INTO circunscricoes values (80, 'Hortolândia'); 
INSERT INTO circunscricoes values (81, 'Sumaré'); 
INSERT INTO circunscricoes values (82, 'Araras'); 
INSERT INTO circunscricoes values (83, 'Limeira'); 
INSERT INTO circunscricoes values (84, 'Rio Claro'); 
INSERT INTO circunscricoes values (85, 'Santa Gertrudes'); 
INSERT INTO circunscricoes values (86, 'Barueri'); 
INSERT INTO circunscricoes values (87, 'Carapicuíba'); 
INSERT INTO circunscricoes values (88, 'Cotia'); 
INSERT INTO circunscricoes values (89, 'Itapevi'); 
INSERT INTO circunscricoes values (90, 'Diadema'); 
INSERT INTO circunscricoes values (91, 'Francisco Morato'); 
INSERT INTO circunscricoes values (92, 'Franco da Rocha'); 
INSERT INTO circunscricoes values (93, 'Guarulhos'); 
INSERT INTO circunscricoes values (94, 'Santa Isabel'); 
INSERT INTO circunscricoes values (95, 'Itaquaquecetuba'); 
INSERT INTO circunscricoes values (96, 'Mogi das Cruzes'); 
INSERT INTO circunscricoes values (97, 'Suzano'); 
INSERT INTO circunscricoes values (98, 'Osasco'); 
INSERT INTO circunscricoes values (99, 'Mauá'); 
INSERT INTO circunscricoes values (100, 'Ribeirão Pires'); 
INSERT INTO circunscricoes values (101, 'Santo André'); 
INSERT INTO circunscricoes values (102, 'São Bernardo do Campo'); 
INSERT INTO circunscricoes values (103, 'São Caetano do Sul'); 
INSERT INTO circunscricoes values (104, 'Embu das Artes'); 
INSERT INTO circunscricoes values (105, 'Embu-Guaçu'); 
INSERT INTO circunscricoes values (106, 'Itapecerica da Serra'); 
INSERT INTO circunscricoes values (107, 'Taboão da Serra'); 
INSERT INTO circunscricoes values (108, 'Guaratinguetá'); 
INSERT INTO circunscricoes values (109, 'Igaratá'); 
INSERT INTO circunscricoes values (110, 'Pereira Barreto'); 
INSERT INTO circunscricoes values (111, 'Birigui'); 
INSERT INTO circunscricoes values (112, 'Brejo Alegre'); 
INSERT INTO circunscricoes values (113, 'Piacatu'); 
INSERT INTO circunscricoes values (114, 'Paulínia'); 
INSERT INTO circunscricoes values (115, 'Bragança Paulista'); 
INSERT INTO circunscricoes values (116, 'Campo Limpo Paulista'); 
INSERT INTO circunscricoes values (117, 'Itupeva'); 
INSERT INTO circunscricoes values (118, 'Jarinu'); 
INSERT INTO circunscricoes values (119, 'Tabatinga'); 
INSERT INTO circunscricoes values (120, 'Pirangi'); 
INSERT INTO circunscricoes values (121, 'Taiaçu'); 
INSERT INTO circunscricoes values (122, 'Jeriquara'); 
INSERT INTO circunscricoes values (123, 'Monte Alto'); 
INSERT INTO circunscricoes values (124, 'Pederneiras'); 
INSERT INTO circunscricoes values (125, 'Igaraçu do Tietê'); 
INSERT INTO circunscricoes values (126, 'Jaú'); 
INSERT INTO circunscricoes values (127, 'Lins'); 
INSERT INTO circunscricoes values (128, 'Sabino'); 
INSERT INTO circunscricoes values (129, 'Espírito Santo do Turvo'); 
INSERT INTO circunscricoes values (130, 'Bastos'); 
INSERT INTO circunscricoes values (131, 'Urupês'); 
INSERT INTO circunscricoes values (132, 'Zacarias'); 
INSERT INTO circunscricoes values (133, 'Itanhaém'); 
INSERT INTO circunscricoes values (134, 'Iporanga'); 
INSERT INTO circunscricoes values (135, 'Jacupiranga'); 
INSERT INTO circunscricoes values (136, 'Bertioga'); 
INSERT INTO circunscricoes values (137, 'Cubatão'); 
INSERT INTO circunscricoes values (138, 'Avaré'); 
INSERT INTO circunscricoes values (139, 'Iaras'); 
INSERT INTO circunscricoes values (140, 'Botucatu'); 
INSERT INTO circunscricoes values (141, 'Itatinga'); 
INSERT INTO circunscricoes values (142, 'Itapetininga'); 
INSERT INTO circunscricoes values (143, 'Tatuí'); 
INSERT INTO circunscricoes values (144, 'Ibiúna'); 
INSERT INTO circunscricoes values (145, 'Pilar do Sul'); 
INSERT INTO circunscricoes values (146, 'Porto Feliz'); 
INSERT INTO circunscricoes values (147, 'Salto'); 
INSERT INTO circunscricoes values (148, 'Votorantim'); 
INSERT INTO circunscricoes values (149, 'Osvaldo Cruz'); 
INSERT INTO circunscricoes values (150, 'Regente Feijó'); 
INSERT INTO circunscricoes values (151, 'Mirante do Paranapanema'); 
INSERT INTO circunscricoes values (152, 'Monte Mor'); 
INSERT INTO circunscricoes values (153, 'Santa Bárbara DOeste'); 
INSERT INTO circunscricoes values (154, 'Torrinha'); 
INSERT INTO circunscricoes values (155, 'Aguaí'); 
INSERT INTO circunscricoes values (156, 'São João da Boa Vista'); 
INSERT INTO circunscricoes values (157, 'Jandira'); 
INSERT INTO circunscricoes values (158, 'Pirapora do Bom Jesus'); 
INSERT INTO circunscricoes values (159, 'Mairiporã'); 
INSERT INTO circunscricoes values (160, 'Arujá'); 
INSERT INTO circunscricoes values (161, 'Ferraz de Vasconcelos'); 
INSERT INTO circunscricoes values (162, 'Poá'); 
INSERT INTO circunscricoes values (163, 'Canas'); 
INSERT INTO circunscricoes values (164, 'Potim'); 
INSERT INTO circunscricoes values (165, 'Roseira'); 
INSERT INTO circunscricoes values (166, 'São Sebastião'); 
INSERT INTO circunscricoes values (167, 'Castilho'); 
INSERT INTO circunscricoes values (168, 'Sud Mennucci'); 
INSERT INTO circunscricoes values (169, 'Penápolis'); 
INSERT INTO circunscricoes values (170, 'Indaiatuba'); 
INSERT INTO circunscricoes values (171, 'Bom Jesus dos Perdões'); 
INSERT INTO circunscricoes values (172, 'Itatiba'); 
INSERT INTO circunscricoes values (173, 'Américo Brasiliense'); 
INSERT INTO circunscricoes values (174, 'Colina'); 
INSERT INTO circunscricoes values (175, 'Viradouro'); 
INSERT INTO circunscricoes values (176, 'Pedregulho'); 
INSERT INTO circunscricoes values (177, 'Rifaina'); 
INSERT INTO circunscricoes values (178, 'Barrinha'); 
INSERT INTO circunscricoes values (179, 'Jaboticabal'); 
INSERT INTO circunscricoes values (180, 'Bernardino de Campos'); 
INSERT INTO circunscricoes values (181, 'Salto Grande'); 
INSERT INTO circunscricoes values (182, 'Santa Fé do Sul'); 
INSERT INTO circunscricoes values (183, 'Bady Bassitt'); 
INSERT INTO circunscricoes values (184, 'Nipoã'); 
INSERT INTO circunscricoes values (185, 'Riolândia'); 
INSERT INTO circunscricoes values (186, 'Peruíbe'); 
INSERT INTO circunscricoes values (187, 'Capela do Alto'); 
INSERT INTO circunscricoes values (188, 'Sarapuí'); 
INSERT INTO circunscricoes values (189, 'Adamantina'); 
INSERT INTO circunscricoes values (190, 'Paraguaçu Paulista'); 
INSERT INTO circunscricoes values (191, 'Teodoro Sampaio'); 
INSERT INTO circunscricoes values (192, 'Casa Branca'); 
INSERT INTO circunscricoes values (193, 'Santa Cruz das Palmeiras'); 
INSERT INTO circunscricoes values (194, 'Leme'); 
INSERT INTO circunscricoes values (195, 'Piracicaba'); 
INSERT INTO circunscricoes values (196, 'São Pedro'); 
INSERT INTO circunscricoes values (197, 'Santana de Parnaíba'); 
INSERT INTO circunscricoes values (198, 'Vargem Grande Paulista'); 
INSERT INTO circunscricoes values (199, 'Juquitiba'); 
INSERT INTO circunscricoes values (200, 'Andradina'); 
INSERT INTO circunscricoes values (201, 'Valparaíso'); 
INSERT INTO circunscricoes values (202, 'Louveira'); 
INSERT INTO circunscricoes values (203, 'Itápolis'); 
INSERT INTO circunscricoes values (204, 'Batatais'); 
INSERT INTO circunscricoes values (205, 'Ituverava'); 
INSERT INTO circunscricoes values (206, 'Guariba'); 
INSERT INTO circunscricoes values (207, 'Agudos'); 
INSERT INTO circunscricoes values (208, 'Dois Córregos'); 
INSERT INTO circunscricoes values (209, 'Promissão'); 
INSERT INTO circunscricoes values (210, 'Tupã'); 
INSERT INTO circunscricoes values (211, 'Pindorama'); 
INSERT INTO circunscricoes values (212, 'Ouroeste'); 
INSERT INTO circunscricoes values (213, 'José Bonifácio'); 
INSERT INTO circunscricoes values (214, 'Registro'); 
INSERT INTO circunscricoes values (215, 'Pratânia'); 
INSERT INTO circunscricoes values (216, 'Angatuba'); 
INSERT INTO circunscricoes values (217, 'Guareí'); 
INSERT INTO circunscricoes values (218, 'Ribeirão Branco'); 
INSERT INTO circunscricoes values (219, 'Mairinque'); 
INSERT INTO circunscricoes values (220, 'Piedade'); 
INSERT INTO circunscricoes values (221, 'Tietê'); 
INSERT INTO circunscricoes values (222, 'Irapuru'); 
INSERT INTO circunscricoes values (223, 'Campos Novos Paulista'); 
INSERT INTO circunscricoes values (224, 'Dracena'); 
INSERT INTO circunscricoes values (225, 'Engenheiro Coelho'); 
INSERT INTO circunscricoes values (226, 'Nova Odessa'); 
INSERT INTO circunscricoes values (227, 'Mococa'); 
INSERT INTO circunscricoes values (228, 'Pirassununga'); 
INSERT INTO circunscricoes values (229, 'Elias Fausto'); 
INSERT INTO circunscricoes values (230, 'Rio das Pedras'); 
INSERT INTO circunscricoes values (231, 'Vargem Grande do Sul'); 
INSERT INTO circunscricoes values (232, 'Caieiras'); 
INSERT INTO circunscricoes values (233, 'Cajamar'); 
INSERT INTO circunscricoes values (234, 'Rio Grande da Serra'); 
INSERT INTO circunscricoes values (235, 'São Lourenço da Serra'); 
INSERT INTO circunscricoes values (236, 'São José do Barreiro'); 
INSERT INTO circunscricoes values (237, 'Coroados'); 
INSERT INTO circunscricoes values (238, 'Amparo'); 
INSERT INTO circunscricoes values (239, 'Várzea Paulista'); 
INSERT INTO circunscricoes values (240, 'Taquaritinga'); 
INSERT INTO circunscricoes values (241, 'Guaíra'); 
INSERT INTO circunscricoes values (242, 'Miguelópolis'); 
INSERT INTO circunscricoes values (243, 'Ribeirão Corrente'); 
INSERT INTO circunscricoes values (244, 'Morro Agudo'); 
INSERT INTO circunscricoes values (245, 'Arealva'); 
INSERT INTO circunscricoes values (246, 'Boracéia'); 
INSERT INTO circunscricoes values (247, 'Óleo'); 
INSERT INTO circunscricoes values (248, 'Ourinhos'); 
INSERT INTO circunscricoes values (249, 'Tabapuã'); 
INSERT INTO circunscricoes values (250, 'Nova Granada'); 
INSERT INTO circunscricoes values (251, 'Mongaguá'); 
INSERT INTO circunscricoes values (252, 'Pariquera-Açu'); 
INSERT INTO circunscricoes values (253, 'Fartura'); 
INSERT INTO circunscricoes values (254, 'Anhembi'); 
INSERT INTO circunscricoes values (255, 'Areiópolis'); 
INSERT INTO circunscricoes values (256, 'Capão Bonito'); 
INSERT INTO circunscricoes values (257, 'Alumínio'); 
INSERT INTO circunscricoes values (258, 'Cândido Mota'); 
INSERT INTO circunscricoes values (259, 'Palmital'); 
INSERT INTO circunscricoes values (260, 'João Ramalho'); 
INSERT INTO circunscricoes values (261, 'Presidente Epitácio'); 
INSERT INTO circunscricoes values (262, 'Presidente Venceslau'); 
INSERT INTO circunscricoes values (263, 'Caconde'); 
INSERT INTO circunscricoes values (264, 'Capivari'); 
INSERT INTO circunscricoes values (265, 'Ipeúna'); 
INSERT INTO circunscricoes values (266, 'Aparecida'); 
INSERT INTO circunscricoes values (267, 'Avanhandava'); 
INSERT INTO circunscricoes values (268, 'General Salgado'); 
INSERT INTO circunscricoes values (269, 'Mogi Mirim'); 
INSERT INTO circunscricoes values (270, 'Altair'); 
INSERT INTO circunscricoes values (271, 'Olímpia'); 
INSERT INTO circunscricoes values (272, 'Taiúva'); 
INSERT INTO circunscricoes values (273, 'Cajuru'); 
INSERT INTO circunscricoes values (274, 'Jardinópolis'); 
INSERT INTO circunscricoes values (275, 'São Joaquim da Barra'); 
INSERT INTO circunscricoes values (276, 'Ariranha'); 
INSERT INTO circunscricoes values (277, 'Taquarituba'); 
INSERT INTO circunscricoes values (278, 'Buri'); 
INSERT INTO circunscricoes values (279, 'Itaóca'); 
INSERT INTO circunscricoes values (280, 'São Roque'); 
INSERT INTO circunscricoes values (281, 'Alfredo Marcondes'); 
INSERT INTO circunscricoes values (282, 'Álvares Machado'); 
INSERT INTO circunscricoes values (283, 'Euclides da Cunha Paulista'); 
INSERT INTO circunscricoes values (284, 'Cordeirópolis'); 
INSERT INTO circunscricoes values (285, 'Analândia'); 
INSERT INTO circunscricoes values (286, 'Cachoeira Paulista'); 
INSERT INTO circunscricoes values (287, 'Ibitinga'); 
INSERT INTO circunscricoes values (288, 'Cajobi'); 
INSERT INTO circunscricoes values (289, 'Cássia dos Coqueiros'); 
INSERT INTO circunscricoes values (290, 'Serrana'); 
INSERT INTO circunscricoes values (291, 'Santa Rita do Passa Quatro'); 
INSERT INTO circunscricoes values (292, 'Balbinos'); 
INSERT INTO circunscricoes values (293, 'Vera Cruz'); 
INSERT INTO circunscricoes values (294, 'Jaci'); 
INSERT INTO circunscricoes values (295, 'Cardoso'); 
INSERT INTO circunscricoes values (296, 'Cerqueira César'); 
INSERT INTO circunscricoes values (297, 'São Manuel'); 
INSERT INTO circunscricoes values (298, 'Nova Guataporanga'); 
INSERT INTO circunscricoes values (299, 'Artur Nogueira'); 
INSERT INTO circunscricoes values (300, 'Tambaú'); 
INSERT INTO circunscricoes values (301, 'São Sebastião da Grama'); 
INSERT INTO circunscricoes values (302, 'Mirandópolis'); 
INSERT INTO circunscricoes values (303, 'Auriflama'); 
INSERT INTO circunscricoes values (304, 'Guaraci'); 
INSERT INTO circunscricoes values (305, 'Brodowski'); 
INSERT INTO circunscricoes values (306, 'Ribeirão Bonito'); 
INSERT INTO circunscricoes values (307, 'Monte Aprazível'); 
INSERT INTO circunscricoes values (308, 'Valentim Gentil'); 
INSERT INTO circunscricoes values (309, 'Taciba'); 
INSERT INTO circunscricoes values (310, 'Itobi'); 
INSERT INTO circunscricoes values (311, 'Buritama'); 
INSERT INTO circunscricoes values (312, 'Santo Antonio do Aracanguá'); 
INSERT INTO circunscricoes values (313, 'Piracaia'); 
INSERT INTO circunscricoes values (314, 'Vargem'); 
INSERT INTO circunscricoes values (315, 'Cabreúva'); 
INSERT INTO circunscricoes values (316, 'Jaguariúna'); 
INSERT INTO circunscricoes values (317, 'Jaborandi'); 
INSERT INTO circunscricoes values (318, 'Santa Rosa do Viterbo'); 
INSERT INTO circunscricoes values (319, 'Serra Azul'); 
INSERT INTO circunscricoes values (320, 'Pitangueiras'); 
INSERT INTO circunscricoes values (321, 'Queiroz'); 
INSERT INTO circunscricoes values (322, 'Novo Horizonte'); 
INSERT INTO circunscricoes values (323, 'Monções'); 
INSERT INTO circunscricoes values (324, 'Juquiá'); 
INSERT INTO circunscricoes values (325, 'Conchas'); 
INSERT INTO circunscricoes values (326, 'São Miguel Arcanjo'); 
INSERT INTO circunscricoes values (327, 'Itapeva'); 
INSERT INTO circunscricoes values (328, 'Paulicéia'); 
INSERT INTO circunscricoes values (329, 'Espírito Santo do Pinhal'); 
INSERT INTO circunscricoes values (330, 'Barbosa'); 
INSERT INTO circunscricoes values (331, 'Clementina'); 
INSERT INTO circunscricoes values (332, 'Nazaré Paulista'); 
INSERT INTO circunscricoes values (333, 'Socorro'); 
INSERT INTO circunscricoes values (334, 'Presidente Alves'); 
INSERT INTO circunscricoes values (335, 'Bocaina'); 
INSERT INTO circunscricoes values (336, 'Elisiário'); 
INSERT INTO circunscricoes values (337, 'Palmeira DOeste'); 
INSERT INTO circunscricoes values (338, 'Sete Barras'); 
INSERT INTO circunscricoes values (339, 'Paraibuna'); 
INSERT INTO circunscricoes values (340, 'Itirapuã'); 
INSERT INTO circunscricoes values (341, 'São Simão'); 
INSERT INTO circunscricoes values (342, 'Pirajuí'); 
INSERT INTO circunscricoes values (343, 'Garça'); 
INSERT INTO circunscricoes values (344, 'São Pedro do Turvo'); 
INSERT INTO circunscricoes values (345, 'Paranapuã'); 
INSERT INTO circunscricoes values (346, 'Guapiaçu'); 
INSERT INTO circunscricoes values (347, 'Potirendaba'); 
INSERT INTO circunscricoes values (348, 'Paranapanema'); 
INSERT INTO circunscricoes values (349, 'Tapiraí'); 
INSERT INTO circunscricoes values (350, 'Lucélia'); 
INSERT INTO circunscricoes values (351, 'Ouro Verde'); 
INSERT INTO circunscricoes values (352, 'Panorama'); 
INSERT INTO circunscricoes values (353, 'Ilhabela'); 
INSERT INTO circunscricoes values (354, 'Valinhos'); 
INSERT INTO circunscricoes values (355, 'Boa Esperança do Sul'); 
INSERT INTO circunscricoes values (356, 'Terra Roxa'); 
INSERT INTO circunscricoes values (357, 'Igarapava'); 
INSERT INTO circunscricoes values (358, 'Patrocínio Paulista'); 
INSERT INTO circunscricoes values (359, 'Restinga'); 
INSERT INTO circunscricoes values (360, 'Ipuã'); 
INSERT INTO circunscricoes values (361, 'Piratininga'); 
INSERT INTO circunscricoes values (362, 'Chavantes'); 
INSERT INTO circunscricoes values (363, 'Quatá'); 
INSERT INTO circunscricoes values (364, 'Urânia'); 
INSERT INTO circunscricoes values (365, 'Eldorado'); 
INSERT INTO circunscricoes values (366, 'Itaporanga'); 
INSERT INTO circunscricoes values (367, 'Laranjal Paulista'); 
INSERT INTO circunscricoes values (368, 'Cerquilho'); 
INSERT INTO circunscricoes values (369, 'Bom Sucesso de Itararé'); 
INSERT INTO circunscricoes values (370, 'Itapirapuã Paulista'); 
INSERT INTO circunscricoes values (371, 'Rosana'); 
INSERT INTO circunscricoes values (372, 'Santo Anastácio'); 
INSERT INTO circunscricoes values (373, 'Santa Maria da Serra'); 
INSERT INTO circunscricoes values (374, 'Américo de Campos'); 
INSERT INTO circunscricoes values (375, 'Canitar'); 
INSERT INTO circunscricoes values (376, 'Santa Albertina'); 
INSERT INTO circunscricoes values (377, 'Itapura'); 
INSERT INTO circunscricoes values (378, 'Barra Bonita'); 
INSERT INTO circunscricoes values (379, 'Guaimbê'); 
INSERT INTO circunscricoes values (380, 'Iracemápolis'); 
INSERT INTO circunscricoes values (381, 'Santa Branca'); 
INSERT INTO circunscricoes values (382, 'Onda Verde'); 
INSERT INTO circunscricoes values (383, 'Pardinho'); 
INSERT INTO circunscricoes values (384, 'Dobrada'); 
INSERT INTO circunscricoes values (385, 'Cafelândia'); 
INSERT INTO circunscricoes values (386, 'Sarutaiá'); 
INSERT INTO circunscricoes values (387, 'Nova Campina'); 
INSERT INTO circunscricoes values (388, 'Palmares Paulista'); 
INSERT INTO circunscricoes values (389, 'Ocauçu'); 
INSERT INTO circunscricoes values (390, 'Queluz'); 
INSERT INTO circunscricoes values (391, 'Tarumã'); 
INSERT INTO circunscricoes values (392, 'Ribeirão do Sul'); 
INSERT INTO circunscricoes values (393, 'Junqueirópolis'); 
INSERT INTO circunscricoes values (394, 'Paulo de Faria'); 
INSERT INTO circunscricoes values (395, 'Brotas'); 
INSERT INTO circunscricoes values (396, 'Cristais Paulista'); 
INSERT INTO circunscricoes values (397, 'Lupércio'); 
INSERT INTO circunscricoes values (398, 'Santa Lucia'); 
INSERT INTO circunscricoes values (399, 'Orlândia'); 
INSERT INTO circunscricoes values (400, 'Guaiçara'); 
INSERT INTO circunscricoes values (401, 'Biritiba Mirim'); 
INSERT INTO circunscricoes values (402, 'Mira Estrela'); 
INSERT INTO circunscricoes values (403, 'Jales'); 
INSERT INTO circunscricoes values (404, 'Itaju'); 
INSERT INTO circunscricoes values (405, 'Porangaba'); 
INSERT INTO circunscricoes values (406, 'Bofete'); 
INSERT INTO circunscricoes values (407, 'Iacanga'); 
INSERT INTO circunscricoes values (408, 'Ribeirão Grande'); 
INSERT INTO circunscricoes values (409, 'Itaberá'); 
INSERT INTO circunscricoes values (410, 'Getulina'); 
INSERT INTO circunscricoes values (411, 'Pirapozinho'); 
INSERT INTO circunscricoes values (412, 'Echaporã'); 
INSERT INTO circunscricoes values (413, 'Cesário Lange'); 
INSERT INTO circunscricoes values (414, 'Coronel Macedo'); 
INSERT INTO circunscricoes values (415, 'Pontes Gestal'); 
INSERT INTO circunscricoes values (416, 'Vista Alegre do Alto'); 
INSERT INTO circunscricoes values (417, 'Buritizal'); 
INSERT INTO circunscricoes values (418, 'Santa Mercedes'); 
INSERT INTO circunscricoes values (419, 'Barra do Turvo'); 
INSERT INTO circunscricoes values (420, 'Itirapina'); 
INSERT INTO circunscricoes values (421, 'Ibirarema'); 
INSERT INTO circunscricoes values (422, 'Reginópolis'); 
INSERT INTO circunscricoes values (423, 'Ipaussu'); 
INSERT INTO circunscricoes values (424, 'Tapiratiba'); 
INSERT INTO circunscricoes values (425, 'Charqueada'); 
INSERT INTO circunscricoes values (426, 'Borborema'); 
INSERT INTO circunscricoes values (427, 'Suzanápolis'); 
INSERT INTO circunscricoes values (428, 'Cananéia'); 
INSERT INTO circunscricoes values (429, 'Severínia'); 
INSERT INTO circunscricoes values (430, 'Corumbataí'); 
INSERT INTO circunscricoes values (431, 'Monteiro Lobato'); 
INSERT INTO circunscricoes values (432, 'União Paulista'); 
INSERT INTO circunscricoes values (433, 'Guararema'); 
INSERT INTO circunscricoes values (434, 'Conchal'); 
INSERT INTO circunscricoes values (435, 'Parapuã'); 
INSERT INTO circunscricoes values (436, 'Sebastianópolis do Sul'); 
INSERT INTO circunscricoes values (437, 'São João das Duas Pontes'); 
INSERT INTO circunscricoes values (438, 'Macatuba'); 
INSERT INTO circunscricoes values (439, 'Salesópolis'); 
INSERT INTO circunscricoes values (440, 'São Bento do Sapucaí'); 
INSERT INTO circunscricoes values (441, 'Cabrália Paulista'); 
INSERT INTO circunscricoes values (442, 'Sales'); 
INSERT INTO circunscricoes values (443, 'Gavião Peixoto'); 
INSERT INTO circunscricoes values (444, 'Lourdes'); 
INSERT INTO circunscricoes values (445, 'Icém'); 
INSERT INTO circunscricoes values (446, 'Lavínia'); 
INSERT INTO circunscricoes values (447, 'Santa Cruz do Rio Pardo'); 
INSERT INTO circunscricoes values (448, 'Flórida Paulista'); 
INSERT INTO circunscricoes values (449, 'Populina'); 
INSERT INTO circunscricoes values (450, 'Campina do Monte Alegre'); 
INSERT INTO circunscricoes values (451, 'Itararé'); 
INSERT INTO circunscricoes values (452, 'Lindóia'); 
INSERT INTO circunscricoes values (453, 'Ilha Solteira'); 
INSERT INTO circunscricoes values (454, 'Rincão'); 
INSERT INTO circunscricoes values (455, 'Alvinlândia'); 
INSERT INTO circunscricoes values (456, 'Joanópolis'); 
INSERT INTO circunscricoes values (457, 'Morungaba'); 
INSERT INTO circunscricoes values (458, 'Estrela D'Oeste'); 
INSERT INTO circunscricoes values (459, 'Ribeira'); 
