INSERT INTO tipo_local values (1, 'Via pública'); 
INSERT INTO tipo_local values (2, 'Residência'); 
INSERT INTO tipo_local values (3, 'Rodovia/Estrada'); 
INSERT INTO tipo_local values (4, 'Comércio e serviços'); 
INSERT INTO tipo_local values (5, 'Entidade assistencial'); 
INSERT INTO tipo_local values (6, 'Area não ocupada'); 
INSERT INTO tipo_local values (7, 'Favela'); 
INSERT INTO tipo_local values (8, 'Lazer e recreação'); 
INSERT INTO tipo_local values (9, 'Saúde'); 
INSERT INTO tipo_local values (10, 'Unidade rural'); 
INSERT INTO tipo_local values (11, 'Restaurante e afins'); 
INSERT INTO tipo_local values (12, 'Condominio Residencial'); 
INSERT INTO tipo_local values (13, 'Terminal/Estação'); 
INSERT INTO tipo_local values (14, 'Estabelecimento prisional'); 
INSERT INTO tipo_local values (15, 'Serviços e bens públicos'); 
INSERT INTO tipo_local values (16, 'Local clandestino/ilegal'); 
INSERT INTO tipo_local values (17, 'Repartição Pública'); 
INSERT INTO tipo_local values (18, 'Centro Comerc./Empresarial'); 
INSERT INTO tipo_local values (19, 'Hospedagem'); 
INSERT INTO tipo_local values (20, 'Condominio Comercial'); 
INSERT INTO tipo_local values (21, 'Templo e afins'); 
INSERT INTO tipo_local values (22, 'Estrada de ferro'); 
INSERT INTO tipo_local values (23, 'Estabelecimento de ensino'); 
INSERT INTO tipo_local values (24, 'Shopping Center'); 
INSERT INTO tipo_local values (25, 'Escritório'); 
