INSERT INTO delegacias values (585, '004 DP - Botucatu'); 
INSERT INTO delegacias values (549, '002 DP - Jales'); 
INSERT INTO delegacias values (407, 'DM - Itajú'); 
INSERT INTO delegacias values (91, 'DM - Santa Albertina'); 
INSERT INTO delegacias values (593, '002 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (305, 'DM - Lavinia'); 
INSERT INTO delegacias values (672, '004 DP - Itapeva'); 
INSERT INTO delegacias values (526, 'DM - Corumbataí'); 
INSERT INTO delegacias values (422, '003 DP - Avaré'); 
INSERT INTO delegacias values (307, 'DM - Indaiatuba'); 
INSERT INTO delegacias values (300, 'DM - Queluz'); 
INSERT INTO delegacias values (338, 'DM - Sebastianópolis do Sul'); 
INSERT INTO delegacias values (320, '001 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (626, 'DM - Cafelândia'); 
INSERT INTO delegacias values (90, 'DM - Mira Estrela'); 
INSERT INTO delegacias values (610, '001 DP - Paraguaçú Pta.'); 
INSERT INTO delegacias values (93, 'DM - Icém'); 
INSERT INTO delegacias values (252, 'DM - Sarutaiá'); 
INSERT INTO delegacias values (515, '007 DP - Santos'); 
INSERT INTO delegacias values (466, 'DM - Ocauçú'); 
INSERT INTO delegacias values (121, '005 DP - Sorocaba'); 
INSERT INTO delegacias values (243, 'DM - Getulina'); 
INSERT INTO delegacias values (72, '002 DP - Itapira'); 
INSERT INTO delegacias values (668, 'DM - Pontes Gestal'); 
INSERT INTO delegacias values (543, 'DM - Gaviao Peixoto'); 
INSERT INTO delegacias values (53, 'DM - Suzanópolis'); 
INSERT INTO delegacias values (87, 'DM - Lupércio'); 
INSERT INTO delegacias values (676, 'DM - Iracemápolis'); 
INSERT INTO delegacias values (615, 'DM - Guararema'); 
INSERT INTO delegacias values (667, 'DM - Sales'); 
INSERT INTO delegacias values (605, 'DM - Estrela do Oeste'); 
INSERT INTO delegacias values (541, 'DM - Morungaba'); 
INSERT INTO delegacias values (224, 'DM - Matão'); 
INSERT INTO delegacias values (254, 'DM - Pardinho'); 
INSERT INTO delegacias values (400, 'DM - Guaíra'); 
INSERT INTO delegacias values (425, '002 DP - Itapetininga'); 
INSERT INTO delegacias values (100, 'DM - Barra do Turvo'); 
INSERT INTO delegacias values (487, '001 DP - Piracicaba'); 
INSERT INTO delegacias values (548, 'DM - Populina'); 
INSERT INTO delegacias values (665, '003 DP - Tupã'); 
INSERT INTO delegacias values (406, 'DM - Iacanga'); 
INSERT INTO delegacias values (545, 'DM - Barra Bonita'); 
INSERT INTO delegacias values (440, 'DM - Biritiba Mirim'); 
INSERT INTO delegacias values (537, 'DM - Valinhos'); 
INSERT INTO delegacias values (417, 'DM - Américo de Campos'); 
INSERT INTO delegacias values (329, 'DM - Macatuba'); 
INSERT INTO delegacias values (394, '001 DP - Penapolis'); 
INSERT INTO delegacias values (347, 'DM - Bofete'); 
INSERT INTO delegacias values (525, 'DM - Brotas'); 
INSERT INTO delegacias values (263, 'DM - Junqueirópolis'); 
INSERT INTO delegacias values (331, 'DM - Guaiçara'); 
INSERT INTO delegacias values (612, 'DM - Itirapina'); 
INSERT INTO delegacias values (657, 'DM - Severínia'); 
INSERT INTO delegacias values (332, 'DM - Guaimbe'); 
INSERT INTO delegacias values (366, 'DM - Charqueada'); 
INSERT INTO delegacias values (640, 'DM - Itapura'); 
INSERT INTO delegacias values (550, 'DM - Paulo de Faria'); 
INSERT INTO delegacias values (516, 'DM - Cesário Lange'); 
INSERT INTO delegacias values (45, '008 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (664, 'DM - Ribeirão do Sul'); 
INSERT INTO delegacias values (590, 'DM - Ibirarema'); 
INSERT INTO delegacias values (401, 'DM - Vista Alegre/Alto'); 
INSERT INTO delegacias values (473, 'DM - Coronel Macedo'); 
INSERT INTO delegacias values (606, 'DM - São João das Duas Pontes'); 
INSERT INTO delegacias values (651, '001 DP - Adamantina'); 
INSERT INTO delegacias values (630, 'DM - Onda Verde'); 
INSERT INTO delegacias values (604, '001 DP - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (609, 'DM - Nova Campina'); 
INSERT INTO delegacias values (70, '003 DP - Jundiai'); 
INSERT INTO delegacias values (56, 'DM - Lourdes'); 
INSERT INTO delegacias values (357, '002 DP - Presidente Prudente'); 
INSERT INTO delegacias values (572, 'DM - Santa Lúcia'); 
INSERT INTO delegacias values (303, '001 DP - Taubaté'); 
INSERT INTO delegacias values (520, 'DM - Itararé'); 
INSERT INTO delegacias values (582, 'DM - União Pta.'); 
INSERT INTO delegacias values (245, 'DM - Ipaussu'); 
INSERT INTO delegacias values (608, 'DM - Itaberá'); 
INSERT INTO delegacias values (496, '003 DP - São Sebastião'); 
INSERT INTO delegacias values (247, 'DM - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (114, 'DM - Porangaba'); 
INSERT INTO delegacias values (117, 'DM - Capão Bonito'); 
INSERT INTO delegacias values (654, 'DM - Salesópolis'); 
INSERT INTO delegacias values (328, 'DM - Cabrália Paulista'); 
INSERT INTO delegacias values (581, '001 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (272, 'DM - Tapiratiba'); 
INSERT INTO delegacias values (432, 'DM - Florida Pta.'); 
INSERT INTO delegacias values (574, 'DM - Buritizal'); 
INSERT INTO delegacias values (673, 'DM - Rib. Grande'); 
INSERT INTO delegacias values (462, 'DM - Orlândia'); 
INSERT INTO delegacias values (225, 'DM - Rincão'); 
INSERT INTO delegacias values (68, 'DM - Joanópolis'); 
INSERT INTO delegacias values (214, 'DM - São Bento do Sapucaí'); 
INSERT INTO delegacias values (538, '001 DP - Amparo'); 
INSERT INTO delegacias values (413, 'DM - Palmares Pta.'); 
INSERT INTO delegacias values (552, 'DM - Campina Monte Alegre'); 
INSERT INTO delegacias values (410, 'DM - Alvinlândia'); 
INSERT INTO delegacias values (614, 'Delegacia Aeroporto Int. SP - Guarulhos'); 
INSERT INTO delegacias values (55, '004 DP - Araçatuba'); 
INSERT INTO delegacias values (428, 'DM - Salto'); 
INSERT INTO delegacias values (536, 'DM - Santa Branca'); 
INSERT INTO delegacias values (255, 'DM - Ribeira'); 
INSERT INTO delegacias values (79, 'DM - Cristais Pta.'); 
INSERT INTO delegacias values (485, 'DM - Conchal'); 
INSERT INTO delegacias values (603, 'DM - Reginópolis'); 
INSERT INTO delegacias values (621, 'DM - Lindóia'); 
INSERT INTO delegacias values (522, 'DM - Tarumã'); 
INSERT INTO delegacias values (670, 'DM - Cananéia'); 
INSERT INTO delegacias values (547, 'DM - Canitar'); 
INSERT INTO delegacias values (627, 'DM - Echaporã'); 
INSERT INTO delegacias values (542, 'DM - Dobrada'); 
INSERT INTO delegacias values (392, 'DM - Ilha Solteira'); 
INSERT INTO delegacias values (652, 'DM - Sta. Mercedes'); 
INSERT INTO delegacias values (335, 'DM - Parapuã'); 
INSERT INTO delegacias values (6, '014 DP - Pinheiros'); 
INSERT INTO delegacias values (571, 'DM - Borborema'); 
INSERT INTO delegacias values (356, 'DM - Pirapozinho'); 
INSERT INTO delegacias values (387, 'DM - Monteiro Lobato'); 
INSERT INTO delegacias values (467, '001 DP - Jales'); 
