INSERT INTO delegacias values (698, '001 DP - Taubaté'); 
INSERT INTO delegacias values (699, 'DM - Sebastianópolis do Sul'); 
INSERT INTO delegacias values (700, 'DM - Tapiratiba'); 
INSERT INTO delegacias values (701, 'DM - Estrela do Oeste'); 
INSERT INTO delegacias values (702, 'Delegacia Aeroporto Int. SP - Guarulhos'); 
INSERT INTO delegacias values (703, 'DM - Conchal'); 
INSERT INTO delegacias values (704, 'DM - Borborema'); 
INSERT INTO delegacias values (705, 'DM - Dobrada'); 
INSERT INTO delegacias values (706, '001 DP - Paraguaçú Pta.'); 
INSERT INTO delegacias values (707, 'DM - Ibirarema'); 
INSERT INTO delegacias values (708, 'DM - Rincão'); 
INSERT INTO delegacias values (709, 'DM - Bofete'); 
INSERT INTO delegacias values (710, 'DM - Lupércio'); 
INSERT INTO delegacias values (711, 'DM - Morungaba'); 
INSERT INTO delegacias values (712, 'DM - Cananéia'); 
INSERT INTO delegacias values (713, 'DM - União Pta.'); 
INSERT INTO delegacias values (714, '002 DP - Itapetininga'); 
INSERT INTO delegacias values (715, '004 DP - Botucatu'); 
INSERT INTO delegacias values (716, 'DM - São João das Duas Pontes'); 
INSERT INTO delegacias values (717, 'DM - Severínia'); 
INSERT INTO delegacias values (718, 'DM - Populina'); 
INSERT INTO delegacias values (719, 'DM - Iracemápolis'); 
INSERT INTO delegacias values (720, 'DM - Orlândia'); 
INSERT INTO delegacias values (721, '004 DP - Araçatuba'); 
INSERT INTO delegacias values (722, '002 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (723, 'DM - Sarutaiá'); 
INSERT INTO delegacias values (724, '003 DP - Tupã'); 
INSERT INTO delegacias values (725, 'DM - Tarumã'); 
INSERT INTO delegacias values (726, 'DM - Queluz'); 
INSERT INTO delegacias values (727, 'DM - Itapura'); 
INSERT INTO delegacias values (728, 'DM - Ipaussu'); 
INSERT INTO delegacias values (729, '001 DP - Jales'); 
INSERT INTO delegacias values (730, 'DM - Santa Albertina'); 
INSERT INTO delegacias values (731, 'DM - Cafelândia'); 
INSERT INTO delegacias values (732, 'DM - Porangaba'); 
INSERT INTO delegacias values (733, '003 DP - Jundiai'); 
INSERT INTO delegacias values (734, 'DM - Guaiçara'); 
INSERT INTO delegacias values (735, 'DM - Sales'); 
INSERT INTO delegacias values (736, 'DM - Florida Pta.'); 
INSERT INTO delegacias values (737, 'DM - Suzanópolis'); 
INSERT INTO delegacias values (738, 'DM - Canitar'); 
INSERT INTO delegacias values (739, 'DM - Ocauçú'); 
INSERT INTO delegacias values (740, 'DM - Salesópolis'); 
INSERT INTO delegacias values (741, '002 DP - Presidente Prudente'); 
INSERT INTO delegacias values (742, '001 DP - Piracicaba'); 
INSERT INTO delegacias values (743, 'DM - Capão Bonito'); 
INSERT INTO delegacias values (744, 'DM - Echaporã'); 
INSERT INTO delegacias values (745, 'DM - Charqueada'); 
INSERT INTO delegacias values (746, 'DM - Vista Alegre/Alto'); 
INSERT INTO delegacias values (747, '001 DP - Amparo'); 
INSERT INTO delegacias values (748, 'DM - Américo de Campos'); 
INSERT INTO delegacias values (749, '001 DP - Adamantina'); 
INSERT INTO delegacias values (750, 'DM - Guaimbe'); 
INSERT INTO delegacias values (751, '007 DP - Santos'); 
INSERT INTO delegacias values (752, '002 DP - Itapira'); 
INSERT INTO delegacias values (753, 'DM - Cesário Lange'); 
INSERT INTO delegacias values (754, '002 DP - Jales'); 
INSERT INTO delegacias values (755, 'DM - Pirapozinho'); 
INSERT INTO delegacias values (756, 'DM - Palmares Pta.'); 
INSERT INTO delegacias values (757, 'DM - Monteiro Lobato'); 
INSERT INTO delegacias values (758, 'DM - Santa Branca'); 
INSERT INTO delegacias values (759, 'DM - Ribeirão do Sul'); 
INSERT INTO delegacias values (760, 'DM - Mira Estrela'); 
INSERT INTO delegacias values (761, 'DM - Corumbataí'); 
INSERT INTO delegacias values (762, 'DM - Pardinho'); 
INSERT INTO delegacias values (763, '001 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (764, 'DM - Macatuba'); 
INSERT INTO delegacias values (765, 'DM - Rib. Grande'); 
INSERT INTO delegacias values (766, 'DM - Indaiatuba'); 
INSERT INTO delegacias values (767, 'DM - Lourdes'); 
INSERT INTO delegacias values (768, 'DM - Matão'); 
INSERT INTO delegacias values (769, 'DM - Pontes Gestal'); 
INSERT INTO delegacias values (770, 'DM - Lavinia'); 
INSERT INTO delegacias values (771, 'DM - Itirapina'); 
INSERT INTO delegacias values (772, 'DM - Ilha Solteira'); 
INSERT INTO delegacias values (773, 'DM - Itaberá'); 
INSERT INTO delegacias values (774, '005 DP - Sorocaba'); 
INSERT INTO delegacias values (775, 'DM - Barra Bonita'); 
INSERT INTO delegacias values (776, 'DM - Reginópolis'); 
INSERT INTO delegacias values (777, 'DM - Icém'); 
INSERT INTO delegacias values (778, 'DM - Ribeira'); 
INSERT INTO delegacias values (779, 'DM - Guaíra'); 
INSERT INTO delegacias values (780, 'DM - São Bento do Sapucaí'); 
INSERT INTO delegacias values (781, 'DM - Campina Monte Alegre'); 
INSERT INTO delegacias values (782, 'DM - Barra do Turvo'); 
INSERT INTO delegacias values (783, '014 DP - Pinheiros'); 
INSERT INTO delegacias values (784, 'DM - Sta. Mercedes'); 
INSERT INTO delegacias values (785, 'DM - Biritiba Mirim'); 
INSERT INTO delegacias values (786, 'DM - Santa Lúcia'); 
INSERT INTO delegacias values (787, '003 DP - Avaré'); 
INSERT INTO delegacias values (788, '001 DP - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (789, 'DM - Joanópolis'); 
INSERT INTO delegacias values (790, 'DM - Salto'); 
INSERT INTO delegacias values (791, 'DM - Parapuã'); 
INSERT INTO delegacias values (792, 'DM - Alvinlândia'); 
INSERT INTO delegacias values (793, 'DM - Cristais Pta.'); 
INSERT INTO delegacias values (794, '004 DP - Itapeva'); 
INSERT INTO delegacias values (795, '001 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (796, 'DM - Getulina'); 
INSERT INTO delegacias values (797, 'DM - Cabrália Paulista'); 
INSERT INTO delegacias values (798, 'DM - Iacanga'); 
INSERT INTO delegacias values (799, 'DM - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (800, '001 DP - Penapolis'); 
INSERT INTO delegacias values (801, '003 DP - São Sebastião'); 
INSERT INTO delegacias values (802, 'DM - Valinhos'); 
INSERT INTO delegacias values (803, 'DM - Junqueirópolis'); 
INSERT INTO delegacias values (804, 'DM - Buritizal'); 
INSERT INTO delegacias values (805, 'DM - Nova Campina'); 
INSERT INTO delegacias values (806, 'DM - Gaviao Peixoto'); 
INSERT INTO delegacias values (807, 'DM - Brotas'); 
INSERT INTO delegacias values (808, '008 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (809, 'DM - Paulo de Faria'); 
INSERT INTO delegacias values (810, 'DM - Lindóia'); 
INSERT INTO delegacias values (811, 'DM - Itararé'); 
INSERT INTO delegacias values (812, 'DM - Coronel Macedo'); 
INSERT INTO delegacias values (813, 'DM - Itajú'); 
INSERT INTO delegacias values (814, 'DM - Guararema'); 
INSERT INTO delegacias values (815, 'DM - Onda Verde'); 
