INSERT INTO unidades_administrativas values (1, '1ª SEC'); 
INSERT INTO unidades_administrativas values (2, '2ª SEC'); 
INSERT INTO unidades_administrativas values (3, '3ª SEC'); 
INSERT INTO unidades_administrativas values (4, '4ª SEC'); 
INSERT INTO unidades_administrativas values (5, '5ª SEC'); 
INSERT INTO unidades_administrativas values (6, '6ª SEC'); 
INSERT INTO unidades_administrativas values (7, '7ª SEC'); 
INSERT INTO unidades_administrativas values (8, '8ª SEC'); 
INSERT INTO unidades_administrativas values (9, 'SEC Cruzeiro'); 
INSERT INTO unidades_administrativas values (10, 'SEC Guaratinguetá'); 
INSERT INTO unidades_administrativas values (11, 'SEC Jacareí'); 
INSERT INTO unidades_administrativas values (12, 'SEC São José Campos'); 
INSERT INTO unidades_administrativas values (13, 'SEC São Sebastião'); 
INSERT INTO unidades_administrativas values (14, 'SEC Taubaté'); 
INSERT INTO unidades_administrativas values (15, 'SEC Araçatuba'); 
INSERT INTO unidades_administrativas values (16, '1ª Seccional Campinas'); 
INSERT INTO unidades_administrativas values (17, '2ª Seccional Campinas'); 
INSERT INTO unidades_administrativas values (18, 'SEC Bragança Paulista'); 
INSERT INTO unidades_administrativas values (19, 'SEC Jundiaí'); 
INSERT INTO unidades_administrativas values (20, 'SEC Mogi-Guaçu'); 
INSERT INTO unidades_administrativas values (21, 'SEC Araraquara'); 
INSERT INTO unidades_administrativas values (22, 'SEC Barretos'); 
INSERT INTO unidades_administrativas values (23, 'SEC Bebedouro'); 
INSERT INTO unidades_administrativas values (24, 'SEC Franca'); 
INSERT INTO unidades_administrativas values (25, 'SEC Ribeirão Preto'); 
INSERT INTO unidades_administrativas values (26, 'SEC São Carlos'); 
INSERT INTO unidades_administrativas values (27, 'SEC Sertãozinho'); 
INSERT INTO unidades_administrativas values (28, 'SEC Bauru'); 
INSERT INTO unidades_administrativas values (29, 'SEC Marília'); 
INSERT INTO unidades_administrativas values (30, 'SEC Catanduva'); 
INSERT INTO unidades_administrativas values (31, 'SEC São José Rio Preto'); 
INSERT INTO unidades_administrativas values (32, 'SEC Votuporanga'); 
INSERT INTO unidades_administrativas values (33, 'SEC Itanhaém'); 
INSERT INTO unidades_administrativas values (34, 'SEC Jacupiranga'); 
INSERT INTO unidades_administrativas values (35, 'SEC Registro'); 
INSERT INTO unidades_administrativas values (36, 'SEC Santos'); 
INSERT INTO unidades_administrativas values (37, 'SEC Avaré'); 
INSERT INTO unidades_administrativas values (38, 'SEC Itapetininga'); 
INSERT INTO unidades_administrativas values (39, 'SEC Itapeva'); 
INSERT INTO unidades_administrativas values (40, 'SEC Sorocaba'); 
INSERT INTO unidades_administrativas values (41, 'SEC Assis'); 
INSERT INTO unidades_administrativas values (42, 'SEC Dracena'); 
INSERT INTO unidades_administrativas values (43, 'SEC Presidente Prudente'); 
INSERT INTO unidades_administrativas values (44, 'SEC Presidente Venceslau'); 
INSERT INTO unidades_administrativas values (45, 'SEC Americana'); 
INSERT INTO unidades_administrativas values (46, 'SEC Limeira'); 
INSERT INTO unidades_administrativas values (47, 'SEC Rio Claro'); 
INSERT INTO unidades_administrativas values (48, 'SEC Carapicuíba'); 
INSERT INTO unidades_administrativas values (49, 'SEC Diadema'); 
INSERT INTO unidades_administrativas values (50, 'SEC Franco da Rocha'); 
INSERT INTO unidades_administrativas values (51, 'SEC Guarulhos'); 
INSERT INTO unidades_administrativas values (52, 'SEC Mogi das Cruzes'); 
INSERT INTO unidades_administrativas values (53, 'SEC Osasco'); 
INSERT INTO unidades_administrativas values (54, 'SEC Santo André'); 
INSERT INTO unidades_administrativas values (55, 'SEC São Bernardo Campo'); 
INSERT INTO unidades_administrativas values (56, 'SEC Taboão da Serra'); 
INSERT INTO unidades_administrativas values (57, 'SEC Andradina'); 
INSERT INTO unidades_administrativas values (58, 'SEC Jaú'); 
INSERT INTO unidades_administrativas values (59, 'SEC Lins'); 
INSERT INTO unidades_administrativas values (60, 'SEC Ourinhos'); 
INSERT INTO unidades_administrativas values (61, 'SEC Tupã'); 
INSERT INTO unidades_administrativas values (62, 'SEC Novo Horizonte'); 
INSERT INTO unidades_administrativas values (63, 'SEC Botucatu'); 
INSERT INTO unidades_administrativas values (64, 'SEC Adamantina'); 
INSERT INTO unidades_administrativas values (65, 'SEC São João Boa Vista'); 
INSERT INTO unidades_administrativas values (66, 'SEC Jales'); 
INSERT INTO unidades_administrativas values (67, 'SEC Casa Branca'); 
INSERT INTO unidades_administrativas values (68, 'SEC Piracicaba'); 
INSERT INTO unidades_administrativas values (69, 'SEC Fernandópolis'); 
INSERT INTO unidades_administrativas values (70, 'SEC São Joaquim da Barra'); 
