INSERT INTO delegacias values (698, '002 DP - Bom Retiro'); 
INSERT INTO delegacias values (699, '008 DP - Brás'); 
INSERT INTO delegacias values (700, '078 DP - Jardins'); 
INSERT INTO delegacias values (701, '017 DP - Ipiranga'); 
INSERT INTO delegacias values (702, '083 DP - Parque Bristol'); 
INSERT INTO delegacias values (703, '014 DP - Pinheiros'); 
INSERT INTO delegacias values (704, '023 DP - Perdizes'); 
INSERT INTO delegacias values (705, '037 DP - Campo Limpo'); 
INSERT INTO delegacias values (706, '046 DP - Perus'); 
INSERT INTO delegacias values (707, '075 DP - Jardim Arpoador'); 
INSERT INTO delegacias values (708, '087 DP - Vila Pereira Barreto'); 
INSERT INTO delegacias values (709, '089 DP - Portal do Morumbi'); 
INSERT INTO delegacias values (710, '013 DP - Casa Verde'); 
INSERT INTO delegacias values (711, '038 DP - Vila Amália'); 
INSERT INTO delegacias values (712, '073 DP - Jaçanã'); 
INSERT INTO delegacias values (713, '074 DP - Jaraguá'); 
INSERT INTO delegacias values (714, '010 DP - Penha de França'); 
INSERT INTO delegacias values (715, '058 DP - Vila Formosa'); 
INSERT INTO delegacias values (716, '011 DP - Santo Amaro'); 
INSERT INTO delegacias values (717, '025 DP - Parelheiros'); 
INSERT INTO delegacias values (718, '047 DP - Capão Redondo'); 
INSERT INTO delegacias values (719, '085 DP - Jardim Mirna'); 
INSERT INTO delegacias values (720, '092 DP - Parque Santo Antônio'); 
INSERT INTO delegacias values (721, '098 DP - Jardim Míriam'); 
INSERT INTO delegacias values (722, '100 DP - Jardim Herculano'); 
INSERT INTO delegacias values (723, '101 DP - Jardim das Imbuias'); 
INSERT INTO delegacias values (724, '059 DP - Jardim Noemia'); 
INSERT INTO delegacias values (725, '062 DP - Ermelino Matarazzo'); 
INSERT INTO delegacias values (726, '063 DP - Vila Jacuí'); 
INSERT INTO delegacias values (727, '068 DP - Lajeado'); 
INSERT INTO delegacias values (728, '044 DP - Guaianazes'); 
INSERT INTO delegacias values (729, '054 DP - Cidade Tiradentes'); 
INSERT INTO delegacias values (730, '055 DP - Parque São Rafael'); 
INSERT INTO delegacias values (731, '070 DP - Vila Ema'); 
INSERT INTO delegacias values (732, '002 DP - Cruzeiro'); 
INSERT INTO delegacias values (733, 'DM - Aparecida'); 
INSERT INTO delegacias values (734, 'DM - Canas'); 
INSERT INTO delegacias values (735, '002 DP - Guaratinguetá'); 
INSERT INTO delegacias values (736, '001 DP - Lorena'); 
INSERT INTO delegacias values (737, '002 DP - Lorena'); 
INSERT INTO delegacias values (738, 'DM - Potim'); 
INSERT INTO delegacias values (739, '001 DP - Jacareí'); 
INSERT INTO delegacias values (740, '003 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (741, '006 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (742, '008 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (743, 'DM - Caraguatatuba'); 
INSERT INTO delegacias values (744, '001 DP - São Sebastião'); 
INSERT INTO delegacias values (745, 'DM - Ubatuba'); 
INSERT INTO delegacias values (746, '001 DP - Campos do Jordão'); 
INSERT INTO delegacias values (747, '002 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (748, '003 DP - Taubaté'); 
INSERT INTO delegacias values (749, 'DM - Pereira Barreto'); 
INSERT INTO delegacias values (750, 'DM - Suzanópolis'); 
INSERT INTO delegacias values (751, '003 DP - Araçatuba'); 
INSERT INTO delegacias values (752, '004 DP - Araçatuba'); 
INSERT INTO delegacias values (753, 'DM - Lourdes'); 
INSERT INTO delegacias values (754, '003 DP - Campinas'); 
INSERT INTO delegacias values (755, '004 DP - Campinas'); 
INSERT INTO delegacias values (756, '007 DP - Campinas'); 
INSERT INTO delegacias values (757, '010 DP - Campinas'); 
INSERT INTO delegacias values (758, '002 DP - Campinas'); 
INSERT INTO delegacias values (759, '008 DP - Campinas'); 
INSERT INTO delegacias values (760, '009 DP - Campinas'); 
INSERT INTO delegacias values (761, '011 DP - Campinas'); 
INSERT INTO delegacias values (762, '001 DP - Indaiatuba'); 
INSERT INTO delegacias values (763, '002 DP - Atibaia'); 
INSERT INTO delegacias values (764, '002 DP - Bragança Pta.'); 
INSERT INTO delegacias values (765, 'DM - Joanópolis'); 
INSERT INTO delegacias values (766, 'DM - Campo Limpo Pta.'); 
INSERT INTO delegacias values (767, '003 DP - Jundiai'); 
INSERT INTO delegacias values (768, 'DM - Várzea Pta.'); 
INSERT INTO delegacias values (769, '002 DP - Itapira'); 
INSERT INTO delegacias values (770, '002 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (771, '003 DP - Araraquara'); 
INSERT INTO delegacias values (772, 'DM - Ibitinga'); 
INSERT INTO delegacias values (773, 'DM - Itápolis'); 
INSERT INTO delegacias values (774, 'DM - Olímpia'); 
INSERT INTO delegacias values (775, 'DM - Taiaçu'); 
INSERT INTO delegacias values (776, 'DM - Cristais Pta.'); 
INSERT INTO delegacias values (777, '002 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (778, 'DM - Porto Ferreira'); 
INSERT INTO delegacias values (779, '004 DP - São Carlos'); 
INSERT INTO delegacias values (780, 'DM - Guariba'); 
INSERT INTO delegacias values (781, 'DM - Sertãozinho'); 
INSERT INTO delegacias values (782, 'DM - Agudos'); 
INSERT INTO delegacias values (783, '002 DP - Lins'); 
INSERT INTO delegacias values (784, 'DM - Lupércio'); 
INSERT INTO delegacias values (785, '001 DP - Marília'); 
INSERT INTO delegacias values (786, '002 DP - Marília'); 
INSERT INTO delegacias values (787, 'DM - Mira Estrela'); 
INSERT INTO delegacias values (788, 'DM - Santa Albertina'); 
INSERT INTO delegacias values (789, 'DM - Urãnia'); 
INSERT INTO delegacias values (790, 'DM - Icém'); 
INSERT INTO delegacias values (791, '003 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (792, '004 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (793, 'DM - Tanabi'); 
INSERT INTO delegacias values (794, '002 DP - Itanhaem'); 
INSERT INTO delegacias values (795, '002 DP - Mongaguá'); 
INSERT INTO delegacias values (796, 'DM - Mongaguá'); 
INSERT INTO delegacias values (797, 'DM - Barra do Turvo'); 
INSERT INTO delegacias values (798, 'DM - Iguape'); 
INSERT INTO delegacias values (799, '002 DP - Cubatão'); 
INSERT INTO delegacias values (800, '002 DP - Guarujá'); 
INSERT INTO delegacias values (801, 'DM - Guarujá'); 
INSERT INTO delegacias values (802, '001 DP - Praia Grande'); 
INSERT INTO delegacias values (803, '002 DP - Praia Grande'); 
INSERT INTO delegacias values (804, '003 DP - Praia Grande'); 
INSERT INTO delegacias values (805, 'DM - Praia Grande'); 
INSERT INTO delegacias values (806, '001 DP - Santos'); 
INSERT INTO delegacias values (807, '002 DP - Santos'); 
INSERT INTO delegacias values (808, '001 DP - São Vicente'); 
INSERT INTO delegacias values (809, '002 DP - São Vicente'); 
INSERT INTO delegacias values (810, 'DM - Iaras'); 
INSERT INTO delegacias values (811, 'DM - Porangaba'); 
INSERT INTO delegacias values (812, '001 DP - Itapetininga'); 
INSERT INTO delegacias values (813, 'DM - Tatuí'); 
INSERT INTO delegacias values (814, 'DM - Capão Bonito'); 
INSERT INTO delegacias values (815, '001 DP - Itú'); 
INSERT INTO delegacias values (816, 'DM - São Roque'); 
INSERT INTO delegacias values (817, '002 DP - Sorocaba'); 
INSERT INTO delegacias values (818, '005 DP - Sorocaba'); 
INSERT INTO delegacias values (819, '006 DP - Sorocaba'); 
INSERT INTO delegacias values (820, 'DM - Votorantim'); 
INSERT INTO delegacias values (821, 'DM - Paraguaçú Pta.'); 
INSERT INTO delegacias values (822, '001 DP - Presidente Prudente'); 
INSERT INTO delegacias values (823, 'DM - Cosmópolis'); 
INSERT INTO delegacias values (824, 'DM - Engenheiro Coelho'); 
INSERT INTO delegacias values (825, '001 DP - Hortolândia'); 
INSERT INTO delegacias values (826, 'DM - Monte Mor'); 
INSERT INTO delegacias values (827, '002 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (828, '002 DP - Sumaré'); 
INSERT INTO delegacias values (829, '003 DP - Sumaré'); 
INSERT INTO delegacias values (830, '001 DP - Leme'); 
INSERT INTO delegacias values (831, '001 DP - Pirassununga'); 
INSERT INTO delegacias values (832, '002 DP - Piracicaba'); 
INSERT INTO delegacias values (833, '004 DP - Piracicaba'); 
INSERT INTO delegacias values (834, '001 DP - Rio Claro'); 
INSERT INTO delegacias values (835, '002 DP - Rio Claro'); 
INSERT INTO delegacias values (836, 'DM - Espírito Sto. do Pinhal'); 
INSERT INTO delegacias values (837, '001 DP - Carapicuiba'); 
INSERT INTO delegacias values (838, '002 DP - Carapicuiba'); 
INSERT INTO delegacias values (839, 'DM - Cotia'); 
INSERT INTO delegacias values (840, 'DM - Itapevi'); 
INSERT INTO delegacias values (841, 'DM - Jandira'); 
INSERT INTO delegacias values (842, 'DM - Pirapora do Bom Jesus'); 
INSERT INTO delegacias values (843, 'DM - Santana do Parnaiba'); 
INSERT INTO delegacias values (844, '002 DP - Diadema'); 
INSERT INTO delegacias values (845, '003 DP - Diadema'); 
INSERT INTO delegacias values (846, '001 DP - Caieiras'); 
INSERT INTO delegacias values (847, 'DM - Cajamar'); 
INSERT INTO delegacias values (848, 'DM - Francisco Morato'); 
INSERT INTO delegacias values (849, 'DM - Mairiporã'); 
INSERT INTO delegacias values (850, 'DM - Aruja'); 
INSERT INTO delegacias values (851, '001 DP - Guarulhos'); 
INSERT INTO delegacias values (852, '002 DP - Guarulhos'); 
INSERT INTO delegacias values (853, '004 DP - Guarulhos'); 
INSERT INTO delegacias values (854, '007 DP - Guarulhos'); 
INSERT INTO delegacias values (855, '009 DP - Guarulhos'); 
INSERT INTO delegacias values (856, 'DM - Santa Isabel'); 
INSERT INTO delegacias values (857, 'DM - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (858, '001 DP - Itaquaquecetuba'); 
INSERT INTO delegacias values (859, 'DM - Itaquaquecetuba'); 
INSERT INTO delegacias values (860, '003 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (861, '004 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (862, 'DM - Poá'); 
INSERT INTO delegacias values (863, 'DM - Suzano'); 
INSERT INTO delegacias values (864, '002 DP - Osasco'); 
INSERT INTO delegacias values (865, '003 DP - Osasco'); 
INSERT INTO delegacias values (866, '010 DP - Osasco'); 
INSERT INTO delegacias values (867, '001 DP - Mauá'); 
INSERT INTO delegacias values (868, '002 DP - Mauá'); 
INSERT INTO delegacias values (869, '003 DP - Mauá'); 
INSERT INTO delegacias values (870, 'DM - Ribeirão Pires'); 
INSERT INTO delegacias values (871, '003 DP - Santo André'); 
INSERT INTO delegacias values (872, '005 DP - Santo André'); 
INSERT INTO delegacias values (873, '006 DP - Santo André'); 
INSERT INTO delegacias values (874, '003 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (875, '004 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (876, '006 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (877, '008 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (878, '001 DP - Embú'); 
INSERT INTO delegacias values (879, 'DM - Embú'); 
INSERT INTO delegacias values (880, 'DM - Embú Guaçú'); 
INSERT INTO delegacias values (881, 'DM - Itapecerica da Serra'); 
INSERT INTO delegacias values (882, '002 DP - Taboão da Serra'); 
INSERT INTO delegacias values (883, '001 DP - Sé'); 
INSERT INTO delegacias values (884, '006 DP - Cambuci'); 
INSERT INTO delegacias values (885, '077 DP - Santa Cecília'); 
INSERT INTO delegacias values (886, '009 DP - Carandiru'); 
INSERT INTO delegacias values (887, '039 DP - Vila Gustavo'); 
INSERT INTO delegacias values (888, '045 DP - Vila Brasilândia'); 
INSERT INTO delegacias values (889, '072 DP - Vila Penteado'); 
INSERT INTO delegacias values (890, '030 DP - Tatuapé'); 
INSERT INTO delegacias values (891, '048 DP - Cidade Dutra'); 
INSERT INTO delegacias values (892, '080 DP - Vila Joaniza'); 
INSERT INTO delegacias values (893, '099 DP - Campo Grande'); 
INSERT INTO delegacias values (894, '022 DP - São Miguel Paulista'); 
INSERT INTO delegacias values (895, '024 DP - Ponte Rasa'); 
INSERT INTO delegacias values (896, '050 DP - Itaim Paulista'); 
INSERT INTO delegacias values (897, '065 DP - Artur Alvim'); 
INSERT INTO delegacias values (898, '067 DP - Jardim Robru'); 
INSERT INTO delegacias values (899, '049 DP - São Mateus'); 
INSERT INTO delegacias values (900, '053 DP - Parque do Carmo'); 
INSERT INTO delegacias values (901, '066 DP - Vale do Aricanduva'); 
INSERT INTO delegacias values (902, '069 DP - Teotônio Vilela'); 
INSERT INTO delegacias values (903, '003 DP - Cruzeiro'); 
INSERT INTO delegacias values (904, '001 DP - Guaratinguetá'); 
INSERT INTO delegacias values (905, '003 DP - Guaratinguetá'); 
INSERT INTO delegacias values (906, 'DM - Caçapava'); 
INSERT INTO delegacias values (907, '002 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (908, '002 DP - São Sebastião'); 
INSERT INTO delegacias values (909, '004 DP - São Sebastião'); 
INSERT INTO delegacias values (910, 'DM - Campos do Jordão'); 
INSERT INTO delegacias values (911, 'DM - São Bento do Sapucaí'); 
INSERT INTO delegacias values (912, 'DM - Tremembé'); 
INSERT INTO delegacias values (913, '002 DP - Araçatuba'); 
INSERT INTO delegacias values (914, 'DM - Guararapes'); 
INSERT INTO delegacias values (915, 'DM - Piracaia'); 
INSERT INTO delegacias values (916, 'DM - Itatiba'); 
INSERT INTO delegacias values (917, '001 DP - Jundiai'); 
INSERT INTO delegacias values (918, '001 DP - Várzea Pta.'); 
INSERT INTO delegacias values (919, '003 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (920, '003 DP - Mogi Mirim'); 
INSERT INTO delegacias values (921, 'DM - Matão'); 
INSERT INTO delegacias values (922, 'DM - Rincão'); 
INSERT INTO delegacias values (923, 'DM - Cajobi'); 
INSERT INTO delegacias values (924, '001 DP - Guaíra'); 
INSERT INTO delegacias values (925, '001 DP - Batatais'); 
INSERT INTO delegacias values (926, '002 DP - Franca'); 
INSERT INTO delegacias values (927, '005 DP - Franca'); 
INSERT INTO delegacias values (928, 'DM - Restinga'); 
INSERT INTO delegacias values (929, 'DM - Cravinhos'); 
INSERT INTO delegacias values (930, '003 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (931, '004 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (932, '005 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (933, '005 DP - São Carlos'); 
INSERT INTO delegacias values (934, 'DM - Morro Agudo'); 
INSERT INTO delegacias values (935, 'DM - Pitangueiras'); 
INSERT INTO delegacias values (936, '002 DP - Bauru'); 
INSERT INTO delegacias values (937, 'DM - Lençóis Paulista'); 
INSERT INTO delegacias values (938, 'DM - Pederneiras'); 
INSERT INTO delegacias values (939, '001 DP - Jaú'); 
INSERT INTO delegacias values (940, 'DM - Getulina'); 
INSERT INTO delegacias values (941, '003 DP - Lins'); 
INSERT INTO delegacias values (942, 'DM - Ipaussu'); 
INSERT INTO delegacias values (943, '002 DP - Ourinhos'); 
INSERT INTO delegacias values (944, 'DM - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (945, '003 DP - Catanduva'); 
INSERT INTO delegacias values (946, 'DM - Valentim Gentil'); 
INSERT INTO delegacias values (947, '001 DP - Votuporanga'); 
INSERT INTO delegacias values (948, 'DM - Itaporanga'); 
INSERT INTO delegacias values (949, 'DM - Sarutaiá'); 
INSERT INTO delegacias values (950, '003 DP - Botucatu'); 
INSERT INTO delegacias values (951, 'DM - Pardinho'); 
INSERT INTO delegacias values (952, 'DM - Ribeira'); 
INSERT INTO delegacias values (953, 'DM - Ibiúna'); 
INSERT INTO delegacias values (954, '002 DP - Itú'); 
INSERT INTO delegacias values (955, '004 DP - Itú'); 
INSERT INTO delegacias values (956, 'DM - Mairinque'); 
INSERT INTO delegacias values (957, '002 DP - Salto'); 
INSERT INTO delegacias values (958, '008 DP - Sorocaba'); 
INSERT INTO delegacias values (959, '003 DP - Votorantim'); 
INSERT INTO delegacias values (960, 'DM - Junqueirópolis'); 
INSERT INTO delegacias values (961, 'DM - Tupi Pta.'); 
INSERT INTO delegacias values (962, '001 DP - Rosana'); 
INSERT INTO delegacias values (963, 'DM - Sto. Anastácio'); 
INSERT INTO delegacias values (964, '002 DP - Americana'); 
INSERT INTO delegacias values (965, '002 DP - Hortolândia'); 
INSERT INTO delegacias values (966, 'DM - Nova Odessa'); 
INSERT INTO delegacias values (967, '003 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (968, 'DM - Casa Branca'); 
INSERT INTO delegacias values (969, 'DM - Tapiratiba'); 
INSERT INTO delegacias values (970, 'DM - Cordeirópolis'); 
INSERT INTO delegacias values (971, '001 DP - Limeira'); 
INSERT INTO delegacias values (972, '003 DP - Piracicaba'); 
INSERT INTO delegacias values (973, '005 DP - Piracicaba'); 
INSERT INTO delegacias values (974, '003 DP - Rio Claro'); 
INSERT INTO delegacias values (975, 'DM - Sta. Gertrudes'); 
INSERT INTO delegacias values (976, '001 DP - Cotia'); 
INSERT INTO delegacias values (977, 'DM - Vargem Grande Paulista'); 
INSERT INTO delegacias values (978, '001 DP - Diadema'); 
INSERT INTO delegacias values (979, '004 DP - Diadema'); 
INSERT INTO delegacias values (980, '001 DP - Mairiporã'); 
INSERT INTO delegacias values (981, '006 DP - Guarulhos'); 
INSERT INTO delegacias values (982, '008 DP - Osasco'); 
INSERT INTO delegacias values (983, '004 DP - Mauá'); 
INSERT INTO delegacias values (984, '003 DP - Campos Elísios'); 
INSERT INTO delegacias values (985, '005 DP - Aclimação'); 
INSERT INTO delegacias values (986, '016 DP - Vila Clementino'); 
INSERT INTO delegacias values (987, '033 DP - Pirituba'); 
INSERT INTO delegacias values (988, '093 DP - Jaguaré'); 
INSERT INTO delegacias values (989, '020 DP - Água Fria'); 
INSERT INTO delegacias values (990, '028 DP - Freguesia do Ó'); 
INSERT INTO delegacias values (991, '029 DP - Vila Diva'); 
INSERT INTO delegacias values (992, '042 DP - Parque São Lucas'); 
INSERT INTO delegacias values (993, '043 DP - Cidade Ademar'); 
INSERT INTO delegacias values (994, '102 DP - Socorro'); 
INSERT INTO delegacias values (995, '032 DP - Itaquera'); 
INSERT INTO delegacias values (996, '064 DP - Cidade A E Carvalho'); 
INSERT INTO delegacias values (997, 'DM - Queluz'); 
INSERT INTO delegacias values (998, '002 DP - Jacareí'); 
INSERT INTO delegacias values (999, '001 DP - Caraguatatuba'); 
INSERT INTO delegacias values (1000, '001 DP - Taubaté'); 
INSERT INTO delegacias values (1001, '004 DP - Taubaté'); 
INSERT INTO delegacias values (1002, 'DM - Lavinia'); 
INSERT INTO delegacias values (1003, '001 DP - Birigui'); 
INSERT INTO delegacias values (1004, 'DM - Indaiatuba'); 
INSERT INTO delegacias values (1005, 'DM - Atibaia'); 
INSERT INTO delegacias values (1006, '003 DP - Bragança Pta.'); 
INSERT INTO delegacias values (1007, '001 DP - Itatiba'); 
INSERT INTO delegacias values (1008, '001 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (1009, '002 DP - Mogi Mirim'); 
INSERT INTO delegacias values (1010, '001 DP - Araraquara'); 
INSERT INTO delegacias values (1011, '001 DP - Matao'); 
INSERT INTO delegacias values (1012, '002 DP - Bebedouro'); 
INSERT INTO delegacias values (1013, '004 DP - Franca'); 
INSERT INTO delegacias values (1014, 'DM - Miguelópolis'); 
INSERT INTO delegacias values (1015, 'DM - Patrocínio Pta.'); 
INSERT INTO delegacias values (1016, 'DM - Jardinópolis'); 
INSERT INTO delegacias values (1017, '001 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (1018, '007 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (1019, 'DM - Ibaté'); 
INSERT INTO delegacias values (1020, '001 DP - São Carlos'); 
INSERT INTO delegacias values (1021, '002 DP - São Carlos'); 
INSERT INTO delegacias values (1022, '001 DP - Jaboticabal'); 
INSERT INTO delegacias values (1023, '001 DP - Bauru'); 
INSERT INTO delegacias values (1024, '004 DP - Bauru'); 
INSERT INTO delegacias values (1025, 'DM - Cabrália Paulista'); 
INSERT INTO delegacias values (1026, 'DM - Macatuba'); 
INSERT INTO delegacias values (1027, 'DM - Igaraçu do Tietê'); 
INSERT INTO delegacias values (1028, 'DM - Guaiçara'); 
INSERT INTO delegacias values (1029, 'DM - Guaimbe'); 
INSERT INTO delegacias values (1030, '001 DP - Lins'); 
INSERT INTO delegacias values (1031, '003 DP - Ourinhos'); 
INSERT INTO delegacias values (1032, 'DM - Parapuã'); 
INSERT INTO delegacias values (1033, 'DM - José Bonifácio'); 
INSERT INTO delegacias values (1034, '007 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (1035, 'DM - Sebastianópolis do Sul'); 
INSERT INTO delegacias values (1036, '003 DP - Votuporanga'); 
INSERT INTO delegacias values (1037, '003 DP - Itanhaem'); 
INSERT INTO delegacias values (1038, '001 DP - Peruíbe'); 
INSERT INTO delegacias values (1039, 'DM - Sete Barras'); 
INSERT INTO delegacias values (1040, 'DM - Bertioga'); 
INSERT INTO delegacias values (1041, '001 DP - Guarujá'); 
INSERT INTO delegacias values (1042, '004 DP - Santos'); 
INSERT INTO delegacias values (1043, 'DM - Itaí'); 
INSERT INTO delegacias values (1044, 'DM - Bofete'); 
INSERT INTO delegacias values (1045, 'DM - Itatinga'); 
INSERT INTO delegacias values (1046, 'DM - Boituva'); 
INSERT INTO delegacias values (1047, 'DM - Buri'); 
INSERT INTO delegacias values (1048, 'DM - Salto de Pirapora'); 
INSERT INTO delegacias values (1049, '001 DP - Sorocaba'); 
INSERT INTO delegacias values (1050, '010 DP - Sorocaba'); 
INSERT INTO delegacias values (1051, '011 DP - Sorocaba'); 
INSERT INTO delegacias values (1052, '003 DP - Assis'); 
INSERT INTO delegacias values (1053, 'DM - Pirapozinho'); 
INSERT INTO delegacias values (1054, '002 DP - Presidente Prudente'); 
INSERT INTO delegacias values (1055, 'DM - Regente Feijó'); 
INSERT INTO delegacias values (1056, 'DM - Presidente Epitácio'); 
INSERT INTO delegacias values (1057, '001 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (1058, '004 DP - Americana'); 
INSERT INTO delegacias values (1059, 'DM - Artur Nogueira'); 
INSERT INTO delegacias values (1060, '001 DP - Sumaré'); 
INSERT INTO delegacias values (1061, '004 DP - Sumaré'); 
INSERT INTO delegacias values (1062, 'DM - Itobi'); 
INSERT INTO delegacias values (1063, 'DM - Charqueada'); 
INSERT INTO delegacias values (1064, 'DM - São Sebastião da Gama'); 
INSERT INTO delegacias values (1065, '001 DP - Barueri'); 
INSERT INTO delegacias values (1066, 'DM - Barueri'); 
INSERT INTO delegacias values (1067, '003 DP - Carapicuiba'); 
INSERT INTO delegacias values (1068, '001 DP - Cajamar'); 
INSERT INTO delegacias values (1069, 'DM - Franco da Rocha'); 
INSERT INTO delegacias values (1070, '008 DP - Guarulhos'); 
INSERT INTO delegacias values (1071, '001 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (1072, '002 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (1073, '007 DP - Osasco'); 
INSERT INTO delegacias values (1074, 'DM - São Lourenço da Serra'); 
INSERT INTO delegacias values (1075, '001 DP - Taboão da Serra'); 
INSERT INTO delegacias values (1076, '095 DP - Heliópolis'); 
INSERT INTO delegacias values (1077, '097 DP - Americanópolis'); 
INSERT INTO delegacias values (1078, '034 DP - Vila Sonia'); 
INSERT INTO delegacias values (1079, '051 DP - Butantã'); 
INSERT INTO delegacias values (1080, '040 DP - Vila Santa Maria'); 
INSERT INTO delegacias values (1081, '090 DP - Parque Novo Mundo'); 
INSERT INTO delegacias values (1082, '021 DP - Vila Matilde'); 
INSERT INTO delegacias values (1083, '103 DP - Cohab Itaquera'); 
INSERT INTO delegacias values (1084, 'DM - Monteiro Lobato'); 
INSERT INTO delegacias values (1085, '005 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (1086, '003 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (1087, '002 DP - Taubaté'); 
INSERT INTO delegacias values (1088, '001 DP - Andradina'); 
INSERT INTO delegacias values (1089, 'DM - Ilha Solteira'); 
INSERT INTO delegacias values (1090, 'DM - Buritama'); 
INSERT INTO delegacias values (1091, '001 DP - Penapolis'); 
INSERT INTO delegacias values (1092, '005 DP - Campinas'); 
INSERT INTO delegacias values (1093, '001 DP - Atibaia'); 
INSERT INTO delegacias values (1094, 'DM - Jaguariúna'); 
INSERT INTO delegacias values (1095, '004 DP - Araraquara'); 
INSERT INTO delegacias values (1096, 'DM - Tabatinga'); 
INSERT INTO delegacias values (1097, 'DM - Guaíra'); 
INSERT INTO delegacias values (1098, 'DM - Vista Alegre/Alto'); 
INSERT INTO delegacias values (1099, 'DM - Guará'); 
INSERT INTO delegacias values (1100, '006 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (1101, '002 DP - Jaboticabal'); 
INSERT INTO delegacias values (1102, 'DM - Monte Alto'); 
INSERT INTO delegacias values (1103, 'DM - Iacanga'); 
INSERT INTO delegacias values (1104, 'DM - Itajú'); 
INSERT INTO delegacias values (1105, '002 DP - Jaú'); 
INSERT INTO delegacias values (1106, 'DM - Promissão'); 
INSERT INTO delegacias values (1107, 'DM - Alvinlândia'); 
INSERT INTO delegacias values (1108, '004 DP - Marília'); 
INSERT INTO delegacias values (1109, '004 DP - Catanduva'); 
INSERT INTO delegacias values (1110, 'DM - Palmares Pta.'); 
INSERT INTO delegacias values (1111, 'DM - Tabapuã'); 
INSERT INTO delegacias values (1112, 'DM - Urupes'); 
INSERT INTO delegacias values (1113, '006 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (1114, 'DM - Américo de Campos'); 
INSERT INTO delegacias values (1115, '001 DP - Itanhaem'); 
INSERT INTO delegacias values (1116, 'DM - Miracatú'); 
INSERT INTO delegacias values (1117, '003 DP - Cubatão'); 
INSERT INTO delegacias values (1118, '005 DP - Santos'); 
INSERT INTO delegacias values (1119, '003 DP - Avaré'); 
INSERT INTO delegacias values (1120, '001 DP - Pirajú'); 
INSERT INTO delegacias values (1121, '002 DP - Botucatu'); 
INSERT INTO delegacias values (1122, '002 DP - Itapetininga'); 
INSERT INTO delegacias values (1123, 'DM - Araçoiba da Serra'); 
INSERT INTO delegacias values (1124, 'DM - Porto Feliz'); 
INSERT INTO delegacias values (1125, 'DM - Salto'); 
INSERT INTO delegacias values (1126, '009 DP - Sorocaba'); 
INSERT INTO delegacias values (1127, 'DM - Tiete'); 
INSERT INTO delegacias values (1128, '003 DP - Adamantina'); 
INSERT INTO delegacias values (1129, 'DM - Florida Pta.'); 
INSERT INTO delegacias values (1130, 'DM - Teodoro Sampaio'); 
INSERT INTO delegacias values (1131, '001 DP - Americana'); 
INSERT INTO delegacias values (1132, '005 DP - Sumaré'); 
INSERT INTO delegacias values (1133, 'DM - Sta. Cruz das Palmeiras'); 
INSERT INTO delegacias values (1134, '002 DP - Leme'); 
INSERT INTO delegacias values (1135, '006 DP - Piracicaba'); 
INSERT INTO delegacias values (1136, 'DM - São Pedro'); 
INSERT INTO delegacias values (1137, 'DM - Biritiba Mirim'); 
INSERT INTO delegacias values (1138, '001 DP - Suzano'); 
INSERT INTO delegacias values (1139, '002 DP - Suzano'); 
INSERT INTO delegacias values (1140, '006 DP - Osasco'); 
INSERT INTO delegacias values (1141, '001 DP - Santo André'); 
INSERT INTO delegacias values (1142, '004 DP - Santo André'); 
INSERT INTO delegacias values (1143, '012 DP - Pari'); 
INSERT INTO delegacias values (1144, '027 DP - Campo Belo'); 
INSERT INTO delegacias values (1145, '007 DP - Lapa'); 
INSERT INTO delegacias values (1146, '007 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (1147, 'DM - Ilhabela'); 
INSERT INTO delegacias values (1148, '001 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (1149, '001 DP - Campinas'); 
INSERT INTO delegacias values (1150, 'DM - Paulínea'); 
INSERT INTO delegacias values (1151, '001 DP - Valinhos'); 
INSERT INTO delegacias values (1152, '006 DP - Campinas'); 
INSERT INTO delegacias values (1153, 'DM - Águas de Lindóia'); 
INSERT INTO delegacias values (1154, '006 DP - Jundiai'); 
INSERT INTO delegacias values (1155, '007 DP - Jundiai'); 
INSERT INTO delegacias values (1156, 'DM - Américo Brasiliense'); 
INSERT INTO delegacias values (1157, '003 DP - Franca'); 
INSERT INTO delegacias values (1158, '001 DP - Ituverava'); 
INSERT INTO delegacias values (1159, 'DM - Orlândia'); 
INSERT INTO delegacias values (1160, 'DM - Pontal'); 
INSERT INTO delegacias values (1161, 'DM - Balbinos'); 
INSERT INTO delegacias values (1162, 'DM - Sabino'); 
INSERT INTO delegacias values (1163, 'DM - Ocauçú'); 
INSERT INTO delegacias values (1164, '001 DP - Jales'); 
INSERT INTO delegacias values (1165, '001 DP - Mirassol'); 
INSERT INTO delegacias values (1166, '002 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (1167, '005 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (1168, '003 DP - Santos'); 
INSERT INTO delegacias values (1169, '003 DP - São Vicente'); 
INSERT INTO delegacias values (1170, 'DM - Coronel Macedo'); 
INSERT INTO delegacias values (1171, 'DM - Fartura'); 
INSERT INTO delegacias values (1172, 'DM - Anhembi'); 
INSERT INTO delegacias values (1173, 'DM - Araçariguama'); 
INSERT INTO delegacias values (1174, '003 DP - Itú'); 
INSERT INTO delegacias values (1175, '007 DP - Sorocaba'); 
INSERT INTO delegacias values (1176, '001 DP - Votorantim'); 
INSERT INTO delegacias values (1177, 'DM - Palmital'); 
INSERT INTO delegacias values (1178, 'DM - Álvares Machado'); 
INSERT INTO delegacias values (1179, '003 DP - Presidente Prudente'); 
INSERT INTO delegacias values (1180, '002 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (1181, '002 DP - Araras'); 
INSERT INTO delegacias values (1182, 'DM - Conchal'); 
INSERT INTO delegacias values (1183, '004 DP - Limeira'); 
INSERT INTO delegacias values (1184, '001 DP - Piracicaba'); 
INSERT INTO delegacias values (1185, '002 DP - Cotia'); 
INSERT INTO delegacias values (1186, 'DM - Rio Grande da Serra'); 
INSERT INTO delegacias values (1187, '026 DP - Sacomã'); 
INSERT INTO delegacias values (1188, '019 DP - Vila Maria'); 
INSERT INTO delegacias values (1189, 'DM - Cachoeira Pta.'); 
INSERT INTO delegacias values (1190, '004 DP - Jacareí'); 
INSERT INTO delegacias values (1191, '001 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (1192, '002 DP - Caraguatatuba'); 
INSERT INTO delegacias values (1193, '003 DP - São Sebastião'); 
INSERT INTO delegacias values (1194, 'DM - Castilho'); 
INSERT INTO delegacias values (1195, 'DM - Penapolis'); 
INSERT INTO delegacias values (1196, '003 DP - Atibaia'); 
INSERT INTO delegacias values (1197, 'DM - Nazaré Pta.'); 
INSERT INTO delegacias values (1198, 'DM - Socorro'); 
INSERT INTO delegacias values (1199, 'DM - Jarinú'); 
INSERT INTO delegacias values (1200, '002 DP - Jundiai'); 
INSERT INTO delegacias values (1201, 'DM - Sto. Antônio de Posse'); 
INSERT INTO delegacias values (1202, 'DM - Colina'); 
INSERT INTO delegacias values (1203, 'DM - Pirangi'); 
INSERT INTO delegacias values (1204, '008 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (1205, 'DM - São Simão'); 
INSERT INTO delegacias values (1206, 'DM - Serrana'); 
INSERT INTO delegacias values (1207, 'DM - Sta R. do Passa 4'); 
INSERT INTO delegacias values (1208, 'DM - Pindorama'); 
INSERT INTO delegacias values (1209, 'DM - Monte Aprazível'); 
INSERT INTO delegacias values (1210, '002 DP - Votuporanga'); 
INSERT INTO delegacias values (1211, 'DM - Itariri'); 
INSERT INTO delegacias values (1212, '007 DP - Santos'); 
INSERT INTO delegacias values (1213, 'DM - Cesário Lange'); 
INSERT INTO delegacias values (1214, 'DM - São Miguel Arcanjo'); 
INSERT INTO delegacias values (1215, '002 DP - Tatuí'); 
INSERT INTO delegacias values (1216, 'DM - Apiaí'); 
INSERT INTO delegacias values (1217, 'DM - Itararé'); 
INSERT INTO delegacias values (1218, '001 DP - Assis'); 
INSERT INTO delegacias values (1219, 'DM - Tarumã'); 
INSERT INTO delegacias values (1220, 'DM - Panorama'); 
INSERT INTO delegacias values (1221, '001 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (1222, 'DM - Brotas'); 
INSERT INTO delegacias values (1223, 'DM - Corumbataí'); 
INSERT INTO delegacias values (1224, 'DM - Aguaí'); 
INSERT INTO delegacias values (1225, '009 DP - Osasco'); 
INSERT INTO delegacias values (1226, '002 DP - Santo André'); 
INSERT INTO delegacias values (1227, 'DM - Juquitiba'); 
INSERT INTO delegacias values (1228, '004 DP - Consolação'); 
INSERT INTO delegacias values (1229, '096 DP - Monções'); 
INSERT INTO delegacias values (1230, '041 DP - Vila Rica'); 
INSERT INTO delegacias values (1231, '003 DP - Jacareí'); 
INSERT INTO delegacias values (1232, 'DM - Paraibuna'); 
INSERT INTO delegacias values (1233, 'DM - Santa Branca'); 
INSERT INTO delegacias values (1234, 'DM - Valinhos'); 
INSERT INTO delegacias values (1235, '001 DP - Amparo'); 
INSERT INTO delegacias values (1236, '002 DP - Amparo'); 
INSERT INTO delegacias values (1237, 'DM - Louveira'); 
INSERT INTO delegacias values (1238, 'DM - Morungaba'); 
INSERT INTO delegacias values (1239, 'DM - Dobrada'); 
INSERT INTO delegacias values (1240, 'DM - Gaviao Peixoto'); 
INSERT INTO delegacias values (1241, '003 DP - Bauru'); 
INSERT INTO delegacias values (1242, 'DM - Barra Bonita'); 
INSERT INTO delegacias values (1243, 'DM - Dois Córregos'); 
INSERT INTO delegacias values (1244, 'DM - Canitar'); 
INSERT INTO delegacias values (1245, 'DM - Populina'); 
INSERT INTO delegacias values (1246, '002 DP - Jales'); 
INSERT INTO delegacias values (1247, 'DM - Paulo de Faria'); 
INSERT INTO delegacias values (1248, '002 DP - Registro'); 
INSERT INTO delegacias values (1249, 'DM - Campina Monte Alegre'); 
INSERT INTO delegacias values (1250, '001 DP - Capão Bonito'); 
INSERT INTO delegacias values (1251, 'DM - Piedade'); 
INSERT INTO delegacias values (1252, '001 DP - Salto'); 
INSERT INTO delegacias values (1253, '002 DP - Votorantim'); 
INSERT INTO delegacias values (1254, '002 DP - Assis'); 
INSERT INTO delegacias values (1255, '006 DP - Presidente Prudente'); 
INSERT INTO delegacias values (1256, 'DM - Hortolândia'); 
INSERT INTO delegacias values (1257, '007 DP - Piracicaba'); 
INSERT INTO delegacias values (1258, '005 DP - Osasco'); 
INSERT INTO delegacias values (1259, '005 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (1260, '007 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (1261, '001 DP - Itapecerica da Serra'); 
INSERT INTO delegacias values (1262, '015 DP - Itaim Bibi'); 
INSERT INTO delegacias values (1263, '091 DP - Ceagesp'); 
INSERT INTO delegacias values (1264, '052 DP - Parque São Jorge'); 
INSERT INTO delegacias values (1265, '002 DP - Andradina'); 
INSERT INTO delegacias values (1266, 'DM - Santo Ant. Aracangua'); 
INSERT INTO delegacias values (1267, '001 DP - Cabreuva'); 
INSERT INTO delegacias values (1268, 'DM - Borborema'); 
INSERT INTO delegacias values (1269, 'DM - Santa Lúcia'); 
INSERT INTO delegacias values (1270, '001 DP - Barretos'); 
INSERT INTO delegacias values (1271, 'DM - Buritizal'); 
INSERT INTO delegacias values (1272, 'DM - Ituverava'); 
INSERT INTO delegacias values (1273, '003 DP - Jaú'); 
INSERT INTO delegacias values (1274, '004 DP - Jaú'); 
INSERT INTO delegacias values (1275, 'DM - Garça'); 
INSERT INTO delegacias values (1276, '002 DP - Tupã'); 
INSERT INTO delegacias values (1277, 'DM - Bady Bassit'); 
INSERT INTO delegacias values (1278, '001 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (1279, 'DM - União Pta.'); 
INSERT INTO delegacias values (1280, '001 DP - Mongaguá'); 
INSERT INTO delegacias values (1281, 'DM - Juquiá'); 
INSERT INTO delegacias values (1282, '004 DP - Botucatu'); 
INSERT INTO delegacias values (1283, '001 DP - Tatuí'); 
INSERT INTO delegacias values (1284, 'DM - Iperó'); 
INSERT INTO delegacias values (1285, '004 DP - Sorocaba'); 
INSERT INTO delegacias values (1286, '004 DP - Assis'); 
INSERT INTO delegacias values (1287, 'DM - Ibirarema'); 
INSERT INTO delegacias values (1288, 'DM - Vargem Grande do Sul'); 
INSERT INTO delegacias values (1289, '001 DP - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (1290, '002 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (1291, '081 DP - Belém'); 
INSERT INTO delegacias values (1292, '001 DP - Cruzeiro'); 
INSERT INTO delegacias values (1293, 'DM - Roseira'); 
INSERT INTO delegacias values (1294, 'DM - Igaratá'); 
INSERT INTO delegacias values (1295, 'DM - Natividade da Serrra'); 
INSERT INTO delegacias values (1296, 'DM - Avanhandava'); 
INSERT INTO delegacias values (1297, '002 DP - Araraquara'); 
INSERT INTO delegacias values (1298, 'DM - Pradópolis'); 
INSERT INTO delegacias values (1299, 'DM - Arealva'); 
INSERT INTO delegacias values (1300, 'DM - Reginópolis'); 
INSERT INTO delegacias values (1301, '001 DP - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (1302, 'DM - Estrela do Oeste'); 
INSERT INTO delegacias values (1303, 'DM - São João das Duas Pontes'); 
INSERT INTO delegacias values (1304, 'DM - Novo Horizonte'); 
INSERT INTO delegacias values (1305, 'DM - Itaberá'); 
INSERT INTO delegacias values (1306, 'DM - Nova Campina'); 
INSERT INTO delegacias values (1307, '001 DP - Paraguaçú Pta.'); 
INSERT INTO delegacias values (1308, 'DM - Capivari'); 
INSERT INTO delegacias values (1309, 'DM - Itirapina'); 
INSERT INTO delegacias values (1310, '005 DP - Guarulhos'); 
INSERT INTO delegacias values (1311, 'Delegacia Aeroporto Int. SP - Guarulhos'); 
INSERT INTO delegacias values (1312, 'DM - Guararema'); 
INSERT INTO delegacias values (1313, '004 DP - Osasco'); 
INSERT INTO delegacias values (1314, '001 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (1315, '036 DP - Vila Mariana'); 
INSERT INTO delegacias values (1316, '004 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (1317, 'DM - Auriflama'); 
INSERT INTO delegacias values (1318, 'DM - Lindóia'); 
INSERT INTO delegacias values (1319, 'DM - Itupeva'); 
INSERT INTO delegacias values (1320, '005 DP - Jundiai'); 
INSERT INTO delegacias values (1321, '001 DP - Itapira'); 
INSERT INTO delegacias values (1322, '001 DP - Porto Ferreira'); 
INSERT INTO delegacias values (1323, 'DM - Cafelândia'); 
INSERT INTO delegacias values (1324, 'DM - Echaporã'); 
INSERT INTO delegacias values (1325, '001 DP - Ourinhos'); 
INSERT INTO delegacias values (1326, 'DM - Sta. Fé do Sul'); 
INSERT INTO delegacias values (1327, 'DM - Onda Verde'); 
INSERT INTO delegacias values (1328, 'DM - Potirendaba'); 
INSERT INTO delegacias values (1329, 'DM - Guarei'); 
INSERT INTO delegacias values (1330, '003 DP - Itapetininga'); 
INSERT INTO delegacias values (1331, '003 DP - Americana'); 
INSERT INTO delegacias values (1332, '003 DP - Limeira'); 
INSERT INTO delegacias values (1333, '003 DP - São João da Boa Vista'); 
INSERT INTO delegacias values (1334, '002 DP - de Barueri'); 
INSERT INTO delegacias values (1335, '035 DP - Jabaquara'); 
INSERT INTO delegacias values (1336, 'DM - Cunha'); 
INSERT INTO delegacias values (1337, 'DM - Itapura'); 
INSERT INTO delegacias values (1338, 'DM - Vargem'); 
INSERT INTO delegacias values (1339, 'DM - Itapira'); 
INSERT INTO delegacias values (1340, 'DM - Altair'); 
INSERT INTO delegacias values (1341, '002 DP - Barretos'); 
INSERT INTO delegacias values (1342, '003 DP - Barretos'); 
INSERT INTO delegacias values (1343, 'DM - Sta. Rosa Viterbo'); 
INSERT INTO delegacias values (1344, '001 DP - São Joaquim da Barra'); 
INSERT INTO delegacias values (1345, 'DM - Bocaina'); 
INSERT INTO delegacias values (1346, 'DM - Taquarituba'); 
INSERT INTO delegacias values (1347, '003 DP - Sorocaba'); 
INSERT INTO delegacias values (1348, '001 DP - Adamantina'); 
INSERT INTO delegacias values (1349, 'DM - Sta. Mercedes'); 
INSERT INTO delegacias values (1350, '003 DP - Pirassununga'); 
INSERT INTO delegacias values (1351, 'DM - Salesópolis'); 
INSERT INTO delegacias values (1352, '057 DP - Parque da Moóca'); 
INSERT INTO delegacias values (1353, 'DM - Colômbia'); 
INSERT INTO delegacias values (1354, 'DM - Severínia'); 
INSERT INTO delegacias values (1355, '003 DP - Bebedouro'); 
INSERT INTO delegacias values (1356, 'DM - Batatais'); 
INSERT INTO delegacias values (1357, 'DM - Igarapava'); 
INSERT INTO delegacias values (1358, '003 DP - São Carlos'); 
INSERT INTO delegacias values (1359, 'DM - Barrinha'); 
INSERT INTO delegacias values (1360, 'DM - Vera Cruz'); 
INSERT INTO delegacias values (1361, 'DM - Ribeirão do Sul'); 
INSERT INTO delegacias values (1362, '003 DP - Tupã'); 
INSERT INTO delegacias values (1363, 'DM - Ouroeste'); 
INSERT INTO delegacias values (1364, 'DM - Sales'); 
INSERT INTO delegacias values (1365, 'DM - Pontes Gestal'); 
INSERT INTO delegacias values (1366, 'DM - Peruíbe'); 
INSERT INTO delegacias values (1367, 'DM - Cananéia'); 
INSERT INTO delegacias values (1368, 'DM - Areiópolis'); 
INSERT INTO delegacias values (1369, '004 DP - Itapeva'); 
INSERT INTO delegacias values (1370, 'DM - Rib. Grande'); 
INSERT INTO delegacias values (1371, 'DM - Mir. Paranapanema'); 
INSERT INTO delegacias values (1372, '001 DP - Araras'); 
INSERT INTO delegacias values (1373, 'DM - Iracemápolis'); 
INSERT INTO delegacias values (1374, '003 DP - Guarulhos'); 
