INSERT INTO delegacias values (1, '002 DP - Bom Retiro'); 
INSERT INTO delegacias values (2, '008 DP - Brás'); 
INSERT INTO delegacias values (3, '078 DP - Jardins'); 
INSERT INTO delegacias values (4, '017 DP - Ipiranga'); 
INSERT INTO delegacias values (5, '083 DP - Parque Bristol'); 
INSERT INTO delegacias values (6, '014 DP - Pinheiros'); 
INSERT INTO delegacias values (7, '023 DP - Perdizes'); 
INSERT INTO delegacias values (8, '037 DP - Campo Limpo'); 
INSERT INTO delegacias values (9, '046 DP - Perus'); 
INSERT INTO delegacias values (10, '075 DP - Jardim Arpoador'); 
INSERT INTO delegacias values (11, '087 DP - Vila Pereira Barreto'); 
INSERT INTO delegacias values (12, '089 DP - Portal do Morumbi'); 
INSERT INTO delegacias values (13, '013 DP - Casa Verde'); 
INSERT INTO delegacias values (14, '038 DP - Vila Amália'); 
INSERT INTO delegacias values (15, '073 DP - Jaçanã'); 
INSERT INTO delegacias values (16, '074 DP - Jaraguá'); 
INSERT INTO delegacias values (17, '010 DP - Penha de França'); 
INSERT INTO delegacias values (18, '058 DP - Vila Formosa'); 
INSERT INTO delegacias values (19, '011 DP - Santo Amaro'); 
INSERT INTO delegacias values (20, '025 DP - Parelheiros'); 
INSERT INTO delegacias values (21, '047 DP - Capão Redondo'); 
INSERT INTO delegacias values (22, '085 DP - Jardim Mirna'); 
INSERT INTO delegacias values (23, '092 DP - Parque Santo Antônio'); 
INSERT INTO delegacias values (24, '098 DP - Jardim Míriam'); 
INSERT INTO delegacias values (25, '100 DP - Jardim Herculano'); 
INSERT INTO delegacias values (26, '101 DP - Jardim das Imbuias'); 
INSERT INTO delegacias values (27, '059 DP - Jardim Noemia'); 
INSERT INTO delegacias values (28, '062 DP - Ermelino Matarazzo'); 
INSERT INTO delegacias values (29, '063 DP - Vila Jacuí'); 
INSERT INTO delegacias values (30, '068 DP - Lajeado'); 
INSERT INTO delegacias values (31, '044 DP - Guaianazes'); 
INSERT INTO delegacias values (32, '054 DP - Cidade Tiradentes'); 
INSERT INTO delegacias values (33, '055 DP - Parque São Rafael'); 
INSERT INTO delegacias values (34, '070 DP - Vila Ema'); 
INSERT INTO delegacias values (35, '002 DP - Cruzeiro'); 
INSERT INTO delegacias values (36, 'DM - Aparecida'); 
INSERT INTO delegacias values (37, 'DM - Canas'); 
INSERT INTO delegacias values (38, '002 DP - Guaratinguetá'); 
INSERT INTO delegacias values (39, '001 DP - Lorena'); 
INSERT INTO delegacias values (40, '002 DP - Lorena'); 
INSERT INTO delegacias values (41, 'DM - Potim'); 
INSERT INTO delegacias values (42, '001 DP - Jacareí'); 
INSERT INTO delegacias values (43, '003 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (44, '006 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (45, '008 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (46, 'DM - Caraguatatuba'); 
INSERT INTO delegacias values (47, '001 DP - São Sebastião'); 
INSERT INTO delegacias values (48, 'DM - Ubatuba'); 
INSERT INTO delegacias values (49, '001 DP - Campos do Jordão'); 
INSERT INTO delegacias values (50, '002 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (51, '003 DP - Taubaté'); 
INSERT INTO delegacias values (52, 'DM - Pereira Barreto'); 
INSERT INTO delegacias values (53, 'DM - Suzanópolis'); 
INSERT INTO delegacias values (54, '003 DP - Araçatuba'); 
INSERT INTO delegacias values (55, '004 DP - Araçatuba'); 
INSERT INTO delegacias values (56, 'DM - Lourdes'); 
INSERT INTO delegacias values (57, '003 DP - Campinas'); 
INSERT INTO delegacias values (58, '004 DP - Campinas'); 
INSERT INTO delegacias values (59, '007 DP - Campinas'); 
INSERT INTO delegacias values (60, '010 DP - Campinas'); 
INSERT INTO delegacias values (61, '002 DP - Campinas'); 
INSERT INTO delegacias values (62, '008 DP - Campinas'); 
INSERT INTO delegacias values (63, '009 DP - Campinas'); 
INSERT INTO delegacias values (64, '011 DP - Campinas'); 
INSERT INTO delegacias values (65, '001 DP - Indaiatuba'); 
INSERT INTO delegacias values (66, '002 DP - Atibaia'); 
INSERT INTO delegacias values (67, '002 DP - Bragança Pta.'); 
INSERT INTO delegacias values (68, 'DM - Joanópolis'); 
INSERT INTO delegacias values (69, 'DM - Campo Limpo Pta.'); 
INSERT INTO delegacias values (70, '003 DP - Jundiai'); 
INSERT INTO delegacias values (71, 'DM - Várzea Pta.'); 
INSERT INTO delegacias values (72, '002 DP - Itapira'); 
INSERT INTO delegacias values (73, '002 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (74, '003 DP - Araraquara'); 
INSERT INTO delegacias values (75, 'DM - Ibitinga'); 
INSERT INTO delegacias values (76, 'DM - Itápolis'); 
INSERT INTO delegacias values (77, 'DM - Olímpia'); 
INSERT INTO delegacias values (78, 'DM - Taiaçu'); 
INSERT INTO delegacias values (79, 'DM - Cristais Pta.'); 
INSERT INTO delegacias values (80, '002 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (81, 'DM - Porto Ferreira'); 
INSERT INTO delegacias values (82, '004 DP - São Carlos'); 
INSERT INTO delegacias values (83, 'DM - Guariba'); 
INSERT INTO delegacias values (84, 'DM - Sertãozinho'); 
INSERT INTO delegacias values (85, 'DM - Agudos'); 
INSERT INTO delegacias values (86, '002 DP - Lins'); 
INSERT INTO delegacias values (87, 'DM - Lupércio'); 
INSERT INTO delegacias values (88, '001 DP - Marília'); 
INSERT INTO delegacias values (89, '002 DP - Marília'); 
INSERT INTO delegacias values (90, 'DM - Mira Estrela'); 
INSERT INTO delegacias values (91, 'DM - Santa Albertina'); 
INSERT INTO delegacias values (92, 'DM - Urãnia'); 
INSERT INTO delegacias values (93, 'DM - Icém'); 
INSERT INTO delegacias values (94, '003 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (95, '004 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (96, 'DM - Tanabi'); 
INSERT INTO delegacias values (97, '002 DP - Itanhaem'); 
INSERT INTO delegacias values (98, '002 DP - Mongaguá'); 
INSERT INTO delegacias values (99, 'DM - Mongaguá'); 
INSERT INTO delegacias values (100, 'DM - Barra do Turvo'); 
INSERT INTO delegacias values (101, 'DM - Iguape'); 
INSERT INTO delegacias values (102, '002 DP - Cubatão'); 
INSERT INTO delegacias values (103, '002 DP - Guarujá'); 
INSERT INTO delegacias values (104, 'DM - Guarujá'); 
INSERT INTO delegacias values (105, '001 DP - Praia Grande'); 
INSERT INTO delegacias values (106, '002 DP - Praia Grande'); 
INSERT INTO delegacias values (107, '003 DP - Praia Grande'); 
INSERT INTO delegacias values (108, 'DM - Praia Grande'); 
INSERT INTO delegacias values (109, '001 DP - Santos'); 
INSERT INTO delegacias values (110, '002 DP - Santos'); 
INSERT INTO delegacias values (111, '001 DP - São Vicente'); 
INSERT INTO delegacias values (112, '002 DP - São Vicente'); 
INSERT INTO delegacias values (113, 'DM - Iaras'); 
INSERT INTO delegacias values (114, 'DM - Porangaba'); 
INSERT INTO delegacias values (115, '001 DP - Itapetininga'); 
INSERT INTO delegacias values (116, 'DM - Tatuí'); 
INSERT INTO delegacias values (117, 'DM - Capão Bonito'); 
INSERT INTO delegacias values (118, '001 DP - Itú'); 
INSERT INTO delegacias values (119, 'DM - São Roque'); 
INSERT INTO delegacias values (120, '002 DP - Sorocaba'); 
INSERT INTO delegacias values (121, '005 DP - Sorocaba'); 
INSERT INTO delegacias values (122, '006 DP - Sorocaba'); 
INSERT INTO delegacias values (123, 'DM - Votorantim'); 
INSERT INTO delegacias values (124, 'DM - Paraguaçú Pta.'); 
INSERT INTO delegacias values (125, '001 DP - Presidente Prudente'); 
INSERT INTO delegacias values (126, 'DM - Cosmópolis'); 
INSERT INTO delegacias values (127, 'DM - Engenheiro Coelho'); 
INSERT INTO delegacias values (128, '001 DP - Hortolândia'); 
INSERT INTO delegacias values (129, 'DM - Monte Mor'); 
INSERT INTO delegacias values (130, '002 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (131, '002 DP - Sumaré'); 
INSERT INTO delegacias values (132, '003 DP - Sumaré'); 
INSERT INTO delegacias values (133, '001 DP - Leme'); 
INSERT INTO delegacias values (134, '001 DP - Pirassununga'); 
INSERT INTO delegacias values (135, '002 DP - Piracicaba'); 
INSERT INTO delegacias values (136, '004 DP - Piracicaba'); 
INSERT INTO delegacias values (137, '001 DP - Rio Claro'); 
INSERT INTO delegacias values (138, '002 DP - Rio Claro'); 
INSERT INTO delegacias values (139, 'DM - Espírito Sto. do Pinhal'); 
INSERT INTO delegacias values (140, '001 DP - Carapicuiba'); 
INSERT INTO delegacias values (141, '002 DP - Carapicuiba'); 
INSERT INTO delegacias values (142, 'DM - Cotia'); 
INSERT INTO delegacias values (143, 'DM - Itapevi'); 
INSERT INTO delegacias values (144, 'DM - Jandira'); 
INSERT INTO delegacias values (145, 'DM - Pirapora do Bom Jesus'); 
INSERT INTO delegacias values (146, 'DM - Santana do Parnaiba'); 
INSERT INTO delegacias values (147, '002 DP - Diadema'); 
INSERT INTO delegacias values (148, '003 DP - Diadema'); 
INSERT INTO delegacias values (149, '001 DP - Caieiras'); 
INSERT INTO delegacias values (150, 'DM - Cajamar'); 
INSERT INTO delegacias values (151, 'DM - Francisco Morato'); 
INSERT INTO delegacias values (152, 'DM - Mairiporã'); 
INSERT INTO delegacias values (153, 'DM - Aruja'); 
INSERT INTO delegacias values (154, '001 DP - Guarulhos'); 
INSERT INTO delegacias values (155, '002 DP - Guarulhos'); 
INSERT INTO delegacias values (156, '004 DP - Guarulhos'); 
INSERT INTO delegacias values (157, '007 DP - Guarulhos'); 
INSERT INTO delegacias values (158, '009 DP - Guarulhos'); 
INSERT INTO delegacias values (159, 'DM - Santa Isabel'); 
INSERT INTO delegacias values (160, 'DM - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (161, '001 DP - Itaquaquecetuba'); 
INSERT INTO delegacias values (162, 'DM - Itaquaquecetuba'); 
INSERT INTO delegacias values (163, '003 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (164, '004 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (165, 'DM - Poá'); 
INSERT INTO delegacias values (166, 'DM - Suzano'); 
INSERT INTO delegacias values (167, '002 DP - Osasco'); 
INSERT INTO delegacias values (168, '003 DP - Osasco'); 
INSERT INTO delegacias values (169, '010 DP - Osasco'); 
INSERT INTO delegacias values (170, '001 DP - Mauá'); 
INSERT INTO delegacias values (171, '002 DP - Mauá'); 
INSERT INTO delegacias values (172, '003 DP - Mauá'); 
INSERT INTO delegacias values (173, 'DM - Ribeirão Pires'); 
INSERT INTO delegacias values (174, '003 DP - Santo André'); 
INSERT INTO delegacias values (175, '005 DP - Santo André'); 
INSERT INTO delegacias values (176, '006 DP - Santo André'); 
INSERT INTO delegacias values (177, '003 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (178, '004 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (179, '006 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (180, '008 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (181, '001 DP - Embú'); 
INSERT INTO delegacias values (182, 'DM - Embú'); 
INSERT INTO delegacias values (183, 'DM - Embú Guaçú'); 
INSERT INTO delegacias values (184, 'DM - Itapecerica da Serra'); 
INSERT INTO delegacias values (185, '002 DP - Taboão da Serra'); 
INSERT INTO delegacias values (186, '001 DP - Sé'); 
INSERT INTO delegacias values (187, '006 DP - Cambuci'); 
INSERT INTO delegacias values (188, '077 DP - Santa Cecília'); 
INSERT INTO delegacias values (189, '009 DP - Carandiru'); 
INSERT INTO delegacias values (190, '039 DP - Vila Gustavo'); 
INSERT INTO delegacias values (191, '045 DP - Vila Brasilândia'); 
INSERT INTO delegacias values (192, '072 DP - Vila Penteado'); 
INSERT INTO delegacias values (193, '030 DP - Tatuapé'); 
INSERT INTO delegacias values (194, '048 DP - Cidade Dutra'); 
INSERT INTO delegacias values (195, '080 DP - Vila Joaniza'); 
INSERT INTO delegacias values (196, '099 DP - Campo Grande'); 
INSERT INTO delegacias values (197, '022 DP - São Miguel Paulista'); 
INSERT INTO delegacias values (198, '024 DP - Ponte Rasa'); 
INSERT INTO delegacias values (199, '050 DP - Itaim Paulista'); 
INSERT INTO delegacias values (200, '065 DP - Artur Alvim'); 
INSERT INTO delegacias values (201, '067 DP - Jardim Robru'); 
INSERT INTO delegacias values (202, '049 DP - São Mateus'); 
INSERT INTO delegacias values (203, '053 DP - Parque do Carmo'); 
INSERT INTO delegacias values (204, '066 DP - Vale do Aricanduva'); 
INSERT INTO delegacias values (205, '069 DP - Teotônio Vilela'); 
INSERT INTO delegacias values (206, '003 DP - Cruzeiro'); 
INSERT INTO delegacias values (207, '001 DP - Guaratinguetá'); 
INSERT INTO delegacias values (208, '003 DP - Guaratinguetá'); 
INSERT INTO delegacias values (209, 'DM - Caçapava'); 
INSERT INTO delegacias values (210, '002 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (211, '002 DP - São Sebastião'); 
INSERT INTO delegacias values (212, '004 DP - São Sebastião'); 
INSERT INTO delegacias values (213, 'DM - Campos do Jordão'); 
INSERT INTO delegacias values (214, 'DM - São Bento do Sapucaí'); 
INSERT INTO delegacias values (215, 'DM - Tremembé'); 
INSERT INTO delegacias values (216, '002 DP - Araçatuba'); 
INSERT INTO delegacias values (217, 'DM - Guararapes'); 
INSERT INTO delegacias values (218, 'DM - Piracaia'); 
INSERT INTO delegacias values (219, 'DM - Itatiba'); 
INSERT INTO delegacias values (220, '001 DP - Jundiai'); 
INSERT INTO delegacias values (221, '001 DP - Várzea Pta.'); 
INSERT INTO delegacias values (222, '003 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (223, '003 DP - Mogi Mirim'); 
INSERT INTO delegacias values (224, 'DM - Matão'); 
INSERT INTO delegacias values (225, 'DM - Rincão'); 
INSERT INTO delegacias values (226, 'DM - Cajobi'); 
INSERT INTO delegacias values (227, '001 DP - Guaíra'); 
INSERT INTO delegacias values (228, '001 DP - Batatais'); 
INSERT INTO delegacias values (229, '002 DP - Franca'); 
INSERT INTO delegacias values (230, '005 DP - Franca'); 
INSERT INTO delegacias values (231, 'DM - Restinga'); 
INSERT INTO delegacias values (232, 'DM - Cravinhos'); 
INSERT INTO delegacias values (233, '003 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (234, '004 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (235, '005 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (236, '005 DP - São Carlos'); 
INSERT INTO delegacias values (237, 'DM - Morro Agudo'); 
INSERT INTO delegacias values (238, 'DM - Pitangueiras'); 
INSERT INTO delegacias values (239, '002 DP - Bauru'); 
INSERT INTO delegacias values (240, 'DM - Lençóis Paulista'); 
INSERT INTO delegacias values (241, 'DM - Pederneiras'); 
INSERT INTO delegacias values (242, '001 DP - Jaú'); 
INSERT INTO delegacias values (243, 'DM - Getulina'); 
INSERT INTO delegacias values (244, '003 DP - Lins'); 
INSERT INTO delegacias values (245, 'DM - Ipaussu'); 
INSERT INTO delegacias values (246, '002 DP - Ourinhos'); 
INSERT INTO delegacias values (247, 'DM - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (248, '003 DP - Catanduva'); 
INSERT INTO delegacias values (249, 'DM - Valentim Gentil'); 
INSERT INTO delegacias values (250, '001 DP - Votuporanga'); 
INSERT INTO delegacias values (251, 'DM - Itaporanga'); 
INSERT INTO delegacias values (252, 'DM - Sarutaiá'); 
INSERT INTO delegacias values (253, '003 DP - Botucatu'); 
INSERT INTO delegacias values (254, 'DM - Pardinho'); 
INSERT INTO delegacias values (255, 'DM - Ribeira'); 
INSERT INTO delegacias values (256, 'DM - Ibiúna'); 
INSERT INTO delegacias values (257, '002 DP - Itú'); 
INSERT INTO delegacias values (258, '004 DP - Itú'); 
INSERT INTO delegacias values (259, 'DM - Mairinque'); 
INSERT INTO delegacias values (260, '002 DP - Salto'); 
INSERT INTO delegacias values (261, '008 DP - Sorocaba'); 
INSERT INTO delegacias values (262, '003 DP - Votorantim'); 
INSERT INTO delegacias values (263, 'DM - Junqueirópolis'); 
INSERT INTO delegacias values (264, 'DM - Tupi Pta.'); 
INSERT INTO delegacias values (265, '001 DP - Rosana'); 
INSERT INTO delegacias values (266, 'DM - Sto. Anastácio'); 
INSERT INTO delegacias values (267, '002 DP - Americana'); 
INSERT INTO delegacias values (268, '002 DP - Hortolândia'); 
INSERT INTO delegacias values (269, 'DM - Nova Odessa'); 
INSERT INTO delegacias values (270, '003 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (271, 'DM - Casa Branca'); 
INSERT INTO delegacias values (272, 'DM - Tapiratiba'); 
INSERT INTO delegacias values (273, 'DM - Cordeirópolis'); 
INSERT INTO delegacias values (274, '001 DP - Limeira'); 
INSERT INTO delegacias values (275, '003 DP - Piracicaba'); 
INSERT INTO delegacias values (276, '005 DP - Piracicaba'); 
INSERT INTO delegacias values (277, '003 DP - Rio Claro'); 
INSERT INTO delegacias values (278, 'DM - Sta. Gertrudes'); 
INSERT INTO delegacias values (279, '001 DP - Cotia'); 
INSERT INTO delegacias values (280, 'DM - Vargem Grande Paulista'); 
INSERT INTO delegacias values (281, '001 DP - Diadema'); 
INSERT INTO delegacias values (282, '004 DP - Diadema'); 
INSERT INTO delegacias values (283, '001 DP - Mairiporã'); 
INSERT INTO delegacias values (284, '006 DP - Guarulhos'); 
INSERT INTO delegacias values (285, '008 DP - Osasco'); 
INSERT INTO delegacias values (286, '004 DP - Mauá'); 
INSERT INTO delegacias values (287, '003 DP - Campos Elísios'); 
INSERT INTO delegacias values (288, '005 DP - Aclimação'); 
INSERT INTO delegacias values (289, '016 DP - Vila Clementino'); 
INSERT INTO delegacias values (290, '033 DP - Pirituba'); 
INSERT INTO delegacias values (291, '093 DP - Jaguaré'); 
INSERT INTO delegacias values (292, '020 DP - Água Fria'); 
INSERT INTO delegacias values (293, '028 DP - Freguesia do Ó'); 
INSERT INTO delegacias values (294, '029 DP - Vila Diva'); 
INSERT INTO delegacias values (295, '042 DP - Parque São Lucas'); 
INSERT INTO delegacias values (296, '043 DP - Cidade Ademar'); 
INSERT INTO delegacias values (297, '102 DP - Socorro'); 
INSERT INTO delegacias values (298, '032 DP - Itaquera'); 
INSERT INTO delegacias values (299, '064 DP - Cidade A E Carvalho'); 
INSERT INTO delegacias values (300, 'DM - Queluz'); 
INSERT INTO delegacias values (301, '002 DP - Jacareí'); 
INSERT INTO delegacias values (302, '001 DP - Caraguatatuba'); 
INSERT INTO delegacias values (303, '001 DP - Taubaté'); 
INSERT INTO delegacias values (304, '004 DP - Taubaté'); 
INSERT INTO delegacias values (305, 'DM - Lavinia'); 
INSERT INTO delegacias values (306, '001 DP - Birigui'); 
INSERT INTO delegacias values (307, 'DM - Indaiatuba'); 
INSERT INTO delegacias values (308, 'DM - Atibaia'); 
INSERT INTO delegacias values (309, '003 DP - Bragança Pta.'); 
INSERT INTO delegacias values (310, '001 DP - Itatiba'); 
INSERT INTO delegacias values (311, '001 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (312, '002 DP - Mogi Mirim'); 
INSERT INTO delegacias values (313, '001 DP - Araraquara'); 
INSERT INTO delegacias values (314, '001 DP - Matao'); 
INSERT INTO delegacias values (315, '002 DP - Bebedouro'); 
INSERT INTO delegacias values (316, '004 DP - Franca'); 
INSERT INTO delegacias values (317, 'DM - Miguelópolis'); 
INSERT INTO delegacias values (318, 'DM - Patrocínio Pta.'); 
INSERT INTO delegacias values (319, 'DM - Jardinópolis'); 
INSERT INTO delegacias values (320, '001 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (321, '007 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (322, 'DM - Ibaté'); 
INSERT INTO delegacias values (323, '001 DP - São Carlos'); 
INSERT INTO delegacias values (324, '002 DP - São Carlos'); 
INSERT INTO delegacias values (325, '001 DP - Jaboticabal'); 
INSERT INTO delegacias values (326, '001 DP - Bauru'); 
INSERT INTO delegacias values (327, '004 DP - Bauru'); 
INSERT INTO delegacias values (328, 'DM - Cabrália Paulista'); 
INSERT INTO delegacias values (329, 'DM - Macatuba'); 
INSERT INTO delegacias values (330, 'DM - Igaraçu do Tietê'); 
INSERT INTO delegacias values (331, 'DM - Guaiçara'); 
INSERT INTO delegacias values (332, 'DM - Guaimbe'); 
INSERT INTO delegacias values (333, '001 DP - Lins'); 
INSERT INTO delegacias values (334, '003 DP - Ourinhos'); 
INSERT INTO delegacias values (335, 'DM - Parapuã'); 
INSERT INTO delegacias values (336, 'DM - José Bonifácio'); 
INSERT INTO delegacias values (337, '007 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (338, 'DM - Sebastianópolis do Sul'); 
INSERT INTO delegacias values (339, '003 DP - Votuporanga'); 
INSERT INTO delegacias values (340, '003 DP - Itanhaem'); 
INSERT INTO delegacias values (341, '001 DP - Peruíbe'); 
INSERT INTO delegacias values (342, 'DM - Sete Barras'); 
INSERT INTO delegacias values (343, 'DM - Bertioga'); 
INSERT INTO delegacias values (344, '001 DP - Guarujá'); 
INSERT INTO delegacias values (345, '004 DP - Santos'); 
INSERT INTO delegacias values (346, 'DM - Itaí'); 
INSERT INTO delegacias values (347, 'DM - Bofete'); 
INSERT INTO delegacias values (348, 'DM - Itatinga'); 
INSERT INTO delegacias values (349, 'DM - Boituva'); 
INSERT INTO delegacias values (350, 'DM - Buri'); 
INSERT INTO delegacias values (351, 'DM - Salto de Pirapora'); 
INSERT INTO delegacias values (352, '001 DP - Sorocaba'); 
INSERT INTO delegacias values (353, '010 DP - Sorocaba'); 
INSERT INTO delegacias values (354, '011 DP - Sorocaba'); 
INSERT INTO delegacias values (355, '003 DP - Assis'); 
INSERT INTO delegacias values (356, 'DM - Pirapozinho'); 
INSERT INTO delegacias values (357, '002 DP - Presidente Prudente'); 
INSERT INTO delegacias values (358, 'DM - Regente Feijó'); 
INSERT INTO delegacias values (359, 'DM - Presidente Epitácio'); 
INSERT INTO delegacias values (360, '001 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (361, '004 DP - Americana'); 
INSERT INTO delegacias values (362, 'DM - Artur Nogueira'); 
INSERT INTO delegacias values (363, '001 DP - Sumaré'); 
INSERT INTO delegacias values (364, '004 DP - Sumaré'); 
INSERT INTO delegacias values (365, 'DM - Itobi'); 
INSERT INTO delegacias values (366, 'DM - Charqueada'); 
INSERT INTO delegacias values (367, 'DM - São Sebastião da Gama'); 
INSERT INTO delegacias values (368, '001 DP - Barueri'); 
INSERT INTO delegacias values (369, 'DM - Barueri'); 
INSERT INTO delegacias values (370, '003 DP - Carapicuiba'); 
INSERT INTO delegacias values (371, '001 DP - Cajamar'); 
INSERT INTO delegacias values (372, 'DM - Franco da Rocha'); 
INSERT INTO delegacias values (373, '008 DP - Guarulhos'); 
INSERT INTO delegacias values (374, '001 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (375, '002 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (376, '007 DP - Osasco'); 
INSERT INTO delegacias values (377, 'DM - São Lourenço da Serra'); 
INSERT INTO delegacias values (378, '001 DP - Taboão da Serra'); 
INSERT INTO delegacias values (379, '095 DP - Heliópolis'); 
INSERT INTO delegacias values (380, '097 DP - Americanópolis'); 
INSERT INTO delegacias values (381, '034 DP - Vila Sonia'); 
INSERT INTO delegacias values (382, '051 DP - Butantã'); 
INSERT INTO delegacias values (383, '040 DP - Vila Santa Maria'); 
INSERT INTO delegacias values (384, '090 DP - Parque Novo Mundo'); 
INSERT INTO delegacias values (385, '021 DP - Vila Matilde'); 
INSERT INTO delegacias values (386, '103 DP - Cohab Itaquera'); 
INSERT INTO delegacias values (387, 'DM - Monteiro Lobato'); 
INSERT INTO delegacias values (388, '005 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (389, '003 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (390, '002 DP - Taubaté'); 
INSERT INTO delegacias values (391, '001 DP - Andradina'); 
INSERT INTO delegacias values (392, 'DM - Ilha Solteira'); 
INSERT INTO delegacias values (393, 'DM - Buritama'); 
INSERT INTO delegacias values (394, '001 DP - Penapolis'); 
INSERT INTO delegacias values (395, '005 DP - Campinas'); 
INSERT INTO delegacias values (396, '001 DP - Atibaia'); 
INSERT INTO delegacias values (397, 'DM - Jaguariúna'); 
INSERT INTO delegacias values (398, '004 DP - Araraquara'); 
INSERT INTO delegacias values (399, 'DM - Tabatinga'); 
INSERT INTO delegacias values (400, 'DM - Guaíra'); 
INSERT INTO delegacias values (401, 'DM - Vista Alegre/Alto'); 
INSERT INTO delegacias values (402, 'DM - Guará'); 
INSERT INTO delegacias values (403, '006 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (404, '002 DP - Jaboticabal'); 
INSERT INTO delegacias values (405, 'DM - Monte Alto'); 
INSERT INTO delegacias values (406, 'DM - Iacanga'); 
INSERT INTO delegacias values (407, 'DM - Itajú'); 
INSERT INTO delegacias values (408, '002 DP - Jaú'); 
INSERT INTO delegacias values (409, 'DM - Promissão'); 
INSERT INTO delegacias values (410, 'DM - Alvinlândia'); 
INSERT INTO delegacias values (411, '004 DP - Marília'); 
INSERT INTO delegacias values (412, '004 DP - Catanduva'); 
INSERT INTO delegacias values (413, 'DM - Palmares Pta.'); 
INSERT INTO delegacias values (414, 'DM - Tabapuã'); 
INSERT INTO delegacias values (415, 'DM - Urupes'); 
INSERT INTO delegacias values (416, '006 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (417, 'DM - Américo de Campos'); 
INSERT INTO delegacias values (418, '001 DP - Itanhaem'); 
INSERT INTO delegacias values (419, 'DM - Miracatú'); 
INSERT INTO delegacias values (420, '003 DP - Cubatão'); 
INSERT INTO delegacias values (421, '005 DP - Santos'); 
INSERT INTO delegacias values (422, '003 DP - Avaré'); 
INSERT INTO delegacias values (423, '001 DP - Pirajú'); 
INSERT INTO delegacias values (424, '002 DP - Botucatu'); 
INSERT INTO delegacias values (425, '002 DP - Itapetininga'); 
INSERT INTO delegacias values (426, 'DM - Araçoiba da Serra'); 
INSERT INTO delegacias values (427, 'DM - Porto Feliz'); 
INSERT INTO delegacias values (428, 'DM - Salto'); 
INSERT INTO delegacias values (429, '009 DP - Sorocaba'); 
INSERT INTO delegacias values (430, 'DM - Tiete'); 
INSERT INTO delegacias values (431, '003 DP - Adamantina'); 
INSERT INTO delegacias values (432, 'DM - Florida Pta.'); 
INSERT INTO delegacias values (433, 'DM - Teodoro Sampaio'); 
INSERT INTO delegacias values (434, '001 DP - Americana'); 
INSERT INTO delegacias values (435, '005 DP - Sumaré'); 
INSERT INTO delegacias values (436, 'DM - Sta. Cruz das Palmeiras'); 
INSERT INTO delegacias values (437, '002 DP - Leme'); 
INSERT INTO delegacias values (438, '006 DP - Piracicaba'); 
INSERT INTO delegacias values (439, 'DM - São Pedro'); 
INSERT INTO delegacias values (440, 'DM - Biritiba Mirim'); 
INSERT INTO delegacias values (441, '001 DP - Suzano'); 
INSERT INTO delegacias values (442, '002 DP - Suzano'); 
INSERT INTO delegacias values (443, '006 DP - Osasco'); 
INSERT INTO delegacias values (444, '001 DP - Santo André'); 
INSERT INTO delegacias values (445, '004 DP - Santo André'); 
INSERT INTO delegacias values (446, '012 DP - Pari'); 
INSERT INTO delegacias values (447, '027 DP - Campo Belo'); 
INSERT INTO delegacias values (448, '007 DP - Lapa'); 
INSERT INTO delegacias values (449, '007 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (450, 'DM - Ilhabela'); 
INSERT INTO delegacias values (451, '001 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (452, '001 DP - Campinas'); 
INSERT INTO delegacias values (453, 'DM - Paulínea'); 
INSERT INTO delegacias values (454, '001 DP - Valinhos'); 
INSERT INTO delegacias values (455, '006 DP - Campinas'); 
INSERT INTO delegacias values (456, 'DM - Águas de Lindóia'); 
INSERT INTO delegacias values (457, '006 DP - Jundiai'); 
INSERT INTO delegacias values (458, '007 DP - Jundiai'); 
INSERT INTO delegacias values (459, 'DM - Américo Brasiliense'); 
INSERT INTO delegacias values (460, '003 DP - Franca'); 
INSERT INTO delegacias values (461, '001 DP - Ituverava'); 
INSERT INTO delegacias values (462, 'DM - Orlândia'); 
INSERT INTO delegacias values (463, 'DM - Pontal'); 
INSERT INTO delegacias values (464, 'DM - Balbinos'); 
INSERT INTO delegacias values (465, 'DM - Sabino'); 
INSERT INTO delegacias values (466, 'DM - Ocauçú'); 
INSERT INTO delegacias values (467, '001 DP - Jales'); 
INSERT INTO delegacias values (468, '001 DP - Mirassol'); 
INSERT INTO delegacias values (469, '002 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (470, '005 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (471, '003 DP - Santos'); 
INSERT INTO delegacias values (472, '003 DP - São Vicente'); 
INSERT INTO delegacias values (473, 'DM - Coronel Macedo'); 
INSERT INTO delegacias values (474, 'DM - Fartura'); 
INSERT INTO delegacias values (475, 'DM - Anhembi'); 
INSERT INTO delegacias values (476, 'DM - Araçariguama'); 
INSERT INTO delegacias values (477, '003 DP - Itú'); 
INSERT INTO delegacias values (478, '007 DP - Sorocaba'); 
INSERT INTO delegacias values (479, '001 DP - Votorantim'); 
INSERT INTO delegacias values (480, 'DM - Palmital'); 
INSERT INTO delegacias values (481, 'DM - Álvares Machado'); 
INSERT INTO delegacias values (482, '003 DP - Presidente Prudente'); 
INSERT INTO delegacias values (483, '002 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (484, '002 DP - Araras'); 
INSERT INTO delegacias values (485, 'DM - Conchal'); 
INSERT INTO delegacias values (486, '004 DP - Limeira'); 
INSERT INTO delegacias values (487, '001 DP - Piracicaba'); 
INSERT INTO delegacias values (488, '002 DP - Cotia'); 
INSERT INTO delegacias values (489, 'DM - Rio Grande da Serra'); 
INSERT INTO delegacias values (490, '026 DP - Sacomã'); 
INSERT INTO delegacias values (491, '019 DP - Vila Maria'); 
INSERT INTO delegacias values (492, 'DM - Cachoeira Pta.'); 
INSERT INTO delegacias values (493, '004 DP - Jacareí'); 
INSERT INTO delegacias values (494, '001 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (495, '002 DP - Caraguatatuba'); 
INSERT INTO delegacias values (496, '003 DP - São Sebastião'); 
INSERT INTO delegacias values (497, 'DM - Castilho'); 
INSERT INTO delegacias values (498, 'DM - Penapolis'); 
INSERT INTO delegacias values (499, '003 DP - Atibaia'); 
INSERT INTO delegacias values (500, 'DM - Nazaré Pta.'); 
INSERT INTO delegacias values (501, 'DM - Socorro'); 
INSERT INTO delegacias values (502, 'DM - Jarinú'); 
INSERT INTO delegacias values (503, '002 DP - Jundiai'); 
INSERT INTO delegacias values (504, 'DM - Sto. Antônio de Posse'); 
INSERT INTO delegacias values (505, 'DM - Colina'); 
INSERT INTO delegacias values (506, 'DM - Pirangi'); 
INSERT INTO delegacias values (507, '008 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (508, 'DM - São Simão'); 
INSERT INTO delegacias values (509, 'DM - Serrana'); 
INSERT INTO delegacias values (510, 'DM - Sta R. do Passa 4'); 
INSERT INTO delegacias values (511, 'DM - Pindorama'); 
INSERT INTO delegacias values (512, 'DM - Monte Aprazível'); 
INSERT INTO delegacias values (513, '002 DP - Votuporanga'); 
INSERT INTO delegacias values (514, 'DM - Itariri'); 
INSERT INTO delegacias values (515, '007 DP - Santos'); 
INSERT INTO delegacias values (516, 'DM - Cesário Lange'); 
INSERT INTO delegacias values (517, 'DM - São Miguel Arcanjo'); 
INSERT INTO delegacias values (518, '002 DP - Tatuí'); 
INSERT INTO delegacias values (519, 'DM - Apiaí'); 
INSERT INTO delegacias values (520, 'DM - Itararé'); 
INSERT INTO delegacias values (521, '001 DP - Assis'); 
INSERT INTO delegacias values (522, 'DM - Tarumã'); 
INSERT INTO delegacias values (523, 'DM - Panorama'); 
INSERT INTO delegacias values (524, '001 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (525, 'DM - Brotas'); 
INSERT INTO delegacias values (526, 'DM - Corumbataí'); 
INSERT INTO delegacias values (527, 'DM - Aguaí'); 
INSERT INTO delegacias values (528, '009 DP - Osasco'); 
INSERT INTO delegacias values (529, '002 DP - Santo André'); 
INSERT INTO delegacias values (530, 'DM - Juquitiba'); 
INSERT INTO delegacias values (531, '004 DP - Consolação'); 
INSERT INTO delegacias values (532, '096 DP - Monções'); 
INSERT INTO delegacias values (533, '041 DP - Vila Rica'); 
INSERT INTO delegacias values (534, '003 DP - Jacareí'); 
INSERT INTO delegacias values (535, 'DM - Paraibuna'); 
INSERT INTO delegacias values (536, 'DM - Santa Branca'); 
INSERT INTO delegacias values (537, 'DM - Valinhos'); 
INSERT INTO delegacias values (538, '001 DP - Amparo'); 
INSERT INTO delegacias values (539, '002 DP - Amparo'); 
INSERT INTO delegacias values (540, 'DM - Louveira'); 
INSERT INTO delegacias values (541, 'DM - Morungaba'); 
INSERT INTO delegacias values (542, 'DM - Dobrada'); 
INSERT INTO delegacias values (543, 'DM - Gaviao Peixoto'); 
INSERT INTO delegacias values (544, '003 DP - Bauru'); 
INSERT INTO delegacias values (545, 'DM - Barra Bonita'); 
INSERT INTO delegacias values (546, 'DM - Dois Córregos'); 
INSERT INTO delegacias values (547, 'DM - Canitar'); 
INSERT INTO delegacias values (548, 'DM - Populina'); 
INSERT INTO delegacias values (549, '002 DP - Jales'); 
INSERT INTO delegacias values (550, 'DM - Paulo de Faria'); 
INSERT INTO delegacias values (551, '002 DP - Registro'); 
INSERT INTO delegacias values (552, 'DM - Campina Monte Alegre'); 
INSERT INTO delegacias values (553, '001 DP - Capão Bonito'); 
INSERT INTO delegacias values (554, 'DM - Piedade'); 
INSERT INTO delegacias values (555, '001 DP - Salto'); 
INSERT INTO delegacias values (556, '002 DP - Votorantim'); 
INSERT INTO delegacias values (557, '002 DP - Assis'); 
INSERT INTO delegacias values (558, '006 DP - Presidente Prudente'); 
INSERT INTO delegacias values (559, 'DM - Hortolândia'); 
INSERT INTO delegacias values (560, '007 DP - Piracicaba'); 
INSERT INTO delegacias values (561, '005 DP - Osasco'); 
INSERT INTO delegacias values (562, '005 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (563, '007 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (564, '001 DP - Itapecerica da Serra'); 
INSERT INTO delegacias values (565, '015 DP - Itaim Bibi'); 
INSERT INTO delegacias values (566, '091 DP - Ceagesp'); 
INSERT INTO delegacias values (567, '052 DP - Parque São Jorge'); 
INSERT INTO delegacias values (568, '002 DP - Andradina'); 
INSERT INTO delegacias values (569, 'DM - Santo Ant. Aracangua'); 
INSERT INTO delegacias values (570, '001 DP - Cabreuva'); 
INSERT INTO delegacias values (571, 'DM - Borborema'); 
INSERT INTO delegacias values (572, 'DM - Santa Lúcia'); 
INSERT INTO delegacias values (573, '001 DP - Barretos'); 
INSERT INTO delegacias values (574, 'DM - Buritizal'); 
INSERT INTO delegacias values (575, 'DM - Ituverava'); 
INSERT INTO delegacias values (576, '003 DP - Jaú'); 
INSERT INTO delegacias values (577, '004 DP - Jaú'); 
INSERT INTO delegacias values (578, 'DM - Garça'); 
INSERT INTO delegacias values (579, '002 DP - Tupã'); 
INSERT INTO delegacias values (580, 'DM - Bady Bassit'); 
INSERT INTO delegacias values (581, '001 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (582, 'DM - União Pta.'); 
INSERT INTO delegacias values (583, '001 DP - Mongaguá'); 
INSERT INTO delegacias values (584, 'DM - Juquiá'); 
INSERT INTO delegacias values (585, '004 DP - Botucatu'); 
INSERT INTO delegacias values (586, '001 DP - Tatuí'); 
INSERT INTO delegacias values (587, 'DM - Iperó'); 
INSERT INTO delegacias values (588, '004 DP - Sorocaba'); 
INSERT INTO delegacias values (589, '004 DP - Assis'); 
INSERT INTO delegacias values (590, 'DM - Ibirarema'); 
INSERT INTO delegacias values (591, 'DM - Vargem Grande do Sul'); 
INSERT INTO delegacias values (592, '001 DP - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (593, '002 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (594, '081 DP - Belém'); 
INSERT INTO delegacias values (595, '001 DP - Cruzeiro'); 
INSERT INTO delegacias values (596, 'DM - Roseira'); 
INSERT INTO delegacias values (597, 'DM - Igaratá'); 
INSERT INTO delegacias values (598, 'DM - Natividade da Serrra'); 
INSERT INTO delegacias values (599, 'DM - Avanhandava'); 
INSERT INTO delegacias values (600, '002 DP - Araraquara'); 
INSERT INTO delegacias values (601, 'DM - Pradópolis'); 
INSERT INTO delegacias values (602, 'DM - Arealva'); 
INSERT INTO delegacias values (603, 'DM - Reginópolis'); 
INSERT INTO delegacias values (604, '001 DP - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (605, 'DM - Estrela do Oeste'); 
INSERT INTO delegacias values (606, 'DM - São João das Duas Pontes'); 
INSERT INTO delegacias values (607, 'DM - Novo Horizonte'); 
INSERT INTO delegacias values (608, 'DM - Itaberá'); 
INSERT INTO delegacias values (609, 'DM - Nova Campina'); 
INSERT INTO delegacias values (610, '001 DP - Paraguaçú Pta.'); 
INSERT INTO delegacias values (611, 'DM - Capivari'); 
INSERT INTO delegacias values (612, 'DM - Itirapina'); 
INSERT INTO delegacias values (613, '005 DP - Guarulhos'); 
INSERT INTO delegacias values (614, 'Delegacia Aeroporto Int. SP - Guarulhos'); 
INSERT INTO delegacias values (615, 'DM - Guararema'); 
INSERT INTO delegacias values (616, '004 DP - Osasco'); 
INSERT INTO delegacias values (617, '001 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (618, '036 DP - Vila Mariana'); 
INSERT INTO delegacias values (619, '004 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (620, 'DM - Auriflama'); 
INSERT INTO delegacias values (621, 'DM - Lindóia'); 
INSERT INTO delegacias values (622, 'DM - Itupeva'); 
INSERT INTO delegacias values (623, '005 DP - Jundiai'); 
INSERT INTO delegacias values (624, '001 DP - Itapira'); 
INSERT INTO delegacias values (625, '001 DP - Porto Ferreira'); 
INSERT INTO delegacias values (626, 'DM - Cafelândia'); 
INSERT INTO delegacias values (627, 'DM - Echaporã'); 
INSERT INTO delegacias values (628, '001 DP - Ourinhos'); 
INSERT INTO delegacias values (629, 'DM - Sta. Fé do Sul'); 
INSERT INTO delegacias values (630, 'DM - Onda Verde'); 
INSERT INTO delegacias values (631, 'DM - Potirendaba'); 
INSERT INTO delegacias values (632, 'DM - Guarei'); 
INSERT INTO delegacias values (633, '003 DP - Itapetininga'); 
INSERT INTO delegacias values (634, '003 DP - Americana'); 
INSERT INTO delegacias values (635, '003 DP - Limeira'); 
INSERT INTO delegacias values (636, '003 DP - São João da Boa Vista'); 
INSERT INTO delegacias values (637, '002 DP - de Barueri'); 
INSERT INTO delegacias values (638, '035 DP - Jabaquara'); 
INSERT INTO delegacias values (639, 'DM - Cunha'); 
INSERT INTO delegacias values (640, 'DM - Itapura'); 
INSERT INTO delegacias values (641, 'DM - Vargem'); 
INSERT INTO delegacias values (642, 'DM - Itapira'); 
INSERT INTO delegacias values (643, 'DM - Altair'); 
INSERT INTO delegacias values (644, '002 DP - Barretos'); 
INSERT INTO delegacias values (645, '003 DP - Barretos'); 
INSERT INTO delegacias values (646, 'DM - Sta. Rosa Viterbo'); 
INSERT INTO delegacias values (647, '001 DP - São Joaquim da Barra'); 
INSERT INTO delegacias values (648, 'DM - Bocaina'); 
INSERT INTO delegacias values (649, 'DM - Taquarituba'); 
INSERT INTO delegacias values (650, '003 DP - Sorocaba'); 
INSERT INTO delegacias values (651, '001 DP - Adamantina'); 
INSERT INTO delegacias values (652, 'DM - Sta. Mercedes'); 
INSERT INTO delegacias values (653, '003 DP - Pirassununga'); 
INSERT INTO delegacias values (654, 'DM - Salesópolis'); 
INSERT INTO delegacias values (655, '057 DP - Parque da Moóca'); 
INSERT INTO delegacias values (656, 'DM - Colômbia'); 
INSERT INTO delegacias values (657, 'DM - Severínia'); 
INSERT INTO delegacias values (658, '003 DP - Bebedouro'); 
INSERT INTO delegacias values (659, 'DM - Batatais'); 
INSERT INTO delegacias values (660, 'DM - Igarapava'); 
INSERT INTO delegacias values (661, '003 DP - São Carlos'); 
INSERT INTO delegacias values (662, 'DM - Barrinha'); 
INSERT INTO delegacias values (663, 'DM - Vera Cruz'); 
INSERT INTO delegacias values (664, 'DM - Ribeirão do Sul'); 
INSERT INTO delegacias values (665, '003 DP - Tupã'); 
INSERT INTO delegacias values (666, 'DM - Ouroeste'); 
INSERT INTO delegacias values (667, 'DM - Sales'); 
INSERT INTO delegacias values (668, 'DM - Pontes Gestal'); 
INSERT INTO delegacias values (669, 'DM - Peruíbe'); 
INSERT INTO delegacias values (670, 'DM - Cananéia'); 
INSERT INTO delegacias values (671, 'DM - Areiópolis'); 
INSERT INTO delegacias values (672, '004 DP - Itapeva'); 
INSERT INTO delegacias values (673, 'DM - Rib. Grande'); 
INSERT INTO delegacias values (674, 'DM - Mir. Paranapanema'); 
INSERT INTO delegacias values (675, '001 DP - Araras'); 
INSERT INTO delegacias values (676, 'DM - Iracemápolis'); 
INSERT INTO delegacias values (677, '003 DP - Guarulhos'); 
