INSERT INTO delegacias values (1, '002 DP - Bom Retiro'); 
INSERT INTO delegacias values (2, '012 DP - Pari'); 
INSERT INTO delegacias values (3, '035 DP - Jabaquara'); 
INSERT INTO delegacias values (4, '097 DP - Americanópolis'); 
INSERT INTO delegacias values (5, '034 DP - Vila Sonia'); 
INSERT INTO delegacias values (6, '046 DP - Perus'); 
INSERT INTO delegacias values (7, '089 DP - Portal do Morumbi'); 
INSERT INTO delegacias values (8, '091 DP - Ceagesp'); 
INSERT INTO delegacias values (9, '009 DP - Carandiru'); 
INSERT INTO delegacias values (10, '040 DP - Vila Santa Maria'); 
INSERT INTO delegacias values (11, '045 DP - Vila Brasilândia'); 
INSERT INTO delegacias values (12, '072 DP - Vila Penteado'); 
INSERT INTO delegacias values (13, '073 DP - Jaçanã'); 
INSERT INTO delegacias values (14, '074 DP - Jaraguá'); 
INSERT INTO delegacias values (15, '090 DP - Parque Novo Mundo'); 
INSERT INTO delegacias values (16, '010 DP - Penha de França'); 
INSERT INTO delegacias values (17, '057 DP - Parque da Moóca'); 
INSERT INTO delegacias values (18, '011 DP - Santo Amaro'); 
INSERT INTO delegacias values (19, '025 DP - Parelheiros'); 
INSERT INTO delegacias values (20, '047 DP - Capão Redondo'); 
INSERT INTO delegacias values (21, '085 DP - Jardim Mirna'); 
INSERT INTO delegacias values (22, '092 DP - Parque Santo Antônio'); 
INSERT INTO delegacias values (23, '098 DP - Jardim Míriam'); 
INSERT INTO delegacias values (24, '100 DP - Jardim Herculano'); 
INSERT INTO delegacias values (25, '032 DP - Itaquera'); 
INSERT INTO delegacias values (26, '059 DP - Jardim Noemia'); 
INSERT INTO delegacias values (27, '062 DP - Ermelino Matarazzo'); 
INSERT INTO delegacias values (28, '063 DP - Vila Jacuí'); 
INSERT INTO delegacias values (29, '064 DP - Cidade A E Carvalho'); 
INSERT INTO delegacias values (30, '054 DP - Cidade Tiradentes'); 
INSERT INTO delegacias values (31, '066 DP - Vale do Aricanduva'); 
INSERT INTO delegacias values (32, '069 DP - Teotônio Vilela'); 
INSERT INTO delegacias values (33, '070 DP - Vila Ema'); 
INSERT INTO delegacias values (34, '003 DP - Cruzeiro'); 
INSERT INTO delegacias values (35, 'DM - Cunha'); 
INSERT INTO delegacias values (36, '001 DP - Lorena'); 
INSERT INTO delegacias values (37, '002 DP - Lorena'); 
INSERT INTO delegacias values (38, 'DM - Piquete'); 
INSERT INTO delegacias values (39, '002 DP - Jacareí'); 
INSERT INTO delegacias values (40, 'DM - Caçapava'); 
INSERT INTO delegacias values (41, '001 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (42, '006 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (43, '001 DP - Caraguatatuba'); 
INSERT INTO delegacias values (44, '002 DP - Caraguatatuba'); 
INSERT INTO delegacias values (45, 'DM - Ubatuba'); 
INSERT INTO delegacias values (46, '001 DP - Campos do Jordão'); 
INSERT INTO delegacias values (47, 'DM - Natividade da Serrra'); 
INSERT INTO delegacias values (48, '001 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (49, '002 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (50, '002 DP - Taubaté'); 
INSERT INTO delegacias values (51, '004 DP - Taubaté'); 
INSERT INTO delegacias values (52, 'DM - Tremembé'); 
INSERT INTO delegacias values (53, '003 DP - Araçatuba'); 
INSERT INTO delegacias values (54, 'DM - Guararapes'); 
INSERT INTO delegacias values (55, 'DM - Luiziania'); 
INSERT INTO delegacias values (56, '003 DP - Campinas'); 
INSERT INTO delegacias values (57, '004 DP - Campinas'); 
INSERT INTO delegacias values (58, '005 DP - Campinas'); 
INSERT INTO delegacias values (59, 'DM - Vinhedo'); 
INSERT INTO delegacias values (60, '009 DP - Campinas'); 
INSERT INTO delegacias values (61, '011 DP - Campinas'); 
INSERT INTO delegacias values (62, 'DM - Águas de Lindóia'); 
INSERT INTO delegacias values (63, '001 DP - Atibaia'); 
INSERT INTO delegacias values (64, 'DM - Atibaia'); 
INSERT INTO delegacias values (65, '005 DP - Jundiai'); 
INSERT INTO delegacias values (66, 'DM - Itapira'); 
INSERT INTO delegacias values (67, '002 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (68, '003 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (69, 'DM - Sto. Antônio de Posse'); 
INSERT INTO delegacias values (70, '001 DP - Araraquara'); 
INSERT INTO delegacias values (71, '003 DP - Araraquara'); 
INSERT INTO delegacias values (72, '001 DP - Matao'); 
INSERT INTO delegacias values (73, '003 DP - Barretos'); 
INSERT INTO delegacias values (74, 'DM - Colômbia'); 
INSERT INTO delegacias values (75, '003 DP - Bebedouro'); 
INSERT INTO delegacias values (76, 'DM - Monte Azul Paulista'); 
INSERT INTO delegacias values (77, '004 DP - Franca'); 
INSERT INTO delegacias values (78, 'DM - Guará'); 
INSERT INTO delegacias values (79, 'DM - Altinópolis'); 
INSERT INTO delegacias values (80, 'DM - Cravinhos'); 
INSERT INTO delegacias values (81, '002 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (82, '003 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (83, 'DM - Descalvado'); 
INSERT INTO delegacias values (84, 'DM - Ibaté'); 
INSERT INTO delegacias values (85, 'DM - Porto Ferreira'); 
INSERT INTO delegacias values (86, '001 DP - São Carlos'); 
INSERT INTO delegacias values (87, '002 DP - São Carlos'); 
INSERT INTO delegacias values (88, '005 DP - São Carlos'); 
INSERT INTO delegacias values (89, 'DM - Pontal'); 
INSERT INTO delegacias values (90, 'DM - Pradópolis'); 
INSERT INTO delegacias values (91, 'DM - Sertãozinho'); 
INSERT INTO delegacias values (92, '001 DP - Bauru'); 
INSERT INTO delegacias values (93, '002 DP - Bauru'); 
INSERT INTO delegacias values (94, 'DM - Lençóis Paulista'); 
INSERT INTO delegacias values (95, '003 DP - Marília'); 
INSERT INTO delegacias values (96, '003 DP - Catanduva'); 
INSERT INTO delegacias values (97, '004 DP - Catanduva'); 
INSERT INTO delegacias values (98, 'DM - Adolfo'); 
INSERT INTO delegacias values (99, 'DM - Balsamo'); 
INSERT INTO delegacias values (100, '001 DP - Mirassol'); 
INSERT INTO delegacias values (101, '002 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (102, '004 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (103, '005 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (104, '006 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (105, '007 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (106, 'DM - Tanabi'); 
INSERT INTO delegacias values (107, '002 DP - Votuporanga'); 
INSERT INTO delegacias values (108, 'DM - Itariri'); 
INSERT INTO delegacias values (109, 'DM - Cajati'); 
INSERT INTO delegacias values (110, '001 DP - Iguape'); 
INSERT INTO delegacias values (111, 'DM - Miracatú'); 
INSERT INTO delegacias values (112, '001 DP - Guarujá'); 
INSERT INTO delegacias values (113, '002 DP - Guarujá'); 
INSERT INTO delegacias values (114, 'DM - Guarujá'); 
INSERT INTO delegacias values (115, '002 DP - Praia Grande'); 
INSERT INTO delegacias values (116, 'DM - Praia Grande'); 
INSERT INTO delegacias values (117, '004 DP - Santos'); 
INSERT INTO delegacias values (118, '005 DP - Santos'); 
INSERT INTO delegacias values (119, '002 DP - São Vicente'); 
INSERT INTO delegacias values (120, 'DM - Itaí'); 
INSERT INTO delegacias values (121, 'DM - Pirajú'); 
INSERT INTO delegacias values (122, 'DM - Boituva'); 
INSERT INTO delegacias values (123, 'DM - Apiaí'); 
INSERT INTO delegacias values (124, 'DM - Araçariguama'); 
INSERT INTO delegacias values (125, 'DM - Araçoiba da Serra'); 
INSERT INTO delegacias values (126, 'DM - Iperó'); 
INSERT INTO delegacias values (127, '002 DP - Itú'); 
INSERT INTO delegacias values (128, 'DM - Salto de Pirapora'); 
INSERT INTO delegacias values (129, '001 DP - Sorocaba'); 
INSERT INTO delegacias values (130, '008 DP - Sorocaba'); 
INSERT INTO delegacias values (131, '002 DP - Assis'); 
INSERT INTO delegacias values (132, '003 DP - Assis'); 
INSERT INTO delegacias values (133, 'DM - Tupi Pta.'); 
INSERT INTO delegacias values (134, '001 DP - Presidente Prudente'); 
INSERT INTO delegacias values (135, 'DM - Caiuá'); 
INSERT INTO delegacias values (136, 'DM - Piquerobi'); 
INSERT INTO delegacias values (137, '001 DP - Americana'); 
INSERT INTO delegacias values (138, '004 DP - Americana'); 
INSERT INTO delegacias values (139, 'DM - Cosmópolis'); 
INSERT INTO delegacias values (140, '001 DP - Hortolândia'); 
INSERT INTO delegacias values (141, '002 DP - Hortolândia'); 
INSERT INTO delegacias values (142, 'DM - Hortolândia'); 
INSERT INTO delegacias values (143, '003 DP - Sumaré'); 
INSERT INTO delegacias values (144, '002 DP - Araras'); 
INSERT INTO delegacias values (145, '004 DP - Limeira'); 
INSERT INTO delegacias values (146, '003 DP - Rio Claro'); 
INSERT INTO delegacias values (147, 'DM - Sta. Gertrudes'); 
INSERT INTO delegacias values (148, '001 DP - Barueri'); 
INSERT INTO delegacias values (149, '001 DP - Carapicuiba'); 
INSERT INTO delegacias values (150, '002 DP - Carapicuiba'); 
INSERT INTO delegacias values (151, '003 DP - Carapicuiba'); 
INSERT INTO delegacias values (152, '001 DP - Cotia'); 
INSERT INTO delegacias values (153, '002 DP - Cotia'); 
INSERT INTO delegacias values (154, 'DM - Itapevi'); 
INSERT INTO delegacias values (155, '001 DP - Diadema'); 
INSERT INTO delegacias values (156, '002 DP - Diadema'); 
INSERT INTO delegacias values (157, 'DM - Francisco Morato'); 
INSERT INTO delegacias values (158, 'DM - Franco da Rocha'); 
INSERT INTO delegacias values (159, '002 DP - Guarulhos'); 
INSERT INTO delegacias values (160, '004 DP - Guarulhos'); 
INSERT INTO delegacias values (161, '005 DP - Guarulhos'); 
INSERT INTO delegacias values (162, '006 DP - Guarulhos'); 
INSERT INTO delegacias values (163, '007 DP - Guarulhos'); 
INSERT INTO delegacias values (164, '008 DP - Guarulhos'); 
INSERT INTO delegacias values (165, '009 DP - Guarulhos'); 
INSERT INTO delegacias values (166, 'DM - Santa Isabel'); 
INSERT INTO delegacias values (167, '001 DP - Itaquaquecetuba'); 
INSERT INTO delegacias values (168, 'DM - Itaquaquecetuba'); 
INSERT INTO delegacias values (169, '001 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (170, '002 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (171, '003 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (172, '001 DP - Suzano'); 
INSERT INTO delegacias values (173, '002 DP - Suzano'); 
INSERT INTO delegacias values (174, 'DM - Suzano'); 
INSERT INTO delegacias values (175, '002 DP - Osasco'); 
INSERT INTO delegacias values (176, '004 DP - Osasco'); 
INSERT INTO delegacias values (177, '008 DP - Osasco'); 
INSERT INTO delegacias values (178, '010 DP - Osasco'); 
INSERT INTO delegacias values (179, '003 DP - Mauá'); 
INSERT INTO delegacias values (180, '004 DP - Mauá'); 
INSERT INTO delegacias values (181, 'DM - Ribeirão Pires'); 
INSERT INTO delegacias values (182, '004 DP - Santo André'); 
INSERT INTO delegacias values (183, '006 DP - Santo André'); 
INSERT INTO delegacias values (184, '004 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (185, '008 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (186, '003 DP - S. Caetano do Sul'); 
INSERT INTO delegacias values (187, 'DM - Embú'); 
INSERT INTO delegacias values (188, 'DM - Embú Guaçú'); 
INSERT INTO delegacias values (189, 'DM - Itapecerica da Serra'); 
INSERT INTO delegacias values (190, '001 DP - Taboão da Serra'); 
INSERT INTO delegacias values (191, '001 DP - Sé'); 
INSERT INTO delegacias values (192, '003 DP - Campos Elísios'); 
INSERT INTO delegacias values (193, '004 DP - Consolação'); 
INSERT INTO delegacias values (194, '077 DP - Santa Cecília'); 
INSERT INTO delegacias values (195, '027 DP - Campo Belo'); 
INSERT INTO delegacias values (196, '015 DP - Itaim Bibi'); 
INSERT INTO delegacias values (197, '023 DP - Perdizes'); 
INSERT INTO delegacias values (198, '033 DP - Pirituba'); 
INSERT INTO delegacias values (199, '037 DP - Campo Limpo'); 
INSERT INTO delegacias values (200, '087 DP - Vila Pereira Barreto'); 
INSERT INTO delegacias values (201, '020 DP - Água Fria'); 
INSERT INTO delegacias values (202, '021 DP - Vila Matilde'); 
INSERT INTO delegacias values (203, '030 DP - Tatuapé'); 
INSERT INTO delegacias values (204, '099 DP - Campo Grande'); 
INSERT INTO delegacias values (205, '101 DP - Jardim das Imbuias'); 
INSERT INTO delegacias values (206, '022 DP - São Miguel Paulista'); 
INSERT INTO delegacias values (207, '050 DP - Itaim Paulista'); 
INSERT INTO delegacias values (208, '067 DP - Jardim Robru'); 
INSERT INTO delegacias values (209, '068 DP - Lajeado'); 
INSERT INTO delegacias values (210, '049 DP - São Mateus'); 
INSERT INTO delegacias values (211, '053 DP - Parque do Carmo'); 
INSERT INTO delegacias values (212, '002 DP - Cruzeiro'); 
INSERT INTO delegacias values (213, '002 DP - Guaratinguetá'); 
INSERT INTO delegacias values (214, '003 DP - Guaratinguetá'); 
INSERT INTO delegacias values (215, 'DM - Igaratá'); 
INSERT INTO delegacias values (216, '004 DP - Jacareí'); 
INSERT INTO delegacias values (217, '002 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (218, '003 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (219, 'DM - Campos do Jordão'); 
INSERT INTO delegacias values (220, '003 DP - Pindamonhangaba'); 
INSERT INTO delegacias values (221, '003 DP - Taubaté'); 
INSERT INTO delegacias values (222, 'DM - Pereira Barreto'); 
INSERT INTO delegacias values (223, '001 DP - Birigui'); 
INSERT INTO delegacias values (224, 'DM - Brejo Alegre'); 
INSERT INTO delegacias values (225, 'DM - Piacatu'); 
INSERT INTO delegacias values (226, '007 DP - Campinas'); 
INSERT INTO delegacias values (227, '010 DP - Campinas'); 
INSERT INTO delegacias values (228, 'DM - Paulínea'); 
INSERT INTO delegacias values (229, '002 DP - Campinas'); 
INSERT INTO delegacias values (230, '006 DP - Campinas'); 
INSERT INTO delegacias values (231, '008 DP - Campinas'); 
INSERT INTO delegacias values (232, '002 DP - Bragança Pta.'); 
INSERT INTO delegacias values (233, 'DM - Campo Limpo Pta.'); 
INSERT INTO delegacias values (234, 'DM - Itupeva'); 
INSERT INTO delegacias values (235, 'DM - Jarinú'); 
INSERT INTO delegacias values (236, '007 DP - Jundiai'); 
INSERT INTO delegacias values (237, 'DM - Tabatinga'); 
INSERT INTO delegacias values (238, 'DM - Pirangi'); 
INSERT INTO delegacias values (239, 'DM - Taiaçu'); 
INSERT INTO delegacias values (240, '002 DP - Franca'); 
INSERT INTO delegacias values (241, 'DM - Jeriguara'); 
INSERT INTO delegacias values (242, '007 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (243, '004 DP - São Carlos'); 
INSERT INTO delegacias values (244, 'DM - Monte Alto'); 
INSERT INTO delegacias values (245, '004 DP - Bauru'); 
INSERT INTO delegacias values (246, 'DM - Pederneiras'); 
INSERT INTO delegacias values (247, 'DM - Igaraçu do Tietê'); 
INSERT INTO delegacias values (248, '003 DP - Jaú'); 
INSERT INTO delegacias values (249, '001 DP - Lins'); 
INSERT INTO delegacias values (250, '002 DP - Lins'); 
INSERT INTO delegacias values (251, 'DM - Sabino'); 
INSERT INTO delegacias values (252, '001 DP - Marília'); 
INSERT INTO delegacias values (253, '004 DP - Marília'); 
INSERT INTO delegacias values (254, 'DM - Esp. Sto. Do Turvo'); 
INSERT INTO delegacias values (255, 'DM - Bastos'); 
INSERT INTO delegacias values (256, '002 DP - Catanduva'); 
INSERT INTO delegacias values (257, 'DM - Urupes'); 
INSERT INTO delegacias values (258, 'DM - Mirassol'); 
INSERT INTO delegacias values (259, '003 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (260, 'DM - Zacarias'); 
INSERT INTO delegacias values (261, '002 DP - Itanhaem'); 
INSERT INTO delegacias values (262, 'DM - Iporanga'); 
INSERT INTO delegacias values (263, '001 DP - Jacupiranga'); 
INSERT INTO delegacias values (264, 'DM - Bertioga'); 
INSERT INTO delegacias values (265, '001 DP - Cubatão'); 
INSERT INTO delegacias values (266, '003 DP - Cubatão'); 
INSERT INTO delegacias values (267, '003 DP - São Vicente'); 
INSERT INTO delegacias values (268, '001 DP - Avaré'); 
INSERT INTO delegacias values (269, 'DM - Iaras'); 
INSERT INTO delegacias values (270, '002 DP - Botucatu'); 
INSERT INTO delegacias values (271, 'DM - Itatinga'); 
INSERT INTO delegacias values (272, '001 DP - Itapetininga'); 
INSERT INTO delegacias values (273, '002 DP - Tatuí'); 
INSERT INTO delegacias values (274, 'DM - Tatuí'); 
INSERT INTO delegacias values (275, 'DM - Ibiúna'); 
INSERT INTO delegacias values (276, 'DM - Pilar do Sul'); 
INSERT INTO delegacias values (277, 'DM - Porto Feliz'); 
INSERT INTO delegacias values (278, '001 DP - Salto'); 
INSERT INTO delegacias values (279, '002 DP - Salto'); 
INSERT INTO delegacias values (280, '002 DP - Sorocaba'); 
INSERT INTO delegacias values (281, '003 DP - Sorocaba'); 
INSERT INTO delegacias values (282, '009 DP - Sorocaba'); 
INSERT INTO delegacias values (283, '002 DP - Votorantim'); 
INSERT INTO delegacias values (284, '003 DP - Votorantim'); 
INSERT INTO delegacias values (285, '001 DP - Osvaldo Cruz'); 
INSERT INTO delegacias values (286, '003 DP - Presidente Prudente'); 
INSERT INTO delegacias values (287, 'DM - Regente Feijó'); 
INSERT INTO delegacias values (288, 'DM - Mir. Paranapanema'); 
INSERT INTO delegacias values (289, 'DM - Monte Mor'); 
INSERT INTO delegacias values (290, '002 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (291, '001 DP - Sumaré'); 
INSERT INTO delegacias values (292, 'DM - Torrinha'); 
INSERT INTO delegacias values (293, 'DM - Aguaí'); 
INSERT INTO delegacias values (294, '002 DP - São João da Boa Vista'); 
INSERT INTO delegacias values (295, '002 DP - de Barueri'); 
INSERT INTO delegacias values (296, 'DM - Jandira'); 
INSERT INTO delegacias values (297, 'DM - Pirapora do Bom Jesus'); 
INSERT INTO delegacias values (298, '003 DP - Diadema'); 
INSERT INTO delegacias values (299, '004 DP - Diadema'); 
INSERT INTO delegacias values (300, 'DM - Mairiporã'); 
INSERT INTO delegacias values (301, 'DM - Aruja'); 
INSERT INTO delegacias values (302, 'DM - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (303, 'DM - Poá'); 
INSERT INTO delegacias values (304, '001 DP - Osasco'); 
INSERT INTO delegacias values (305, '006 DP - Osasco'); 
INSERT INTO delegacias values (306, '001 DP - Mauá'); 
INSERT INTO delegacias values (307, '002 DP - Santo André'); 
INSERT INTO delegacias values (308, '003 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (309, '006 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (310, 'DM - S. Caetano do Sul'); 
INSERT INTO delegacias values (311, '001 DP - Embú'); 
INSERT INTO delegacias values (312, '005 DP - Aclimação'); 
INSERT INTO delegacias values (313, '006 DP - Cambuci'); 
INSERT INTO delegacias values (314, '008 DP - Brás'); 
INSERT INTO delegacias values (315, '017 DP - Ipiranga'); 
INSERT INTO delegacias values (316, '026 DP - Sacomã'); 
INSERT INTO delegacias values (317, '083 DP - Parque Bristol'); 
INSERT INTO delegacias values (318, '075 DP - Jardim Arpoador'); 
INSERT INTO delegacias values (319, '029 DP - Vila Diva'); 
INSERT INTO delegacias values (320, '065 DP - Artur Alvim'); 
INSERT INTO delegacias values (321, 'DM - Canas'); 
INSERT INTO delegacias values (322, 'DM - Potim'); 
INSERT INTO delegacias values (323, 'DM - Roseira'); 
INSERT INTO delegacias values (324, '001 DP - Jacareí'); 
INSERT INTO delegacias values (325, 'DM - Caraguatatuba'); 
INSERT INTO delegacias values (326, '002 DP - São Sebastião'); 
INSERT INTO delegacias values (327, '004 DP - São Sebastião'); 
INSERT INTO delegacias values (328, 'DM - Castilho'); 
INSERT INTO delegacias values (329, 'DM - Sud Menucci'); 
INSERT INTO delegacias values (330, '002 DP - Araçatuba'); 
INSERT INTO delegacias values (331, 'DM - Penapolis'); 
INSERT INTO delegacias values (332, '001 DP - Campinas'); 
INSERT INTO delegacias values (333, '001 DP - Indaiatuba'); 
INSERT INTO delegacias values (334, 'DM - Bom Jesus dos Perdões'); 
INSERT INTO delegacias values (335, '001 DP - Itatiba'); 
INSERT INTO delegacias values (336, '002 DP - Jundiai'); 
INSERT INTO delegacias values (337, '004 DP - Jundiai'); 
INSERT INTO delegacias values (338, '006 DP - Jundiai'); 
INSERT INTO delegacias values (339, 'DM - Américo Brasiliense'); 
INSERT INTO delegacias values (340, 'DM - Colina'); 
INSERT INTO delegacias values (341, '002 DP - Bebedouro'); 
INSERT INTO delegacias values (342, 'DM - Viradouro'); 
INSERT INTO delegacias values (343, 'DM - Pedregulho'); 
INSERT INTO delegacias values (344, 'DM - Rifaina'); 
INSERT INTO delegacias values (345, '003 DP - São Carlos'); 
INSERT INTO delegacias values (346, 'DM - Barrinha'); 
INSERT INTO delegacias values (347, '001 DP - Jaboticabal'); 
INSERT INTO delegacias values (348, '002 DP - Jaboticabal'); 
INSERT INTO delegacias values (349, '003 DP - Lins'); 
INSERT INTO delegacias values (350, 'DM - Bern. De Campos'); 
INSERT INTO delegacias values (351, 'DM - Salto Grande'); 
INSERT INTO delegacias values (352, '001 DP - Sta. Fé do Sul'); 
INSERT INTO delegacias values (353, 'DM - Sta. Fé do Sul'); 
INSERT INTO delegacias values (354, 'DM - Bady Bassit'); 
INSERT INTO delegacias values (355, 'DM - Nipoã'); 
INSERT INTO delegacias values (356, 'DM - Riolândia'); 
INSERT INTO delegacias values (357, '001 DP - Votuporanga'); 
INSERT INTO delegacias values (358, '003 DP - Votuporanga'); 
INSERT INTO delegacias values (359, '001 DP - Peruíbe'); 
INSERT INTO delegacias values (360, '003 DP - Praia Grande'); 
INSERT INTO delegacias values (361, '001 DP - São Vicente'); 
INSERT INTO delegacias values (362, 'DM - Capela do Alto'); 
INSERT INTO delegacias values (363, 'DM - Sarapuí'); 
INSERT INTO delegacias values (364, '003 DP - Itú'); 
INSERT INTO delegacias values (365, '011 DP - Sorocaba'); 
INSERT INTO delegacias values (366, '001 DP - Votorantim'); 
INSERT INTO delegacias values (367, 'DM - Votorantim'); 
INSERT INTO delegacias values (368, '003 DP - Adamantina'); 
INSERT INTO delegacias values (369, 'DM - Paraguaçú Pta.'); 
INSERT INTO delegacias values (370, '006 DP - Presidente Prudente'); 
INSERT INTO delegacias values (371, 'DM - Teodoro Sampaio'); 
INSERT INTO delegacias values (372, '003 DP - Americana'); 
INSERT INTO delegacias values (373, '003 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (374, '002 DP - Sumaré'); 
INSERT INTO delegacias values (375, 'DM - Casa Branca'); 
INSERT INTO delegacias values (376, 'DM - Sta. Cruz das Palmeiras'); 
INSERT INTO delegacias values (377, '001 DP - Araras'); 
INSERT INTO delegacias values (378, '001 DP - Leme'); 
INSERT INTO delegacias values (379, '001 DP - Limeira'); 
INSERT INTO delegacias values (380, '002 DP - Limeira'); 
INSERT INTO delegacias values (381, '003 DP - Limeira'); 
INSERT INTO delegacias values (382, '003 DP - Piracicaba'); 
INSERT INTO delegacias values (383, '007 DP - Piracicaba'); 
INSERT INTO delegacias values (384, 'DM - São Pedro'); 
INSERT INTO delegacias values (385, 'DM - Barueri'); 
INSERT INTO delegacias values (386, 'DM - Cotia'); 
INSERT INTO delegacias values (387, 'DM - Santana do Parnaiba'); 
INSERT INTO delegacias values (388, 'DM - Vargem Grande Paulista'); 
INSERT INTO delegacias values (389, '003 DP - Guarulhos'); 
INSERT INTO delegacias values (390, '009 DP - Osasco'); 
INSERT INTO delegacias values (391, '001 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (392, '007 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (393, '001 DP - Itapecerica da Serra'); 
INSERT INTO delegacias values (394, 'DM - Juquitiba'); 
INSERT INTO delegacias values (395, '002 DP - Taboão da Serra'); 
INSERT INTO delegacias values (396, '078 DP - Jardins'); 
INSERT INTO delegacias values (397, '051 DP - Butantã'); 
INSERT INTO delegacias values (398, '013 DP - Casa Verde'); 
INSERT INTO delegacias values (399, '019 DP - Vila Maria'); 
INSERT INTO delegacias values (400, '028 DP - Freguesia do Ó'); 
INSERT INTO delegacias values (401, '039 DP - Vila Gustavo'); 
INSERT INTO delegacias values (402, '031 DP - Vila Carrão'); 
INSERT INTO delegacias values (403, '052 DP - Parque São Jorge'); 
INSERT INTO delegacias values (404, '043 DP - Cidade Ademar'); 
INSERT INTO delegacias values (405, '048 DP - Cidade Dutra'); 
INSERT INTO delegacias values (406, '080 DP - Vila Joaniza'); 
INSERT INTO delegacias values (407, '103 DP - Cohab Itaquera'); 
INSERT INTO delegacias values (408, '041 DP - Vila Rica'); 
INSERT INTO delegacias values (409, '044 DP - Guaianazes'); 
INSERT INTO delegacias values (410, '055 DP - Parque São Rafael'); 
INSERT INTO delegacias values (411, '004 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (412, '005 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (413, '007 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (414, '001 DP - Andradina'); 
INSERT INTO delegacias values (415, 'DM - Birigui'); 
INSERT INTO delegacias values (416, 'DM - Valparaiso'); 
INSERT INTO delegacias values (417, '001 DP - Bragança Pta.'); 
INSERT INTO delegacias values (418, '003 DP - Bragança Pta.'); 
INSERT INTO delegacias values (419, 'DM - Louveira'); 
INSERT INTO delegacias values (420, 'DM - Itápolis'); 
INSERT INTO delegacias values (421, 'DM - Batatais'); 
INSERT INTO delegacias values (422, '005 DP - Franca'); 
INSERT INTO delegacias values (423, 'DM - Ituverava'); 
INSERT INTO delegacias values (424, '006 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (425, '008 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (426, 'DM - Guariba'); 
INSERT INTO delegacias values (427, 'DM - Agudos'); 
INSERT INTO delegacias values (428, '003 DP - Bauru'); 
INSERT INTO delegacias values (429, 'DM - Dois Córregos'); 
INSERT INTO delegacias values (430, 'DM - Promissão'); 
INSERT INTO delegacias values (431, '002 DP - Marília'); 
INSERT INTO delegacias values (432, '001 DP - Tupã'); 
INSERT INTO delegacias values (433, 'DM - Pindorama'); 
INSERT INTO delegacias values (434, 'DM - Ouroeste'); 
INSERT INTO delegacias values (435, 'DM - José Bonifácio'); 
INSERT INTO delegacias values (436, '002 DP - Registro'); 
INSERT INTO delegacias values (437, '003 DP - Santos'); 
INSERT INTO delegacias values (438, 'DM - Pratânia'); 
INSERT INTO delegacias values (439, 'DM - Angatuba'); 
INSERT INTO delegacias values (440, 'DM - Guarei'); 
INSERT INTO delegacias values (441, 'DM - Rib. Branco'); 
INSERT INTO delegacias values (442, 'DM - Mairinque'); 
INSERT INTO delegacias values (443, 'DM - Piedade'); 
INSERT INTO delegacias values (444, '006 DP - Sorocaba'); 
INSERT INTO delegacias values (445, 'DM - Tiete'); 
INSERT INTO delegacias values (446, 'DM - Irapuru'); 
INSERT INTO delegacias values (447, '001 DP - Assis'); 
INSERT INTO delegacias values (448, 'DM - Campos Novos Pta.'); 
INSERT INTO delegacias values (449, '001 DP - Dracena'); 
INSERT INTO delegacias values (450, '002 DP - Americana'); 
INSERT INTO delegacias values (451, 'DM - Engenheiro Coelho'); 
INSERT INTO delegacias values (452, 'DM - Nova Odessa'); 
INSERT INTO delegacias values (453, '004 DP - Sumaré'); 
INSERT INTO delegacias values (454, '005 DP - Sumaré'); 
INSERT INTO delegacias values (455, 'DM - Mococa'); 
INSERT INTO delegacias values (456, '002 DP - Leme'); 
INSERT INTO delegacias values (457, '002 DP - Pirassununga'); 
INSERT INTO delegacias values (458, 'DM - Elias Fausto'); 
INSERT INTO delegacias values (459, '006 DP - Piracicaba'); 
INSERT INTO delegacias values (460, 'DM - Rio das Pedras'); 
INSERT INTO delegacias values (461, 'DM - Vargem Grande do Sul'); 
INSERT INTO delegacias values (462, '001 DP - Caieiras'); 
INSERT INTO delegacias values (463, 'DM - Cajamar'); 
INSERT INTO delegacias values (464, '004 DP - Mogi das Cruzes'); 
INSERT INTO delegacias values (465, 'DM - Rio Grande da Serra'); 
INSERT INTO delegacias values (466, '001 DP - Santo André'); 
INSERT INTO delegacias values (467, '003 DP - Santo André'); 
INSERT INTO delegacias values (468, 'DM - São Lourenço da Serra'); 
INSERT INTO delegacias values (469, '095 DP - Heliópolis'); 
INSERT INTO delegacias values (470, '093 DP - Jaguaré'); 
INSERT INTO delegacias values (471, '038 DP - Vila Amália'); 
INSERT INTO delegacias values (472, '102 DP - Socorro'); 
INSERT INTO delegacias values (473, 'DM - São José do Barreiro'); 
INSERT INTO delegacias values (474, '001 DP - São Sebastião'); 
INSERT INTO delegacias values (475, '002 DP - Andradina'); 
INSERT INTO delegacias values (476, 'DM - Coroados'); 
INSERT INTO delegacias values (477, '002 DP - Amparo'); 
INSERT INTO delegacias values (478, 'DM - Várzea Pta.'); 
INSERT INTO delegacias values (479, '001 DP - Itapira'); 
INSERT INTO delegacias values (480, 'DM - Taquaritinga'); 
INSERT INTO delegacias values (481, '001 DP - Guaíra'); 
INSERT INTO delegacias values (482, '001 DP - Batatais'); 
INSERT INTO delegacias values (483, 'DM - Miguelópolis'); 
INSERT INTO delegacias values (484, 'DM - Ribeirão Corrente'); 
INSERT INTO delegacias values (485, 'DM - Morro Agudo'); 
INSERT INTO delegacias values (486, 'DM - Arealva'); 
INSERT INTO delegacias values (487, 'DM - Boracéia'); 
INSERT INTO delegacias values (488, 'DM - Oleo'); 
INSERT INTO delegacias values (489, '002 DP - Ourinhos'); 
INSERT INTO delegacias values (490, 'DM - Tabapuã'); 
INSERT INTO delegacias values (491, 'DM - Nova Granada'); 
INSERT INTO delegacias values (492, 'DM - Mongaguá'); 
INSERT INTO delegacias values (493, 'DM - Pariquera-Açú'); 
INSERT INTO delegacias values (494, 'DM - Fartura'); 
INSERT INTO delegacias values (495, 'DM - Anhembi'); 
INSERT INTO delegacias values (496, 'DM - Areiópolis'); 
INSERT INTO delegacias values (497, '001 DP - Capão Bonito'); 
INSERT INTO delegacias values (498, 'DM - Alumínio'); 
INSERT INTO delegacias values (499, '001 DP - Itú'); 
INSERT INTO delegacias values (500, '004 DP - Itú'); 
INSERT INTO delegacias values (501, '004 DP - Assis'); 
INSERT INTO delegacias values (502, 'DM - Cândido Mota'); 
INSERT INTO delegacias values (503, 'DM - Palmital'); 
INSERT INTO delegacias values (504, 'DM - João Ramalho'); 
INSERT INTO delegacias values (505, 'DM - Presidente Epitácio'); 
INSERT INTO delegacias values (506, '001 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (507, '001 DP - Sta. Barbara do Oeste'); 
INSERT INTO delegacias values (508, 'DM - Caconde'); 
INSERT INTO delegacias values (509, 'DM - Capivari'); 
INSERT INTO delegacias values (510, 'DM - Ipeúna'); 
INSERT INTO delegacias values (511, '001 DP - Rio Claro'); 
INSERT INTO delegacias values (512, '002 DP - Rio Claro'); 
INSERT INTO delegacias values (513, '001 DP - Cajamar'); 
INSERT INTO delegacias values (514, '003 DP - Osasco'); 
INSERT INTO delegacias values (515, '007 DP - Osasco'); 
INSERT INTO delegacias values (516, '081 DP - Belém'); 
INSERT INTO delegacias values (517, 'DM - Aparecida'); 
INSERT INTO delegacias values (518, '003 DP - Jacareí'); 
INSERT INTO delegacias values (519, 'DM - Avanhandava'); 
INSERT INTO delegacias values (520, 'DM - General Salgado'); 
INSERT INTO delegacias values (521, '003 DP - Mogi Mirim'); 
INSERT INTO delegacias values (522, 'DM - Altair'); 
INSERT INTO delegacias values (523, '002 DP - Barretos'); 
INSERT INTO delegacias values (524, 'DM - Olímpia'); 
INSERT INTO delegacias values (525, 'DM - Taiuva'); 
INSERT INTO delegacias values (526, 'DM - Cajuru'); 
INSERT INTO delegacias values (527, 'DM - Jardinópolis'); 
INSERT INTO delegacias values (528, '005 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (529, '001 DP - São Joaquim da Barra'); 
INSERT INTO delegacias values (530, '002 DP - Tupã'); 
INSERT INTO delegacias values (531, 'DM - Ariranha'); 
INSERT INTO delegacias values (532, '002 DP - Mongaguá'); 
INSERT INTO delegacias values (533, 'DM - Iguape'); 
INSERT INTO delegacias values (534, 'DM - Taquarituba'); 
INSERT INTO delegacias values (535, '003 DP - Itapetininga'); 
INSERT INTO delegacias values (536, 'DM - Buri'); 
INSERT INTO delegacias values (537, 'DM - Itaoca'); 
INSERT INTO delegacias values (538, 'DM - São Roque'); 
INSERT INTO delegacias values (539, 'DM - Alfredo Marcondes'); 
INSERT INTO delegacias values (540, 'DM - Álvares Machado'); 
INSERT INTO delegacias values (541, 'DM - Euclides da Cunha Pta.'); 
INSERT INTO delegacias values (542, 'DM - Cordeirópolis'); 
INSERT INTO delegacias values (543, '002 DP - Piracicaba'); 
INSERT INTO delegacias values (544, 'DM - Analândia'); 
INSERT INTO delegacias values (545, '001 DP - Ferraz de Vasconcelos'); 
INSERT INTO delegacias values (546, '002 DP - Mauá'); 
INSERT INTO delegacias values (547, '096 DP - Monções'); 
INSERT INTO delegacias values (548, '058 DP - Vila Formosa'); 
INSERT INTO delegacias values (549, 'DM - Cachoeira Pta.'); 
INSERT INTO delegacias values (550, '001 DP - Guaratinguetá'); 
INSERT INTO delegacias values (551, '001 DP - Araçatuba'); 
INSERT INTO delegacias values (552, '001 DP - Mogi-Guaçu'); 
INSERT INTO delegacias values (553, '002 DP - Araraquara'); 
INSERT INTO delegacias values (554, 'DM - Ibitinga'); 
INSERT INTO delegacias values (555, 'DM - Cajobi'); 
INSERT INTO delegacias values (556, 'DM - C. Coqueiros'); 
INSERT INTO delegacias values (557, '004 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (558, 'DM - Serrana'); 
INSERT INTO delegacias values (559, 'DM - Sta R. do Passa 4'); 
INSERT INTO delegacias values (560, 'DM - Balbinos'); 
INSERT INTO delegacias values (561, '001 DP - Jaú'); 
INSERT INTO delegacias values (562, 'DM - Vera Cruz'); 
INSERT INTO delegacias values (563, 'DM - Jaci'); 
INSERT INTO delegacias values (564, 'DM - Cardoso'); 
INSERT INTO delegacias values (565, '001 DP - Praia Grande'); 
INSERT INTO delegacias values (566, '002 DP - Santos'); 
INSERT INTO delegacias values (567, '002 DP - Avaré'); 
INSERT INTO delegacias values (568, 'DM - Cerqueira César'); 
INSERT INTO delegacias values (569, '001 DP - Botucatu'); 
INSERT INTO delegacias values (570, '001 DP - São Manuel'); 
INSERT INTO delegacias values (571, '004 DP - Sorocaba'); 
INSERT INTO delegacias values (572, 'DM - Nova Guataporanga'); 
INSERT INTO delegacias values (573, '002 DP - Presidente Venceslau'); 
INSERT INTO delegacias values (574, 'DM - Artur Nogueira'); 
INSERT INTO delegacias values (575, 'DM - Tambaú'); 
INSERT INTO delegacias values (576, '001 DP - Pirassununga'); 
INSERT INTO delegacias values (577, '004 DP - Piracicaba'); 
INSERT INTO delegacias values (578, '005 DP - Piracicaba'); 
INSERT INTO delegacias values (579, 'DM - São Sebastião da Gama'); 
INSERT INTO delegacias values (580, '005 DP - Osasco'); 
INSERT INTO delegacias values (581, '005 DP - Santo André'); 
INSERT INTO delegacias values (582, '005 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (583, '016 DP - Vila Clementino'); 
INSERT INTO delegacias values (584, '042 DP - Parque São Lucas'); 
INSERT INTO delegacias values (585, 'DM - Mirandópolis'); 
INSERT INTO delegacias values (586, 'DM - Auriflama'); 
INSERT INTO delegacias values (587, '002 DP - Birigui'); 
INSERT INTO delegacias values (588, '002 DP - Mogi Mirim'); 
INSERT INTO delegacias values (589, 'DM - Guaraci'); 
INSERT INTO delegacias values (590, '001 DP - Ituverava'); 
INSERT INTO delegacias values (591, 'DM - Brodowski'); 
INSERT INTO delegacias values (592, 'DM - Ribeirão Bonito'); 
INSERT INTO delegacias values (593, '001 DP - Ourinhos'); 
INSERT INTO delegacias values (594, '003 DP - Ourinhos'); 
INSERT INTO delegacias values (595, 'DM - Monte Aprazível'); 
INSERT INTO delegacias values (596, 'DM - Valentim Gentil'); 
INSERT INTO delegacias values (597, '003 DP - Botucatu'); 
INSERT INTO delegacias values (598, '001 DP - Tatuí'); 
INSERT INTO delegacias values (599, '010 DP - Sorocaba'); 
INSERT INTO delegacias values (600, 'DM - Taciba'); 
INSERT INTO delegacias values (601, 'DM - Itobi'); 
INSERT INTO delegacias values (602, '001 DP - São João da Boa Vista'); 
INSERT INTO delegacias values (603, '003 DP - São João da Boa Vista'); 
INSERT INTO delegacias values (604, 'DM - Caieiras'); 
INSERT INTO delegacias values (605, '001 DP - Mairiporã'); 
INSERT INTO delegacias values (606, '036 DP - Vila Mariana'); 
INSERT INTO delegacias values (607, '056 DP - Vila Alpina'); 
INSERT INTO delegacias values (608, 'DM - Buritama'); 
INSERT INTO delegacias values (609, 'DM - Santo Ant. Aracangua'); 
INSERT INTO delegacias values (610, '002 DP - Atibaia'); 
INSERT INTO delegacias values (611, '003 DP - Atibaia'); 
INSERT INTO delegacias values (612, 'DM - Piracaia'); 
INSERT INTO delegacias values (613, 'DM - Vargem'); 
INSERT INTO delegacias values (614, '001 DP - Cabreuva'); 
INSERT INTO delegacias values (615, '001 DP - Várzea Pta.'); 
INSERT INTO delegacias values (616, 'DM - Jaguariúna'); 
INSERT INTO delegacias values (617, '001 DP - Barretos'); 
INSERT INTO delegacias values (618, 'DM - Jaborandi'); 
INSERT INTO delegacias values (619, 'DM - Sta. Rosa Viterbo'); 
INSERT INTO delegacias values (620, 'DM - Serra Azul'); 
INSERT INTO delegacias values (621, '001 DP - Porto Ferreira'); 
INSERT INTO delegacias values (622, 'DM - Pitangueiras'); 
INSERT INTO delegacias values (623, 'DM - Queiroz'); 
INSERT INTO delegacias values (624, 'DM - Novo Horizonte'); 
INSERT INTO delegacias values (625, 'DM - Monções'); 
INSERT INTO delegacias values (626, 'DM - Juquiá'); 
INSERT INTO delegacias values (627, '001 DP - Santos'); 
INSERT INTO delegacias values (628, 'DM - Conchas'); 
INSERT INTO delegacias values (629, 'DM - São Miguel Arcanjo'); 
INSERT INTO delegacias values (630, '001 DP - Itapeva'); 
INSERT INTO delegacias values (631, '007 DP - Sorocaba'); 
INSERT INTO delegacias values (632, 'DM - Paulicéia'); 
INSERT INTO delegacias values (633, 'DM - Espírito Sto. do Pinhal'); 
INSERT INTO delegacias values (634, '007 DP - Lapa'); 
INSERT INTO delegacias values (635, '024 DP - Ponte Rasa'); 
INSERT INTO delegacias values (636, '001 DP - Cruzeiro'); 
INSERT INTO delegacias values (637, 'DM - Barbosa'); 
INSERT INTO delegacias values (638, 'DM - Clementina'); 
INSERT INTO delegacias values (639, '012 DP - Campinas'); 
INSERT INTO delegacias values (640, '013 DP - Campinas'); 
INSERT INTO delegacias values (641, 'DM - Nazaré Pta.'); 
INSERT INTO delegacias values (642, 'DM - Socorro'); 
INSERT INTO delegacias values (643, '003 DP - Franca'); 
INSERT INTO delegacias values (644, 'DM - Presidente Alves'); 
INSERT INTO delegacias values (645, 'DM - Bocaina'); 
INSERT INTO delegacias values (646, 'DM - Elisiário'); 
INSERT INTO delegacias values (647, 'DM - Palmeira do Oeste'); 
INSERT INTO delegacias values (648, '001 DP - Itanhaem'); 
INSERT INTO delegacias values (649, '003 DP - Itanhaem'); 
INSERT INTO delegacias values (650, '001 DP - Mongaguá'); 
INSERT INTO delegacias values (651, 'DM - Sete Barras'); 
INSERT INTO delegacias values (652, '002 DP - Cubatão'); 
INSERT INTO delegacias values (653, '003 DP - Pirassununga'); 
INSERT INTO delegacias values (654, '001 DP - Guarulhos'); 
INSERT INTO delegacias values (655, 'DM - Paraibuna'); 
INSERT INTO delegacias values (656, '004 DP - Araraquara'); 
INSERT INTO delegacias values (657, 'DM - Itirapuã'); 
INSERT INTO delegacias values (658, 'DM - São Simão'); 
INSERT INTO delegacias values (659, 'DM - Pirajui'); 
INSERT INTO delegacias values (660, '001 DP - Garça'); 
INSERT INTO delegacias values (661, 'DM - Garça'); 
INSERT INTO delegacias values (662, 'DM - S. Pedro do Turvo'); 
INSERT INTO delegacias values (663, 'DM - Paranapuã'); 
INSERT INTO delegacias values (664, 'DM - Guapiaçú'); 
INSERT INTO delegacias values (665, 'DM - Potirendaba'); 
INSERT INTO delegacias values (666, 'DM - Peruíbe'); 
INSERT INTO delegacias values (667, 'DM - Paranapanema'); 
INSERT INTO delegacias values (668, 'DM - Tapiraí'); 
INSERT INTO delegacias values (669, 'DM - Lucélia'); 
INSERT INTO delegacias values (670, 'DM - Ouro Verde'); 
INSERT INTO delegacias values (671, 'DM - Panorama'); 
INSERT INTO delegacias values (672, 'DM - Ilhabela'); 
INSERT INTO delegacias values (673, '001 DP - Valinhos'); 
INSERT INTO delegacias values (674, 'DM - Itatiba'); 
INSERT INTO delegacias values (675, '001 DP - Jundiai'); 
INSERT INTO delegacias values (676, 'DM - Boa Esperança Sul'); 
INSERT INTO delegacias values (677, 'DM - Terra Roxa'); 
INSERT INTO delegacias values (678, 'DM - Igarapava'); 
INSERT INTO delegacias values (679, 'DM - Patrocínio Pta.'); 
INSERT INTO delegacias values (680, 'DM - Restinga'); 
INSERT INTO delegacias values (681, 'DM - Ipuã'); 
INSERT INTO delegacias values (682, 'DM - Piratininga'); 
INSERT INTO delegacias values (683, '002 DP - Jaú'); 
INSERT INTO delegacias values (684, '004 DP - Jaú'); 
INSERT INTO delegacias values (685, 'DM - Chavantes'); 
INSERT INTO delegacias values (686, 'DM - Quatá'); 
INSERT INTO delegacias values (687, 'DM - Urãnia'); 
INSERT INTO delegacias values (688, 'DM - Eldorado'); 
INSERT INTO delegacias values (689, 'DM - Itaporanga'); 
INSERT INTO delegacias values (690, '001 DP - Pirajú'); 
INSERT INTO delegacias values (691, 'DM - Laranjal Pta.'); 
INSERT INTO delegacias values (692, 'DM - Cerquilho'); 
INSERT INTO delegacias values (693, 'DM - B. Sucesso / Itararé'); 
INSERT INTO delegacias values (694, 'DM - Itapirapuã Pta.'); 
INSERT INTO delegacias values (695, '001 DP - Rosana'); 
INSERT INTO delegacias values (696, 'DM - Sto. Anastácio'); 
INSERT INTO delegacias values (697, 'DM - Sta. Maria da Serra'); 
INSERT INTO delegacias values (698, 'DM - Guararema'); 
INSERT INTO delegacias values (699, 'DM - Estrela do Oeste'); 
INSERT INTO delegacias values (700, '007 DP - Santos'); 
INSERT INTO delegacias values (701, 'DM - Tarumã'); 
INSERT INTO delegacias values (702, 'DM - União Pta.'); 
INSERT INTO delegacias values (703, 'DM - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (704, 'DM - Paulo de Faria'); 
INSERT INTO delegacias values (705, 'DM - Monteiro Lobato'); 
INSERT INTO delegacias values (706, 'DM - Guaíra'); 
INSERT INTO delegacias values (707, '002 DP - Itapira'); 
INSERT INTO delegacias values (708, 'DM - São João das Duas Pontes'); 
INSERT INTO delegacias values (709, 'DM - Ribeirão do Sul'); 
INSERT INTO delegacias values (710, '002 DP - Presidente Prudente'); 
INSERT INTO delegacias values (711, '001 DP - Sta. Cruz do Rio Pardo'); 
INSERT INTO delegacias values (712, 'DM - Pontes Gestal'); 
INSERT INTO delegacias values (713, 'DM - Guaiçara'); 
INSERT INTO delegacias values (714, 'DM - Capão Bonito'); 
INSERT INTO delegacias values (715, 'DM - Alvinlândia'); 
INSERT INTO delegacias values (716, 'DM - Charqueada'); 
INSERT INTO delegacias values (717, 'DM - Guaimbe'); 
INSERT INTO delegacias values (718, 'DM - Matão'); 
INSERT INTO delegacias values (719, 'DM - Iacanga'); 
INSERT INTO delegacias values (720, 'DM - Tapiratiba'); 
INSERT INTO delegacias values (721, 'DM - Rincão'); 
INSERT INTO delegacias values (722, '001 DP - Amparo'); 
INSERT INTO delegacias values (723, 'DM - Lourdes'); 
INSERT INTO delegacias values (724, 'DM - Santa Albertina'); 
INSERT INTO delegacias values (725, 'DM - Itirapina'); 
INSERT INTO delegacias values (726, '003 DP - Jundiai'); 
INSERT INTO delegacias values (727, '004 DP - Botucatu'); 
INSERT INTO delegacias values (728, 'DM - Queluz'); 
INSERT INTO delegacias values (729, 'DM - Cafelândia'); 
INSERT INTO delegacias values (730, '001 DP - Ribeirão Preto'); 
INSERT INTO delegacias values (731, 'DM - São Bento do Sapucaí'); 
INSERT INTO delegacias values (732, 'DM - Bofete'); 
INSERT INTO delegacias values (733, '008 DP - São Jose dos Campos'); 
INSERT INTO delegacias values (734, 'DM - Valinhos'); 
INSERT INTO delegacias values (735, '004 DP - Itapeva'); 
INSERT INTO delegacias values (736, 'DM - Porangaba'); 
INSERT INTO delegacias values (737, 'DM - Biritiba Mirim'); 
INSERT INTO delegacias values (738, 'DM - Suzanópolis'); 
INSERT INTO delegacias values (739, 'DM - Barra Bonita'); 
INSERT INTO delegacias values (740, 'DM - Canitar'); 
INSERT INTO delegacias values (741, 'DM - Dobrada'); 
INSERT INTO delegacias values (742, 'DM - Ipaussu'); 
INSERT INTO delegacias values (743, 'DM - Borborema'); 
INSERT INTO delegacias values (744, 'DM - Barra do Turvo'); 
INSERT INTO delegacias values (745, 'DM - Sales'); 
INSERT INTO delegacias values (746, 'DM - Echaporã'); 
INSERT INTO delegacias values (747, '001 DP - Adamantina'); 
INSERT INTO delegacias values (748, 'DM - Santa Branca'); 
INSERT INTO delegacias values (749, 'DM - Gaviao Peixoto'); 
INSERT INTO delegacias values (750, 'DM - Joanópolis'); 
INSERT INTO delegacias values (751, 'DM - Sebastianópolis do Sul'); 
INSERT INTO delegacias values (752, 'Delegacia Aeroporto Int. SP - Guarulhos'); 
INSERT INTO delegacias values (753, 'DM - Populina'); 
INSERT INTO delegacias values (754, '001 DP - Jales'); 
INSERT INTO delegacias values (755, 'DM - Itararé'); 
INSERT INTO delegacias values (756, 'DM - Ocauçú'); 
INSERT INTO delegacias values (757, 'DM - Severínia'); 
INSERT INTO delegacias values (758, 'DM - Brotas'); 
INSERT INTO delegacias values (759, 'DM - Buritizal'); 
INSERT INTO delegacias values (760, 'DM - Cesário Lange'); 
INSERT INTO delegacias values (761, '004 DP - Araçatuba'); 
INSERT INTO delegacias values (762, 'DM - Junqueirópolis'); 
INSERT INTO delegacias values (763, 'DM - Itapura'); 
INSERT INTO delegacias values (764, '002 DP - Itapetininga'); 
INSERT INTO delegacias values (765, 'DM - Florida Pta.'); 
INSERT INTO delegacias values (766, 'DM - Santa Lúcia'); 
INSERT INTO delegacias values (767, '005 DP - Sorocaba'); 
INSERT INTO delegacias values (768, '001 DP - Paraguaçú Pta.'); 
INSERT INTO delegacias values (769, 'DM - Palmares Pta.'); 
INSERT INTO delegacias values (770, '002 DP - São Bernardo do Campo'); 
INSERT INTO delegacias values (771, 'DM - Vista Alegre/Alto'); 
INSERT INTO delegacias values (772, 'DM - Pirapozinho'); 
INSERT INTO delegacias values (773, 'DM - Corumbataí'); 
INSERT INTO delegacias values (774, 'DM - Itajú'); 
INSERT INTO delegacias values (775, '001 DP - Penapolis'); 
INSERT INTO delegacias values (776, '001 DP - Taubaté'); 
INSERT INTO delegacias values (777, 'DM - Cabrália Paulista'); 
INSERT INTO delegacias values (778, 'DM - Orlândia'); 
INSERT INTO delegacias values (779, 'DM - Sta. Mercedes'); 
INSERT INTO delegacias values (780, 'DM - Ribeira'); 
INSERT INTO delegacias values (781, '003 DP - São Sebastião'); 
INSERT INTO delegacias values (782, 'DM - Coronel Macedo'); 
INSERT INTO delegacias values (783, 'DM - Campina Monte Alegre'); 
INSERT INTO delegacias values (784, 'DM - Salto'); 
INSERT INTO delegacias values (785, 'DM - Nova Campina'); 
INSERT INTO delegacias values (786, 'DM - Pardinho'); 
INSERT INTO delegacias values (787, 'DM - Lavinia'); 
INSERT INTO delegacias values (788, '001 DP - São José do Rio Preto'); 
INSERT INTO delegacias values (789, 'DM - Macatuba'); 
INSERT INTO delegacias values (790, 'DM - Indaiatuba'); 
INSERT INTO delegacias values (791, 'DM - Cristais Pta.'); 
INSERT INTO delegacias values (792, '014 DP - Pinheiros'); 
INSERT INTO delegacias values (793, 'DM - Lupércio'); 
INSERT INTO delegacias values (794, 'DM - Ilha Solteira'); 
INSERT INTO delegacias values (795, '003 DP - Tupã'); 
INSERT INTO delegacias values (796, '002 DP - Jales'); 
INSERT INTO delegacias values (797, 'DM - Conchal'); 
INSERT INTO delegacias values (798, 'DM - Salesópolis'); 
INSERT INTO delegacias values (799, 'DM - Onda Verde'); 
INSERT INTO delegacias values (800, 'DM - Ibirarema'); 
INSERT INTO delegacias values (801, '003 DP - Avaré'); 
INSERT INTO delegacias values (802, 'DM - Sarutaiá'); 
INSERT INTO delegacias values (803, 'DM - Lindóia'); 
INSERT INTO delegacias values (804, 'DM - Getulina'); 
INSERT INTO delegacias values (805, 'DM - Parapuã'); 
INSERT INTO delegacias values (806, 'DM - Icém'); 
INSERT INTO delegacias values (807, 'DM - Itaberá'); 
INSERT INTO delegacias values (808, 'DM - Morungaba'); 
INSERT INTO delegacias values (809, 'DM - Rib. Grande'); 
INSERT INTO delegacias values (810, '001 DP - Piracicaba'); 
INSERT INTO delegacias values (811, 'DM - Iracemápolis'); 
INSERT INTO delegacias values (812, 'DM - Cananéia'); 
INSERT INTO delegacias values (813, 'DM - Mira Estrela'); 
INSERT INTO delegacias values (814, 'DM - Américo de Campos'); 
INSERT INTO delegacias values (815, 'DM - Reginópolis'); 